Repository DKU-Dgaja/gitudy, pull requests merged in 2023-12, with the labels that each got.

#9 docs: 홍찬희 프로필 수정
  README.md
Labels: docs

#12 docs: 이정우 프로필 수정
  README.md
Labels: docs

#11 docs: 구영민 프로필 수정
  README.md
Labels: docs

#16 [ALL] refactor(#6): README 프로필 수정
  README.md
Labels: refactor, 탁세하 진행중🔥

#15 chore: pull requests template 적용
  .github/issue_template.md
  .github/pull_request_template.md
  .gitignore
Labels: chore
