Repository DKU-Dgaja/gitudy, pull requests merged in 2024-02, with the labels that each got.

#81 [BE] Feat(#65): 회원가입 및 탈퇴 구현
  backend/src/main/java/com/example/backend/auth/api/controller/auth/AuthController.java
  backend/src/main/java/com/example/backend/auth/api/controller/auth/request/AuthRegisterRequest.java
  backend/src/main/java/com/example/backend/auth/api/service/auth/AuthService.java
  backend/src/main/java/com/example/backend/auth/api/service/auth/request/AuthServiceRegisterRequest.java
  backend/src/main/java/com/example/backend/auth/api/service/auth/response/AuthServiceLoginResponse.java
  backend/src/main/java/com/example/backend/common/exception/ExceptionMessage.java
  backend/src/main/java/com/example/backend/common/exception/auth/AuthException.java
  backend/src/main/java/com/example/backend/domain/define/account/user/User.java
  backend/src/test/java/com/example/backend/auth/api/controller/auth/AuthControllerTest.java
  backend/src/test/java/com/example/backend/auth/api/service/auth/AuthServiceTest.java
Labels: feat, test

#84 [BE] feat(#39): 유저 정보 조회
  backend/src/main/java/com/example/backend/auth/api/controller/auth/AuthController.java
  backend/src/main/java/com/example/backend/auth/api/controller/auth/response/UserInfoResponse.java
  backend/src/main/java/com/example/backend/auth/api/service/auth/AuthService.java
  backend/src/main/java/com/example/backend/common/exception/ExceptionMessage.java
  backend/src/main/java/com/example/backend/common/exception/user/UserException.java
  backend/src/test/java/com/example/backend/auth/api/controller/auth/AuthControllerTest.java
  backend/src/test/java/com/example/backend/auth/api/service/auth/AuthServiceTest.java
Labels: feat, 이정우 진행중🔥

#88 [AN] feat(#86): 마이스터디 관련 페이지 UI 구현
  frontend/presentation/src/main/AndroidManifest.xml
  frontend/presentation/src/main/java/com/takseha/presentation/ui/home/ToDoActivity.kt
  frontend/presentation/src/main/java/com/takseha/presentation/ui/mystudy/MyStudyMainActivity.kt
  frontend/presentation/src/main/res/drawable/box_non_stroke_r8.xml
  frontend/presentation/src/main/res/drawable/ic_filter.png
  frontend/presentation/src/main/res/drawable/ic_lock.png
  frontend/presentation/src/main/res/drawable/ic_noti.png
  frontend/presentation/src/main/res/drawable/ic_plus.png
  frontend/presentation/src/main/res/drawable/ic_rank.png
  frontend/presentation/src/main/res/drawable/ic_search.png
  frontend/presentation/src/main/res/drawable/ic_smile.png
  frontend/presentation/src/main/res/drawable/ic_study_commit.png
  frontend/presentation/src/main/res/drawable/ic_study_github_link.png
  frontend/presentation/src/main/res/drawable/ic_thumbs_up.png
  frontend/presentation/src/main/res/drawable/ic_todo_git.png
  frontend/presentation/src/main/res/drawable/img_study_background_1.png
  frontend/presentation/src/main/res/drawable/img_study_background_2.png
  frontend/presentation/src/main/res/drawable/logo_blog_700.png
  frontend/presentation/src/main/res/drawable/logo_git.png
  frontend/presentation/src/main/res/drawable/progress_bar.xml
  frontend/presentation/src/main/res/layout/activity_main_home.xml
  frontend/presentation/src/main/res/layout/activity_my_study_main.xml
  frontend/presentation/src/main/res/layout/activity_profile_edit.xml
  frontend/presentation/src/main/res/layout/activity_to_do.xml
  frontend/presentation/src/main/res/layout/fragment_agreement_popup.xml
  frontend/presentation/src/main/res/layout/fragment_edit_nickname.xml
  frontend/presentation/src/main/res/layout/fragment_main_home.xml
  frontend/presentation/src/main/res/layout/fragment_my_commit_detail.xml
  frontend/presentation/src/main/res/layout/fragment_my_study_home.xml
  frontend/presentation/src/main/res/layout/fragment_popup_detail1.xml
  frontend/presentation/src/main/res/layout/fragment_popup_detail2.xml
  frontend/presentation/src/main/res/layout/fragment_popup_detail3.xml
  frontend/presentation/src/main/res/layout/fragment_profile_home.xml
  frontend/presentation/src/main/res/values/strings.xml
Labels: feat, 탁세하 진행중🔥

#90 [BE] fix(#89): resolve conflicts
  backend/src/main/java/com/example/backend/auth/api/controller/auth/AuthController.java
  backend/src/main/java/com/example/backend/common/exception/ExceptionMessage.java
  backend/src/test/java/com/example/backend/auth/api/controller/auth/AuthControllerTest.java
  backend/src/test/java/com/example/backend/auth/api/service/auth/AuthServiceTest.java
Labels: fix, 이정우 진행중🔥

#92 [BE] refactor(#91): 데이터베이스 설계 수정
  backend/src/main/java/com/example/backend/auth/api/controller/auth/response/UserInfoResponse.java
  backend/src/main/java/com/example/backend/domain/define/account/user/User.java
  backend/src/main/java/com/example/backend/domain/define/study/commit/StudyCommit.java
  backend/src/main/java/com/example/backend/domain/define/study/commit/constant/LikeCount.java
  backend/src/main/java/com/example/backend/domain/define/study/todo/info/StudyTodo.java
  backend/src/test/java/com/example/backend/auth/TestConfig.java
  backend/src/test/java/com/example/backend/auth/api/controller/auth/AuthControllerTest.java
  backend/src/test/java/com/example/backend/auth/api/service/auth/AuthServiceTest.java
  backend/src/test/java/com/example/backend/domain/define/study/commit/constant/LikeCountTest.java
Labels: refactor, 이주성 진행중🔥

#95 [BE] feat(#87): 회원 정보 수정 & 푸시 알림 수정 api 구현
  backend/src/main/java/com/example/backend/auth/api/controller/auth/AuthController.java
  backend/src/main/java/com/example/backend/auth/api/controller/auth/request/UserUpdateRequest.java
  backend/src/main/java/com/example/backend/auth/api/controller/auth/response/UserInfoResponse.java
  backend/src/main/java/com/example/backend/auth/api/service/auth/AuthService.java
  backend/src/main/java/com/example/backend/auth/api/service/auth/request/UserUpdateServiceRequest.java
  backend/src/main/java/com/example/backend/auth/api/service/auth/response/UserUpdatePageResponse.java
  backend/src/main/java/com/example/backend/auth/config/security/SecurityConfig.java
  backend/src/main/java/com/example/backend/common/exception/ExceptionMessage.java
  backend/src/main/java/com/example/backend/common/utils/EmailValidator.java
  backend/src/main/java/com/example/backend/common/validation/SocialInfoValidator.java
  backend/src/main/java/com/example/backend/common/validation/ValidSocialInfo.java
  backend/src/main/java/com/example/backend/domain/define/account/social/SocialAccountLink.java
  backend/src/main/java/com/example/backend/domain/define/account/social/constant/SocialType.java
  backend/src/main/java/com/example/backend/domain/define/account/user/SocialInfo.java
  backend/src/main/java/com/example/backend/domain/define/account/user/User.java
  backend/src/main/java/com/example/backend/external/clients/oauth/github/response/GithubProfileResponse.java
  backend/src/test/java/com/example/backend/auth/TestConfig.java
  backend/src/test/java/com/example/backend/auth/api/controller/auth/AuthControllerTest.java
  backend/src/test/java/com/example/backend/auth/api/service/auth/AuthServiceTest.java
  backend/src/test/java/com/example/backend/auth/api/service/jwt/JwtServiceTest.java
  backend/src/test/java/com/example/backend/auth/api/service/oauth/OAuthServiceTest.java
  backend/src/test/java/com/example/backend/auth/config/fixture/UserFixture.java
  backend/src/test/java/com/example/backend/common/utils/TokenUtil.java
  backend/src/test/java/com/example/backend/domain/define/test/repository/DslTestRepositoryTest.java
  backend/src/test/java/com/example/backend/domain/define/user/repository/UserRepositoryTest.java
Labels: feat, 이주성 진행중🔥

#110 [AN] feat(#103): 전체 스터디 관련 페이지 UI 구현
  frontend/presentation/src/main/AndroidManifest.xml
  frontend/presentation/src/main/java/com/takseha/presentation/ui/feed/MakeStudy1Fragment.kt
  frontend/presentation/src/main/java/com/takseha/presentation/ui/feed/MakeStudy2Fragment.kt
  frontend/presentation/src/main/java/com/takseha/presentation/ui/feed/MakeStudy3Fragment.kt
  frontend/presentation/src/main/java/com/takseha/presentation/ui/feed/MakeStudy4Fragment.kt
  frontend/presentation/src/main/java/com/takseha/presentation/ui/feed/NewStudyFragment.kt
  frontend/presentation/src/main/java/com/takseha/presentation/ui/feed/StudyApplyActivity.kt
  frontend/presentation/src/main/java/com/takseha/presentation/ui/feed/StudyApplyFragment.kt
  frontend/presentation/src/main/res/drawable/box_stroke_200_r8.xml
  frontend/presentation/src/main/res/drawable/ic_feed_save.png
  frontend/presentation/src/main/res/drawable/ic_minus_r.png
  frontend/presentation/src/main/res/drawable/ic_people.png
  frontend/presentation/src/main/res/drawable/ic_plus_r.png
  frontend/presentation/src/main/res/drawable/ic_study_blue.png
  frontend/presentation/src/main/res/drawable/ic_study_green.png
  frontend/presentation/src/main/res/drawable/ic_study_grey.png
  frontend/presentation/src/main/res/drawable/ic_study_orange.png
  frontend/presentation/src/main/res/drawable/ic_study_pink.png
  frontend/presentation/src/main/res/layout/activity_study_apply.xml
  frontend/presentation/src/main/res/layout/fragment_edit_nickname.xml
  frontend/presentation/src/main/res/layout/fragment_feed_home.xml
  frontend/presentation/src/main/res/layout/fragment_make_study1.xml
  frontend/presentation/src/main/res/layout/fragment_make_study2.xml
  frontend/presentation/src/main/res/layout/fragment_make_study3.xml
  frontend/presentation/src/main/res/layout/fragment_make_study4.xml
  frontend/presentation/src/main/res/layout/fragment_my_commit_detail.xml
  frontend/presentation/src/main/res/layout/fragment_new_study.xml
  frontend/presentation/src/main/res/layout/fragment_quit_study.xml
  frontend/presentation/src/main/res/layout/fragment_recommand_new_study.xml
  frontend/presentation/src/main/res/layout/fragment_study_apply.xml
  frontend/presentation/src/main/res/values/strings.xml
Labels: feat, 탁세하 진행중🔥

#107 [BE] feat(#106): 북마크 목록 조회 & 등록/삭제 api 구현
  backend/src/main/java/com/example/backend/auth/api/controller/auth/response/UserInfoResponse.java
  backend/src/main/java/com/example/backend/auth/api/service/auth/AuthService.java
  backend/src/main/java/com/example/backend/common/exception/ExceptionMessage.java
  backend/src/main/java/com/example/backend/common/exception/bookmark/BookmarkException.java
  backend/src/main/java/com/example/backend/domain/define/account/bookmark/repository/StudyBookmarkRepository.java
  backend/src/main/java/com/example/backend/domain/define/account/bookmark/repository/StudyBookmarkRepositoryCustom.java
  backend/src/main/java/com/example/backend/domain/define/account/bookmark/repository/StudyBookmarkRepositoryImpl.java
  backend/src/main/java/com/example/backend/domain/define/study/info/repository/StudyInfoRepository.java
  backend/src/main/java/com/example/backend/study/api/controller/bookmark/StudyBookmarkController.java
  backend/src/main/java/com/example/backend/study/api/controller/bookmark/response/BookmarkInfoListAndCursorIdxResponse.java
  backend/src/main/java/com/example/backend/study/api/service/bookmark/StudyBookmarkService.java
  backend/src/main/java/com/example/backend/study/api/service/bookmark/response/BookmarkInfoResponse.java
  backend/src/main/java/com/example/backend/study/api/service/info/response/StudyInfoWithIdResponse.java
  backend/src/test/java/com/example/backend/auth/TestConfig.java
  backend/src/test/java/com/example/backend/auth/api/controller/auth/AuthControllerTest.java
  backend/src/test/java/com/example/backend/auth/api/service/auth/AuthServiceTest.java
  backend/src/test/java/com/example/backend/auth/api/service/oauth/OAuthServiceTest.java
  backend/src/test/java/com/example/backend/auth/config/fixture/UserFixture.java
  backend/src/test/java/com/example/backend/common/utils/TokenUtil.java
  backend/src/test/java/com/example/backend/domain/define/account/bookmark/StudyBookmarkFixture.java
  backend/src/test/java/com/example/backend/domain/define/account/bookmark/repository/StudyBookmarkRepositoryTest.java
  backend/src/test/java/com/example/backend/domain/define/study/info/StudyInfoFixture.java
  backend/src/test/java/com/example/backend/study/api/controller/bookmark/StudyBookmarkControllerTest.java
  backend/src/test/java/com/example/backend/study/api/service/bookmark/StudyBookmarkServiceTest.java
Labels: feat, 이주성 진행중🔥

#120 [BE] feat(#118): StudyMember 권한 검증 관련 공통 로직 구현
  backend/src/main/java/com/example/backend/domain/define/study/member/repository/StudyMemberRepository.java
  backend/src/main/java/com/example/backend/domain/define/study/member/repository/StudyMemberRepositoryCustom.java
  backend/src/main/java/com/example/backend/domain/define/study/member/repository/StudyMemberRepositoryImpl.java
  backend/src/test/java/com/example/backend/domain/define/study/member/StudyMemberFixture.java
  backend/src/test/java/com/example/backend/domain/define/study/member/repository/StudyMemberRepositoryTest.java
Labels: feat, 이주성 진행중🔥

#126 Refactor(#125) @json property 제거
  backend/src/main/java/com/example/backend/auth/api/controller/auth/request/AuthRegisterRequest.java
  backend/src/test/java/com/example/backend/auth/api/controller/auth/AuthControllerTest.java
Labels: refactor

#121 [BE] feat(#117): Todo 등록 api 구현
  backend/src/main/java/com/example/backend/auth/config/ProjectConfig.java
  backend/src/main/java/com/example/backend/common/exception/ExceptionMessage.java
  backend/src/main/java/com/example/backend/common/exception/member/MemberException.java
  backend/src/main/java/com/example/backend/common/exception/todo/TodoException.java
  backend/src/main/java/com/example/backend/domain/define/study/member/repository/StudyMemberRepository.java
  backend/src/main/java/com/example/backend/domain/define/study/member/repository/StudyMemberRepositoryCustom.java
  backend/src/main/java/com/example/backend/domain/define/study/member/repository/StudyMemberRepositoryImpl.java
  backend/src/main/java/com/example/backend/domain/define/study/todo/repository/StudyTodoMappingRepository.java
  backend/src/main/java/com/example/backend/domain/define/study/todo/repository/StudyTodoRepository.java
  backend/src/main/java/com/example/backend/study/api/controller/todo/StudyTodoController.java
  backend/src/main/java/com/example/backend/study/api/controller/todo/request/StudyTodoRequest.java
  backend/src/main/java/com/example/backend/study/api/service/member/StudyMemberService.java
  backend/src/main/java/com/example/backend/study/api/service/todo/StudyTodoService.java
  backend/src/test/java/com/example/backend/auth/config/fixture/UserFixture.java
  backend/src/test/java/com/example/backend/domain/define/study/member/StudyMemberFixture.java
  backend/src/test/java/com/example/backend/domain/define/study/member/repository/StudyMemberRepositoryTest.java
  backend/src/test/java/com/example/backend/domain/define/study/todo/StudyTodoFixture.java
  backend/src/test/java/com/example/backend/study/api/controller/todo/StudyTodoControllerTest.java
  backend/src/test/java/com/example/backend/study/api/service/todo/StudyTodoServiceTest.java
Labels: feat, 이정우 진행중🔥

#115 [BE] Feat(#114) 스터디 등록 api 구현
  backend/src/main/java/com/example/backend/domain/define/study/info/StudyInfo.java
  backend/src/main/java/com/example/backend/domain/define/study/member/repository/StudyMemberRepository.java
  backend/src/main/java/com/example/backend/study/api/controller/info/StudyInfoController.java
  backend/src/main/java/com/example/backend/study/api/controller/info/request/StudyInfoRegisterRequest.java
  backend/src/main/java/com/example/backend/study/api/controller/info/response/StudyInfoRegisterResponse.java
  backend/src/main/java/com/example/backend/study/api/service/category/info/repository/StudyCategoryRepository.java
  backend/src/main/java/com/example/backend/study/api/service/category/mapping/repository/StudyCategoryMappingRepository.java
  backend/src/main/java/com/example/backend/study/api/service/info/StudyInfoService.java
  backend/src/test/java/com/example/backend/auth/TestConfig.java
  backend/src/test/java/com/example/backend/domain/define/study/StudyCategory/StudyCategoryFixture.java
  backend/src/test/java/com/example/backend/domain/define/study/info/StudyInfoFixture.java
  backend/src/test/java/com/example/backend/study/api/controller/info/StudyInfoControllerTest.java
  backend/src/test/java/com/example/backend/study/api/service/info/StudyInfoServiceTest.java
Labels: feat, 구영민 진행중🔥

#128 [BE] feat(#123): Todo 삭제 api
  backend/src/main/java/com/example/backend/common/exception/ExceptionMessage.java
  backend/src/main/java/com/example/backend/domain/define/study/todo/repository/StudyTodoMappingRepository.java
  backend/src/main/java/com/example/backend/domain/define/study/todo/repository/StudyTodoRepository.java
  backend/src/main/java/com/example/backend/study/api/controller/todo/StudyTodoController.java
  backend/src/main/java/com/example/backend/study/api/service/todo/StudyTodoService.java
  backend/src/test/java/com/example/backend/study/api/controller/todo/StudyTodoControllerTest.java
  backend/src/test/java/com/example/backend/study/api/service/todo/StudyTodoServiceTest.java
Labels: feat, 이정우 진행중🔥

#130 [BE] feat(#124): 스터디 삭제 api 구현
  backend/src/main/java/com/example/backend/common/exception/study/StudyInfoException.java
  backend/src/main/java/com/example/backend/domain/define/study/category/info/repository/StudyCategoryRepository.java
  backend/src/main/java/com/example/backend/domain/define/study/category/mapping/repository/StudyCategoryMappingRepository.java
  backend/src/main/java/com/example/backend/domain/define/study/info/StudyInfo.java
  backend/src/main/java/com/example/backend/domain/define/study/member/StudyMember.java
  backend/src/main/java/com/example/backend/domain/define/study/member/repository/StudyMemberRepository.java
  backend/src/main/java/com/example/backend/study/api/controller/info/StudyInfoController.java
  backend/src/main/java/com/example/backend/study/api/service/info/StudyInfoService.java
  backend/src/test/java/com/example/backend/auth/config/fixture/UserFixture.java
  backend/src/test/java/com/example/backend/study/api/controller/info/StudyInfoControllerTest.java
  backend/src/test/java/com/example/backend/study/api/service/info/StudyInfoServiceTest.java
Labels: feat, 구영민 진행중🔥

#131 [BE] feat(#129): Todo 수정 api
  backend/src/main/java/com/example/backend/domain/define/study/todo/info/StudyTodo.java
  backend/src/main/java/com/example/backend/study/api/controller/todo/StudyTodoController.java
  backend/src/main/java/com/example/backend/study/api/controller/todo/request/StudyTodoUpdateRequest.java
  backend/src/main/java/com/example/backend/study/api/service/todo/StudyTodoService.java
  backend/src/test/java/com/example/backend/domain/define/study/todo/StudyTodoFixture.java
  backend/src/test/java/com/example/backend/study/api/controller/todo/StudyTodoControllerTest.java
  backend/src/test/java/com/example/backend/study/api/service/todo/StudyTodoServiceTest.java
Labels: feat, 이정우 진행중🔥

#133 [BE] feat(#132) 스터디 수정 api 구현
  backend/src/main/java/com/example/backend/domain/define/study/category/info/repository/StudyCategoryRepository.java
  backend/src/main/java/com/example/backend/domain/define/study/category/mapping/repository/StudyCategoryMappingRepository.java
  backend/src/main/java/com/example/backend/domain/define/study/info/StudyInfo.java
  backend/src/main/java/com/example/backend/study/api/controller/info/StudyInfoController.java
  backend/src/main/java/com/example/backend/study/api/controller/info/request/StudyInfoUpdateRequest.java
  backend/src/main/java/com/example/backend/study/api/controller/info/response/UpdateStudyInfoPageResponse.java
  backend/src/main/java/com/example/backend/study/api/service/info/StudyInfoService.java
  backend/src/test/java/com/example/backend/domain/define/study/StudyCategory/info/StudyCategoryFixture.java
  backend/src/test/java/com/example/backend/domain/define/study/StudyCategory/mapping/StudyCategoryMappingFixture.java
  backend/src/test/java/com/example/backend/domain/define/study/info/StudyInfoFixture.java
  backend/src/test/java/com/example/backend/study/api/controller/info/StudyInfoControllerTest.java
  backend/src/test/java/com/example/backend/study/api/service/info/StudyInfoServiceTest.java
Labels: feat, 구영민 진행중🔥

#98 [BE] feat(#96): 마이 커밋 조회 api 구현
  backend/src/main/java/com/example/backend/auth/api/controller/auth/AuthController.java
  backend/src/main/java/com/example/backend/common/exception/commit/CommitException.java
  backend/src/main/java/com/example/backend/domain/define/study/commit/repository/StudyCommitRepository.java
  backend/src/main/java/com/example/backend/domain/define/study/commit/repository/StudyCommitRepositoryCustom.java
  backend/src/main/java/com/example/backend/domain/define/study/commit/repository/StudyCommitRepositoryImpl.java
  backend/src/main/java/com/example/backend/study/api/controller/commit/StudyCommitController.java
  backend/src/main/java/com/example/backend/study/api/controller/commit/response/CommitInfoListAndCursorIdxResponse.java
  backend/src/main/java/com/example/backend/study/api/service/StudyCommitService.java
  backend/src/main/java/com/example/backend/study/api/service/commit/response/CommitInfoResponse.java
  backend/src/test/java/com/example/backend/domain/define/study/commit/StudyCommitFixture.java
  backend/src/test/java/com/example/backend/domain/define/study/commit/repository/StudyCommitRepositoryTest.java
  backend/src/test/java/com/example/backend/study/api/controller/commit/StudyCommitControllerTest.java
  backend/src/test/java/com/example/backend/study/api/service/StudyCommitServiceTest.java
Labels: feat, 이주성 진행중🔥

#142 Feat(#140) 스터디 댓글 등록 api 구현
  backend/src/main/java/com/example/backend/common/exception/ExceptionMessage.java
  backend/src/main/java/com/example/backend/common/exception/comment/study/StudyCommentException.java
  backend/src/main/java/com/example/backend/domain/define/study/comment/study/repository/StudyCommentRepository.java
  backend/src/main/java/com/example/backend/study/api/controller/comment/study/StudyCommentController.java
  backend/src/main/java/com/example/backend/study/api/controller/comment/study/request/StudyCommentRegisterRequest.java
  backend/src/main/java/com/example/backend/study/api/service/comment/study/StudyCommentService.java
  backend/src/test/java/com/example/backend/domain/define/study/comment/StudyCommentFixture.java
  backend/src/test/java/com/example/backend/study/api/controller/comment/study/StudyCommentControllerTest.java
  backend/src/test/java/com/example/backend/study/api/service/comment/study/StudyCommentServiceTest.java
Labels: feat, 구영민 진행중🔥

#145 [BE] feat: (#144) 스터디 댓글 수정 api
  backend/src/main/java/com/example/backend/common/exception/ExceptionMessage.java
  backend/src/main/java/com/example/backend/domain/define/study/comment/study/StudyComment.java
  backend/src/main/java/com/example/backend/study/api/controller/comment/study/StudyCommentController.java
  backend/src/main/java/com/example/backend/study/api/controller/comment/study/request/StudyCommentUpdateRequest.java
  backend/src/main/java/com/example/backend/study/api/service/comment/study/StudyCommentService.java
  backend/src/test/java/com/example/backend/domain/define/study/comment/StudyCommentFixture.java
  backend/src/test/java/com/example/backend/study/api/controller/comment/study/StudyCommentControllerTest.java
  backend/src/test/java/com/example/backend/study/api/service/comment/study/StudyCommentServiceTest.java
Labels: feat, 구영민 진행중🔥

#137 [BE] feat(#134): Todo 전체조회 api
  backend/src/main/java/com/example/backend/common/exception/ExceptionMessage.java
  backend/src/main/java/com/example/backend/domain/define/study/todo/mapping/repository/StudyTodoMappingRepository.java
  backend/src/main/java/com/example/backend/domain/define/study/todo/repository/StudyTodoRepository.java
  backend/src/main/java/com/example/backend/domain/define/study/todo/repository/StudyTodoRepositoryCustom.java
  backend/src/main/java/com/example/backend/domain/define/study/todo/repository/StudyTodoRepositoryImpl.java
  backend/src/main/java/com/example/backend/study/api/controller/todo/StudyTodoController.java
  backend/src/main/java/com/example/backend/study/api/controller/todo/response/StudyTodoListAndCursorIdxResponse.java
  backend/src/main/java/com/example/backend/study/api/controller/todo/response/StudyTodoResponse.java
  backend/src/main/java/com/example/backend/study/api/service/member/StudyMemberService.java
  backend/src/main/java/com/example/backend/study/api/service/todo/StudyTodoService.java
  backend/src/test/java/com/example/backend/domain/define/study/todo/StudyTodoFixture.java
  backend/src/test/java/com/example/backend/domain/define/study/todo/repository/StudyTodoRepositoryTest.java
  backend/src/test/java/com/example/backend/study/api/controller/todo/StudyTodoControllerTest.java
  backend/src/test/java/com/example/backend/study/api/service/todo/StudyTodoServiceTest.java
Labels: feat, 이정우 진행중🔥

#116 [BE] feat(#108): 커밋 상세 페이지 조회 api
  backend/src/main/java/com/example/backend/common/exception/ExceptionMessage.java
  backend/src/main/java/com/example/backend/study/api/controller/commit/StudyCommitController.java
  backend/src/main/java/com/example/backend/study/api/service/commit/StudyCommitService.java
  backend/src/main/java/com/example/backend/study/api/service/commit/response/CommitInfoResponse.java
  backend/src/test/java/com/example/backend/domain/define/study/commit/StudyCommitFixture.java
  backend/src/test/java/com/example/backend/study/api/controller/commit/StudyCommitControllerTest.java
  backend/src/test/java/com/example/backend/study/api/service/commit/StudyCommitServiceTest.java
Labels: feat, 이주성 진행중🔥

#127 [BE] feat(#122) 커밋 댓글 리스트 조회 api
  backend/src/main/java/com/example/backend/common/exception/ExceptionMessage.java
  backend/src/main/java/com/example/backend/domain/define/study/comment/commit/repository/CommitCommentRepository.java
  backend/src/main/java/com/example/backend/domain/define/study/comment/commit/repository/CommitCommentRepositoryCustom.java
  backend/src/main/java/com/example/backend/domain/define/study/comment/commit/repository/CommitCommentRepositoryImpl.java
  backend/src/main/java/com/example/backend/study/api/controller/comment/commit/CommitCommentController.java
  backend/src/main/java/com/example/backend/study/api/controller/comment/commit/response/CommitCommentInfoResponse.java
  backend/src/main/java/com/example/backend/study/api/service/comment/commit/CommitCommentService.java
  backend/src/test/java/com/example/backend/domain/define/study/comment/commit/CommitCommentFixture.java
  backend/src/test/java/com/example/backend/domain/define/study/comment/commit/repository/CommitCommentRepositoryTest.java
  backend/src/test/java/com/example/backend/study/api/controller/comment/commit/CommitCommentControllerTest.java
  backend/src/test/java/com/example/backend/study/api/service/comment/commit/CommitCommentServiceTest.java
Labels: feat, 이주성 진행중🔥

#151 [BE] refactor(#150): STUDYCOMMIT 데이터베이스 수정
  backend/src/main/java/com/example/backend/domain/define/study/commit/StudyCommit.java
  backend/src/main/java/com/example/backend/domain/define/study/commit/repository/StudyCommitRepositoryImpl.java
  backend/src/main/java/com/example/backend/study/api/service/commit/response/CommitInfoResponse.java
  backend/src/test/java/com/example/backend/domain/define/study/commit/StudyCommitFixture.java
  backend/src/test/java/com/example/backend/domain/define/study/commit/repository/StudyCommitRepositoryTest.java
  backend/src/test/java/com/example/backend/study/api/service/comment/commit/CommitCommentServiceTest.java
  backend/src/test/java/com/example/backend/study/api/service/commit/StudyCommitServiceTest.java
Labels: refactor, 이주성 진행중🔥

#149 [BE] feat(#147): 스터디에 속한 스터디원 조회 api
  backend/src/main/java/com/example/backend/domain/define/study/member/repository/StudyMemberRepositoryCustom.java
  backend/src/main/java/com/example/backend/domain/define/study/member/repository/StudyMemberRepositoryImpl.java
  backend/src/main/java/com/example/backend/study/api/controller/member/StudyMemberController.java
  backend/src/main/java/com/example/backend/study/api/controller/member/response/StudyMembersResponse.java
  backend/src/main/java/com/example/backend/study/api/service/member/StudyMemberService.java
  backend/src/test/java/com/example/backend/auth/config/fixture/UserFixture.java
  backend/src/test/java/com/example/backend/domain/define/study/member/StudyMemberFixture.java
  backend/src/test/java/com/example/backend/study/api/controller/member/StudyMemberControllerTest.java
  backend/src/test/java/com/example/backend/study/api/service/member/StudyMemberServiceTest.java
Labels: feat, 이정우 진행중🔥

#154 [BE] refactor(#153): swagger 미적용 수정
  backend/src/main/java/com/example/backend/auth/api/controller/auth/AuthController.java
  backend/src/test/java/com/example/backend/auth/api/controller/auth/AuthControllerTest.java
Labels: refactor, 이정우 진행중🔥
