Repository DKU-Dgaja/gitudy, pull requests merged in 2024-07, with the labels that each got.

#373 [AN] feat(#359): 앱 실행 시 token 유효하면 로그인 생략하는 기능 구현
  android/gitudy/presentation/src/main/java/com/takseha/presentation/adapter/FeedRVAdapter.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/SplashActivity.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/viewmodel/auth/SplashViewModel.kt
Labels: feat, 탁세하 진행중🔥

#375 [BE] refactor(#372): 스터디 리스트 조회 dto 리팩토링
  backend/src/main/java/com/example/backend/study/api/controller/info/response/StudyInfoListAndCursorIdxResponse.java
  backend/src/main/java/com/example/backend/study/api/controller/info/response/StudyInfoListWithMemberResponse.java
  backend/src/main/java/com/example/backend/study/api/service/info/StudyInfoService.java
  backend/src/test/java/com/example/backend/domain/define/study/info/StudyInfoFixture.java
  backend/src/test/java/com/example/backend/study/api/service/info/StudyInfoServiceTest.java
Labels: refactor, 구영민 진행중🔥

#376 [BE] refactor(#371): 스터디 기본 컨벤션 고정
  backend/src/main/java/com/example/backend/domain/define/study/convention/repository/StudyConventionRepository.java
  backend/src/main/java/com/example/backend/study/api/controller/comment/commit/CommitCommentController.java
  backend/src/main/java/com/example/backend/study/api/controller/commit/StudyCommitController.java
  backend/src/main/java/com/example/backend/study/api/service/commit/StudyCommitService.java
  backend/src/main/java/com/example/backend/study/api/service/convention/StudyConventionService.java
  backend/src/main/java/com/example/backend/study/api/service/info/StudyInfoService.java
  backend/src/test/java/com/example/backend/domain/define/study/convention/StudyConventionFixture.java
  backend/src/test/java/com/example/backend/domain/define/study/convention/repository/StudyConventionRepositoryTest.java
  backend/src/test/java/com/example/backend/study/api/service/commit/CommitFetchPerformanceTest.java
  backend/src/test/java/com/example/backend/study/api/service/commit/CommitFetchServiceTest.java
  backend/src/test/java/com/example/backend/study/api/service/commit/StudyCommitServiceTest.java
  backend/src/test/java/com/example/backend/study/api/service/info/StudyInfoServiceTest.java
Labels: refactor, 이주성 진행중🔥

#379 [BE] feat(#378): 커밋 패치 로직 수정
  backend/src/main/java/com/example/backend/study/api/controller/commit/StudyCommitController.java
  backend/src/main/java/com/example/backend/study/api/service/todo/StudyTodoService.java
  backend/src/test/java/com/example/backend/auth/api/service/jwt/JwtServiceTest.java
Labels: fix, 이주성 진행중🔥

#383 [AN] feat(#377): 토큰 만료 시 재발급 기능 구현
  android/gitudy/app/build.gradle.kts
  android/gitudy/app/src/main/java/com/takseha/gitudy/GitudyApplication.kt
  android/gitudy/data/build.gradle.kts
  android/gitudy/data/src/main/java/com/takseha/data/TokenInterceptor.kt
  android/gitudy/data/src/main/java/com/takseha/data/TokenManager.kt
  android/gitudy/data/src/main/java/com/takseha/data/api/gitudy/RetrofitInstance.kt
  android/gitudy/data/src/main/java/com/takseha/data/api/gitudy/auth/GitudyAuthApi.kt
  android/gitudy/data/src/main/java/com/takseha/data/api/gitudy/member/GitudyMemberApi.kt
  android/gitudy/data/src/main/java/com/takseha/data/api/gitudy/study/GitudyStudyApi.kt
  android/gitudy/data/src/main/java/com/takseha/data/dto/auth/register/ReissueResponse.kt
  android/gitudy/data/src/main/java/com/takseha/data/repository/auth/GitudyAuthRepository.kt
  android/gitudy/data/src/main/java/com/takseha/data/repository/member/GitudyMemberRepository.kt
  android/gitudy/data/src/main/java/com/takseha/data/repository/study/GitudyStudyRepository.kt
  android/gitudy/data/src/main/java/com/takseha/data/sharedPreferences/SP.kt
  android/gitudy/data/src/main/java/com/takseha/data/sharedPreferences/SPKey.kt
  android/gitudy/presentation/build.gradle.kts
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/auth/InputIdFragment.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/auth/InputNicknameFragment.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/auth/RegisterCompleteFragment.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/feed/StudyApplyActivity.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/viewmodel/auth/LoginWebViewViewModel.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/viewmodel/auth/RegisterViewModel.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/viewmodel/auth/SplashViewModel.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/viewmodel/feed/FeedHomeViewModel.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/viewmodel/feed/MakeStudyViewModel.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/viewmodel/feed/StudyApplyViewModel.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/viewmodel/home/MainHomeViewModel.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/viewmodel/mystudy/AddTodoViewModel.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/viewmodel/mystudy/CommitConventionViewModel.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/viewmodel/mystudy/MyStudyMainViewModel.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/viewmodel/mystudy/TodoViewModel.kt
  android/gitudy/settings.gradle.kts
Labels: feat, 탁세하 진행중🔥

#390 [ALL] Chore: README.md 수정
  README.md
Labels: chore, 탁세하 진행중🔥

#391 [ALL] Chore: README.md 수정
  README.md
Labels: chore, 탁세하 진행중🔥

#389 feat(#388): 깃허브 웹훅 저장 로직 구현
  webhooks/.gitignore
  webhooks/build.gradle.kts
  webhooks/gradle/wrapper/gradle-wrapper.jar
  webhooks/gradle/wrapper/gradle-wrapper.properties
  webhooks/gradlew
  webhooks/gradlew.bat
  webhooks/settings.gradle.kts
  webhooks/src/main/kotlin/site/gitudy/webhooks/WebhooksApplication.kt
  webhooks/src/main/kotlin/site/gitudy/webhooks/common/error/GlobalExceptionHandler.kt
  webhooks/src/main/kotlin/site/gitudy/webhooks/common/filter/RequestFilter.kt
  webhooks/src/main/kotlin/site/gitudy/webhooks/domain/webhook/WebhookController.kt
  webhooks/src/main/kotlin/site/gitudy/webhooks/domain/webhook/WebhookRepository.kt
  webhooks/src/main/kotlin/site/gitudy/webhooks/domain/webhook/WebhookService.kt
  webhooks/src/main/kotlin/site/gitudy/webhooks/domain/webhook/github/GithubPushEvent.kt
  webhooks/src/main/kotlin/site/gitudy/webhooks/domain/webhook/github/GithubWebhook.kt
  webhooks/src/main/kotlin/site/gitudy/webhooks/utils/Logger.kt
  webhooks/src/main/kotlin/site/gitudy/webhooks/utils/RequestContext.kt
  webhooks/src/main/resources/application.yml
  webhooks/src/test/kotlin/site/gitudy/webhooks/WebhooksApplicationTests.kt
Labels: feat

#397 [BE] refactor(#385) 비활성화 스터디 추가
  backend/src/main/java/com/example/backend/domain/define/study/info/constant/StudyStatus.java
  backend/src/main/java/com/example/backend/domain/define/study/info/repository/StudyInfoRepositoryImpl.java
  backend/src/main/java/com/example/backend/study/api/controller/info/response/StudyInfoListResponse.java
  backend/src/main/java/com/example/backend/study/api/controller/info/response/StudyInfoListWithMemberResponse.java
  backend/src/test/java/com/example/backend/domain/define/study/info/StudyInfoFixture.java
  backend/src/test/java/com/example/backend/study/api/service/info/StudyInfoServiceTest.java
Labels: refactor, 구영민 진행중🔥

#399 [BE] refactor(#398): Jwt 예외 반환코드 수정
  backend/src/main/java/com/example/backend/auth/config/security/filter/JwtAuthenticationFilter.java
  backend/src/main/java/com/example/backend/common/exception/GlobalExceptionHandler.java
  backend/src/main/java/com/example/backend/common/response/JsonResult.java
  backend/src/test/java/com/example/backend/auth/api/controller/auth/AuthControllerTest.java
  backend/src/test/java/com/example/backend/common/exception/GlobalExceptionHandlerTest.java
Labels: refactor, 이정우 진행중🔥

#395 [BE] refactor(#386): authorization 형식 수정
  backend/src/main/java/com/example/backend/auth/api/controller/auth/AuthController.java
  backend/src/main/java/com/example/backend/auth/api/service/auth/AuthService.java
  backend/src/main/java/com/example/backend/auth/api/service/token/RefreshTokenService.java
  backend/src/main/java/com/example/backend/auth/config/security/filter/JwtAuthenticationFilter.java
  backend/src/main/java/com/example/backend/domain/define/refreshToken/RefreshToken.java
  backend/src/main/java/com/example/backend/domain/define/refreshToken/repository/RefreshTokenRepository.java
  backend/src/test/java/com/example/backend/MockTestConfig.java
  backend/src/test/java/com/example/backend/TestConfig.java
  backend/src/test/java/com/example/backend/auth/api/controller/auth/AuthControllerTest.java
  backend/src/test/java/com/example/backend/auth/api/service/auth/AuthServiceTest.java
  backend/src/test/java/com/example/backend/auth/api/service/token/RefreshTokenServiceTest.java
  backend/src/test/java/com/example/backend/auth/config/security/SecurityConfigTest.java
  backend/src/test/java/com/example/backend/study/api/controller/bookmark/StudyBookmarkControllerTest.java
  backend/src/test/java/com/example/backend/study/api/controller/category/info/CategoryControllerTest.java
  backend/src/test/java/com/example/backend/study/api/controller/comment/commit/CommitCommentControllerTest.java
  backend/src/test/java/com/example/backend/study/api/controller/comment/study/StudyCommentControllerTest.java
  backend/src/test/java/com/example/backend/study/api/controller/commit/StudyCommitControllerTest.java
  backend/src/test/java/com/example/backend/study/api/controller/convention/StudyConventionControllerTest.java
  backend/src/test/java/com/example/backend/study/api/controller/info/StudyInfoControllerTest.java
  backend/src/test/java/com/example/backend/study/api/controller/member/StudyMemberControllerTest.java
  backend/src/test/java/com/example/backend/study/api/controller/todo/StudyTodoControllerTest.java
  backend/src/test/java/com/example/backend/study/api/event/controller/FcmControllerTest.java
  backend/src/test/java/com/example/backend/study/api/event/controller/NoticeControllerTest.java
Labels: refactor, 이정우 진행중🔥

#411 [BE] feat(#410) GitHub access token 저장 로직 구현
  backend/src/main/java/com/example/backend/auth/api/service/auth/AuthService.java
  backend/src/main/java/com/example/backend/auth/api/service/oauth/adapter/github/GithubAdapter.java
  backend/src/main/java/com/example/backend/auth/api/service/oauth/builder/github/GithubURLBuilder.java
  backend/src/main/java/com/example/backend/auth/api/service/oauth/response/OAuthResponse.java
  backend/src/main/java/com/example/backend/domain/define/study/github/GithubApiToken.java
  backend/src/main/java/com/example/backend/domain/define/study/github/repository/GithubApiTokenRepository.java
  backend/src/test/java/com/example/backend/auth/api/service/auth/AuthServiceTest.java
  backend/src/test/java/com/example/backend/auth/api/service/oauth/builder/github/GithubURLBuilderTest.java
  backend/src/test/java/com/example/backend/auth/config/fixture/UserFixture.java
  backend/src/test/java/com/example/backend/domain/define/study/github/repository/GithubApiTokenRepositoryTest.java
Labels: feat, 구영민 진행중🔥

#409 [BE] refactor(#408): reissue 수정
  backend/src/main/java/com/example/backend/auth/api/controller/auth/AuthController.java
  backend/src/test/java/com/example/backend/auth/api/controller/auth/AuthControllerTest.java
  backend/src/test/java/com/example/backend/auth/api/service/auth/AuthServiceTest.java
  backend/src/test/java/com/example/backend/study/api/controller/bookmark/StudyBookmarkControllerTest.java
  backend/src/test/java/com/example/backend/study/api/controller/category/info/CategoryControllerTest.java
  backend/src/test/java/com/example/backend/study/api/controller/comment/commit/CommitCommentControllerTest.java
  backend/src/test/java/com/example/backend/study/api/controller/comment/study/StudyCommentControllerTest.java
  backend/src/test/java/com/example/backend/study/api/controller/commit/StudyCommitControllerTest.java
  backend/src/test/java/com/example/backend/study/api/controller/convention/StudyConventionControllerTest.java
  backend/src/test/java/com/example/backend/study/api/controller/info/StudyInfoControllerTest.java
  backend/src/test/java/com/example/backend/study/api/controller/member/StudyMemberControllerTest.java
  backend/src/test/java/com/example/backend/study/api/controller/todo/StudyTodoControllerTest.java
  backend/src/test/java/com/example/backend/study/api/event/controller/FcmControllerTest.java
  backend/src/test/java/com/example/backend/study/api/event/controller/NoticeControllerTest.java
Labels: refactor, 이정우 진행중🔥

#418 [BE] refactor(#405): 응답 객체 구조 변경
  backend/src/main/java/com/example/backend/auth/api/controller/auth/AuthController.java
  backend/src/main/java/com/example/backend/auth/config/security/filter/JwtAuthenticationFilter.java
  backend/src/main/java/com/example/backend/common/exception/ErrorResponse.java
  backend/src/main/java/com/example/backend/common/exception/GlobalExceptionHandler.java
  backend/src/main/java/com/example/backend/common/response/JsonResult.java
  backend/src/main/java/com/example/backend/domain/define/study/category/mapping/repository/StudyCategoryMappingRepository.java
  backend/src/main/java/com/example/backend/study/api/controller/bookmark/StudyBookmarkController.java
  backend/src/main/java/com/example/backend/study/api/controller/category/info/CategoryController.java
  backend/src/main/java/com/example/backend/study/api/controller/comment/commit/CommitCommentController.java
  backend/src/main/java/com/example/backend/study/api/controller/comment/study/StudyCommentController.java
  backend/src/main/java/com/example/backend/study/api/controller/commit/StudyCommitController.java
  backend/src/main/java/com/example/backend/study/api/controller/convention/StudyConventionController.java
  backend/src/main/java/com/example/backend/study/api/controller/info/StudyInfoController.java
  backend/src/main/java/com/example/backend/study/api/controller/info/response/StudyInfoListAndCursorIdxResponse.java
  backend/src/main/java/com/example/backend/study/api/controller/member/StudyMemberController.java
  backend/src/main/java/com/example/backend/study/api/controller/todo/StudyTodoController.java
  backend/src/main/java/com/example/backend/study/api/event/controller/FcmController.java
  backend/src/main/java/com/example/backend/study/api/event/controller/NoticeController.java
  backend/src/main/java/com/example/backend/study/api/scheduler/service/ScheduledCommitFetchService.java
  backend/src/main/java/com/example/backend/study/api/service/info/StudyInfoService.java
  backend/src/test/java/com/example/backend/TestConfig.java
  backend/src/test/java/com/example/backend/auth/api/controller/auth/AuthControllerTest.java
  backend/src/test/java/com/example/backend/auth/api/service/jwt/JwtServiceTest.java
  backend/src/test/java/com/example/backend/auth/api/service/oauth/OAuthServiceTest.java
  backend/src/test/java/com/example/backend/auth/api/service/oauth/adapter/github/GithubAdapterTest.java
  backend/src/test/java/com/example/backend/auth/api/service/oauth/adapter/google/GoogleAdapterTest.java
  backend/src/test/java/com/example/backend/auth/api/service/oauth/adapter/kakao/KakaoAdapterTest.java
  backend/src/test/java/com/example/backend/auth/config/fixture/UserFixture.java
  backend/src/test/java/com/example/backend/auth/config/security/SecurityConfigTest.java
  backend/src/test/java/com/example/backend/common/exception/GlobalExceptionHandlerTest.java
  backend/src/test/java/com/example/backend/common/utils/TokenUtil.java
  backend/src/test/java/com/example/backend/domain/define/fcm/listener/NotifyMemberListenerTest.java
  backend/src/test/java/com/example/backend/domain/define/study/comment/study/repository/StudyCommentRepositoryTest.java
  backend/src/test/java/com/example/backend/domain/define/study/commit/constant/LikeCountTest.java
  backend/src/test/java/com/example/backend/domain/define/study/commit/repository/StudyCommitRepositoryTest.java
  backend/src/test/java/com/example/backend/domain/define/study/convention/StudyConventionFixture.java
  backend/src/test/java/com/example/backend/domain/define/study/github/repository/GithubApiTokenRepositoryTest.java
  backend/src/test/java/com/example/backend/domain/define/study/info/StudyInfoFixture.java
  backend/src/test/java/com/example/backend/domain/define/study/todo/repository/StudyTodoRepositoryTest.java
  backend/src/test/java/com/example/backend/domain/redis/define/state/LoginStateTest.java
  backend/src/test/java/com/example/backend/study/api/controller/bookmark/StudyBookmarkControllerTest.java
  backend/src/test/java/com/example/backend/study/api/controller/category/info/CategoryControllerTest.java
  backend/src/test/java/com/example/backend/study/api/controller/comment/commit/CommitCommentControllerTest.java
  backend/src/test/java/com/example/backend/study/api/controller/comment/study/StudyCommentControllerTest.java
  backend/src/test/java/com/example/backend/study/api/controller/commit/StudyCommitControllerTest.java
  backend/src/test/java/com/example/backend/study/api/controller/convention/StudyConventionControllerTest.java
  backend/src/test/java/com/example/backend/study/api/controller/info/StudyInfoControllerTest.java
  backend/src/test/java/com/example/backend/study/api/controller/member/StudyMemberControllerTest.java
  backend/src/test/java/com/example/backend/study/api/controller/todo/StudyTodoControllerTest.java
  backend/src/test/java/com/example/backend/study/api/event/controller/FcmControllerTest.java
  backend/src/test/java/com/example/backend/study/api/event/controller/NoticeControllerTest.java
  backend/src/test/java/com/example/backend/study/api/event/service/FcmServiceTest.java
  backend/src/test/java/com/example/backend/study/api/scheduler/service/ScheduledCommitFetchServiceTest.java
  backend/src/test/java/com/example/backend/study/api/service/commit/CommitFetchPerformanceTest.java
  backend/src/test/java/com/example/backend/study/api/service/commit/CommitFetchServiceTest.java
  backend/src/test/java/com/example/backend/study/api/service/commit/StudyCommitServiceTest.java
  backend/src/test/java/com/example/backend/study/api/service/github/GithubApiServiceTest.java
  backend/src/test/java/com/example/backend/study/api/service/info/StudyInfoServiceTest.java
  backend/src/test/java/com/example/backend/study/api/service/member/StudyMemberServiceTest.java
  backend/src/test/java/com/example/backend/study/api/service/todo/StudyTodoServiceTest.java
Labels: refactor, 이주성 진행중🔥

#421 [AN] refactor(#384): 회원가입 시 닉네임/id 중복체크 및 입력 문자 제한 관련 로직 수정
  android/gitudy/app/src/main/java/com/takseha/gitudy/GitudyApplication.kt
  android/gitudy/data/src/main/java/com/takseha/data/NavigationHandler.kt
  android/gitudy/data/src/main/java/com/takseha/data/TokenInterceptor.kt
  android/gitudy/data/src/main/java/com/takseha/data/TokenManager.kt
  android/gitudy/data/src/main/java/com/takseha/data/api/gitudy/RetrofitInstance.kt
  android/gitudy/data/src/main/java/com/takseha/data/api/gitudy/auth/GitudyAuthApi.kt
  android/gitudy/data/src/main/java/com/takseha/data/dto/auth/auth/UserInfoResponse.kt
  android/gitudy/data/src/main/java/com/takseha/data/dto/auth/login/LoginPageInfo.kt
  android/gitudy/data/src/main/java/com/takseha/data/dto/auth/login/LoginResponse.kt
  android/gitudy/data/src/main/java/com/takseha/data/dto/auth/register/NickNameResponse.kt
  android/gitudy/data/src/main/java/com/takseha/data/dto/auth/register/ReissueResponse.kt
  android/gitudy/data/src/main/java/com/takseha/data/dto/feed/StudyListResponse.kt
  android/gitudy/data/src/main/java/com/takseha/data/dto/mystudy/ConventionResponse.kt
  android/gitudy/data/src/main/java/com/takseha/data/dto/mystudy/MyStudyResponse.kt
  android/gitudy/data/src/main/java/com/takseha/data/dto/mystudy/StudyMemberListResponse.kt
  android/gitudy/data/src/main/java/com/takseha/data/dto/mystudy/TodoListResponse.kt
  android/gitudy/data/src/main/java/com/takseha/data/dto/mystudy/TodoProgressResponse.kt
  android/gitudy/data/src/main/java/com/takseha/data/repository/auth/GitudyAuthRepository.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/handler/LoginNavigationHandler.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/SplashActivity.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/auth/InputIdFragment.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/auth/InputNicknameFragment.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/viewmodel/auth/LoginViewModel.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/viewmodel/auth/LoginWebViewViewModel.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/viewmodel/auth/RegisterViewModel.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/viewmodel/auth/SplashViewModel.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/viewmodel/feed/FeedHomeViewModel.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/viewmodel/feed/StudyApplyViewModel.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/viewmodel/home/MainHomeViewModel.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/viewmodel/mystudy/MyStudyMainViewModel.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/viewmodel/mystudy/TodoViewModel.kt
Labels: refactor, 탁세하 진행중🔥

#420 [BE] refactor(#419): 토큰없이 요청 시 400 bad request 에러가 뜨는 문제 해결
  backend/src/main/java/com/example/backend/auth/api/controller/TestController.java
  backend/src/main/java/com/example/backend/auth/api/controller/auth/AuthController.java
  backend/src/main/java/com/example/backend/auth/config/security/SecurityConfig.java
  backend/src/test/java/com/example/backend/auth/api/controller/auth/AuthControllerTest.java
  backend/src/test/java/com/example/backend/auth/config/fixture/UserFixture.java
  backend/src/test/java/com/example/backend/auth/config/security/SecurityConfigTest.java
Labels: refactor, 이주성 진행중🔥

#423 [BE] refactor(#422): 중복메서드 리팩토링
  backend/src/main/java/com/example/backend/auth/api/service/auth/AuthService.java
  backend/src/main/java/com/example/backend/auth/api/service/jwt/JwtService.java
  backend/src/main/java/com/example/backend/auth/api/service/state/LoginStateService.java
  backend/src/main/java/com/example/backend/auth/api/service/token/RefreshTokenService.java
  backend/src/main/java/com/example/backend/study/api/service/category/info/CategoryService.java
  backend/src/main/java/com/example/backend/study/api/service/commit/StudyCommitService.java
  backend/src/main/java/com/example/backend/study/api/service/info/StudyInfoService.java
Labels: refactor, 이정우 진행중🔥

#426 [BE] refactor(#425): 스웨거 응답 수정
  backend/src/main/java/com/example/backend/auth/api/controller/auth/AuthController.java
  backend/src/main/java/com/example/backend/study/api/controller/bookmark/StudyBookmarkController.java
  backend/src/main/java/com/example/backend/study/api/controller/category/info/CategoryController.java
  backend/src/main/java/com/example/backend/study/api/controller/comment/commit/CommitCommentController.java
  backend/src/main/java/com/example/backend/study/api/controller/commit/StudyCommitController.java
  backend/src/main/java/com/example/backend/study/api/controller/convention/StudyConventionController.java
  backend/src/main/java/com/example/backend/study/api/controller/info/StudyInfoController.java
  backend/src/main/java/com/example/backend/study/api/controller/member/StudyMemberController.java
  backend/src/main/java/com/example/backend/study/api/controller/todo/StudyTodoController.java
Labels: refactor, 이정우 진행중🔥

#428 [BE] fix: swagger error
  backend/src/main/java/com/example/backend/study/api/controller/comment/commit/CommitCommentController.java
  backend/src/main/java/com/example/backend/study/api/controller/member/StudyMemberController.java
Labels: fix, 이정우 진행중🔥

#432 [BE] refactor(#429): 시큐리티 설정 변경
  backend/src/main/java/com/example/backend/auth/config/security/SecurityConfig.java
Labels: refactor, 이주성 진행중🔥

#433 [AN] refactor(#424): 변경된 response 형식 관련 data class 수정
  android/gitudy/data/src/main/java/com/takseha/data/api/github/GithubService.kt
  android/gitudy/data/src/main/java/com/takseha/data/api/gitudy/RetrofitInstance.kt
  android/gitudy/data/src/main/java/com/takseha/data/api/gitudy/auth/GitudyAuthService.kt
  android/gitudy/data/src/main/java/com/takseha/data/api/gitudy/member/GitudyMemberService.kt
  android/gitudy/data/src/main/java/com/takseha/data/api/gitudy/study/GitudyStudyService.kt
  android/gitudy/data/src/main/java/com/takseha/data/dto/auth/auth/UserInfoResponse.kt
  android/gitudy/data/src/main/java/com/takseha/data/dto/auth/login/LoginPageInfoResponse.kt
  android/gitudy/data/src/main/java/com/takseha/data/dto/auth/login/ReissueTokenResponse.kt
  android/gitudy/data/src/main/java/com/takseha/data/dto/auth/login/RoleStatus.kt
  android/gitudy/data/src/main/java/com/takseha/data/dto/auth/login/TokenResponse.kt
  android/gitudy/data/src/main/java/com/takseha/data/dto/auth/register/GithubIdCheckResponse.kt
  android/gitudy/data/src/main/java/com/takseha/data/dto/auth/register/NickNameResponse.kt
  android/gitudy/data/src/main/java/com/takseha/data/dto/auth/register/RegisterResponse.kt
  android/gitudy/data/src/main/java/com/takseha/data/dto/auth/register/ReissueResponse.kt
  android/gitudy/data/src/main/java/com/takseha/data/dto/feed/MakeStudyRequest.kt
  android/gitudy/data/src/main/java/com/takseha/data/dto/feed/MakeStudyResponse.kt
  android/gitudy/data/src/main/java/com/takseha/data/dto/feed/StudyListResponse.kt
  android/gitudy/data/src/main/java/com/takseha/data/dto/feed/StudyPeriodStatus.kt
  android/gitudy/data/src/main/java/com/takseha/data/dto/mystudy/MakeTodoResponse.kt
  android/gitudy/data/src/main/java/com/takseha/data/dto/mystudy/MyStudyResponse.kt
  android/gitudy/data/src/main/java/com/takseha/data/dto/mystudy/RogerResponse.kt
  android/gitudy/data/src/main/java/com/takseha/data/dto/mystudy/StudyApplyStatus.kt
  android/gitudy/data/src/main/java/com/takseha/data/dto/mystudy/StudyMemberListResponse.kt
  android/gitudy/data/src/main/java/com/takseha/data/dto/mystudy/TodoListResponse.kt
  android/gitudy/data/src/main/java/com/takseha/data/dto/mystudy/TodoProgressResponse.kt
  android/gitudy/data/src/main/java/com/takseha/data/repository/auth/GithubRepository.kt
  android/gitudy/data/src/main/java/com/takseha/data/repository/auth/GitudyAuthRepository.kt
  android/gitudy/data/src/main/java/com/takseha/data/repository/member/GitudyMemberRepository.kt
  android/gitudy/data/src/main/java/com/takseha/data/repository/study/GitudyStudyRepository.kt
  android/gitudy/data/src/main/java/com/takseha/data/token/NavigationHandler.kt
  android/gitudy/data/src/main/java/com/takseha/data/token/TokenInterceptor.kt
  android/gitudy/data/src/main/java/com/takseha/data/token/TokenManager.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/adapter/FeedRVAdapter.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/handler/LoginNavigationHandler.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/SplashActivity.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/auth/LoginWebViewActivity.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/auth/SocialLoginCompleteActivity.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/feed/FeedHomeFragment.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/feed/MakeStudy1Fragment.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/feed/MakeStudy2Fragment.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/feed/MakeStudy3Fragment.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/feed/StudyApplyActivity.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/mystudy/MyStudyMainActivity.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/viewmodel/auth/LoginViewModel.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/viewmodel/auth/LoginWebViewViewModel.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/viewmodel/auth/RegisterViewModel.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/viewmodel/auth/SplashViewModel.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/viewmodel/feed/FeedHomeViewModel.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/viewmodel/feed/MakeStudyViewModel.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/viewmodel/feed/StudyApplyViewModel.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/viewmodel/home/MainHomeViewModel.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/viewmodel/mystudy/AddTodoViewModel.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/viewmodel/mystudy/MyStudyMainViewModel.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/viewmodel/mystudy/TodoViewModel.kt
Labels: refactor, 탁세하 진행중🔥

#435 [BE] feat(#431): 웹 훅 데이터를 활용한 커밋 처리 로직 구현
  backend/src/main/java/com/example/backend/auth/config/security/SecurityConfig.java
  backend/src/main/java/com/example/backend/common/exception/ExceptionMessage.java
  backend/src/main/java/com/example/backend/common/exception/webhook/WebhookException.java
  backend/src/main/java/com/example/backend/domain/define/study/commit/repository/StudyCommitRepository.java
  backend/src/main/java/com/example/backend/domain/define/study/info/repository/StudyInfoRepositoryCustom.java
  backend/src/main/java/com/example/backend/domain/define/study/info/repository/StudyInfoRepositoryImpl.java
  backend/src/main/java/com/example/backend/domain/define/study/member/repository/StudyMemberRepositoryCustom.java
  backend/src/main/java/com/example/backend/domain/define/study/member/repository/StudyMemberRepositoryImpl.java
  backend/src/main/java/com/example/backend/domain/define/study/todo/mapping/repository/StudyTodoMappingRepository.java
  backend/src/main/java/com/example/backend/domain/define/study/todo/mapping/repository/StudyTodoMappingRepositoryCustom.java
  backend/src/main/java/com/example/backend/domain/define/study/todo/mapping/repository/StudyTodoMappingRepositoryImpl.java
  backend/src/main/java/com/example/backend/domain/define/study/todo/repository/StudyTodoRepository.java
  backend/src/main/java/com/example/backend/webhook/api/controller/WebhookController.java
  backend/src/main/java/com/example/backend/webhook/api/controller/request/WebhookPayload.java
  backend/src/main/java/com/example/backend/webhook/api/service/WebhookService.java
  backend/src/test/java/com/example/backend/auth/api/service/jwt/JwtServiceTest.java
  backend/src/test/java/com/example/backend/auth/config/fixture/UserFixture.java
  backend/src/test/java/com/example/backend/domain/define/study/info/repository/StudyInfoRepositoryTest.java
  backend/src/test/java/com/example/backend/domain/define/study/member/repository/StudyMemberRepositoryTest.java
  backend/src/test/java/com/example/backend/domain/define/study/todo/StudyTodoFixture.java
  backend/src/test/java/com/example/backend/domain/define/study/todo/mapping/repository/StudyTodoMappingRepositoryTest.java
  backend/src/test/java/com/example/backend/domain/define/study/todo/repository/StudyTodoRepositoryTest.java
  backend/src/test/java/com/example/backend/study/api/service/commit/StudyCommitServiceTest.java
  backend/src/test/java/com/example/backend/webhook/api/controller/WebhookControllerTest.java
  backend/src/test/java/com/example/backend/webhook/api/service/WebhookServiceTest.java
Labels: feat, 이주성 진행중🔥

#438 [BE] feat(#437) git api를 이용한 레포지토리 생성 구현
  backend/src/main/java/com/example/backend/common/exception/ExceptionMessage.java
  backend/src/main/java/com/example/backend/study/api/service/github/GithubApiService.java
  backend/src/main/java/com/example/backend/study/api/service/info/StudyInfoService.java
  backend/src/test/java/com/example/backend/study/api/service/github/GithubApiServiceTest.java
  backend/src/test/java/com/example/backend/study/api/service/info/StudyInfoServiceTest.java
Labels: feat, 구영민 진행중🔥

#442 Be(#441) refactor 이전의 커밋 로직 및 오래 걸리는 테스트 로직 제거
  backend/build.gradle
  backend/src/main/java/com/example/backend/auth/api/service/jwt/JwtService.java
  backend/src/main/java/com/example/backend/domain/define/study/todo/mapping/repository/StudyTodoMappingRepositoryCustom.java
  backend/src/main/java/com/example/backend/domain/define/study/todo/mapping/repository/StudyTodoMappingRepositoryImpl.java
  backend/src/main/java/com/example/backend/study/api/controller/member/StudyMemberController.java
  backend/src/main/java/com/example/backend/study/api/controller/todo/StudyTodoController.java
  backend/src/main/java/com/example/backend/study/api/scheduler/config/AsyncConfig.java
  backend/src/main/java/com/example/backend/study/api/scheduler/config/SchedulingConfig.java
  backend/src/main/java/com/example/backend/study/api/scheduler/service/ScheduledCommitFetchService.java
  backend/src/main/java/com/example/backend/study/api/service/commit/StudyCommitService.java
  backend/src/main/java/com/example/backend/study/api/service/github/GithubApiService.java
  backend/src/main/java/com/example/backend/study/api/service/todo/StudyTodoService.java
  backend/src/test/java/com/example/backend/MockTestConfig.java
  backend/src/test/java/com/example/backend/TestConfig.java
  backend/src/test/java/com/example/backend/study/api/controller/todo/StudyTodoControllerTest.java
  backend/src/test/java/com/example/backend/study/api/scheduler/service/ScheduledCommitFetchServiceTest.java
  backend/src/test/java/com/example/backend/study/api/service/commit/CommitFetchPerformanceTest.java
  backend/src/test/java/com/example/backend/study/api/service/commit/CommitFetchServiceTest.java
  backend/src/test/java/com/example/backend/study/api/service/commit/StudyCommitServiceTest.java
  backend/src/test/java/com/example/backend/study/api/service/github/GithubApiServiceTest.java
  backend/src/test/java/com/example/backend/study/api/service/todo/StudyTodoServiceTest.java
Labels: refactor, 이주성 진행중🔥

#454 [BE] refactor(#453): 스터디 생성 날짜 추가
  backend/src/main/java/com/example/backend/study/api/controller/todo/response/StudyTodoResponse.java
  backend/src/main/java/com/example/backend/study/api/controller/todo/response/StudyTodoWithCommitsResponse.java
Labels: refactor, 구영민 진행중🔥

#466 [BE] refactor(#465): DTO 변경
  backend/src/main/java/com/example/backend/domain/define/study/comment/study/repository/StudyCommentRepositoryImpl.java
  backend/src/main/java/com/example/backend/study/api/controller/comment/study/response/StudyCommentResponse.java
  backend/src/main/java/com/example/backend/study/api/service/comment/study/response/UserInfoForStudyCommentResponse.java
  backend/src/test/java/com/example/backend/domain/define/study/comment/StudyCommentFixture.java
  backend/src/test/java/com/example/backend/domain/define/study/comment/study/repository/StudyCommentRepositoryTest.java
Labels: refactor, 구영민 진행중🔥

#461 [BE] feat(#459) collaborator 초대 및 수락 자동화 구현
  backend/src/main/java/com/example/backend/common/exception/ExceptionMessage.java
  backend/src/main/java/com/example/backend/study/api/service/github/GithubApiService.java
  backend/src/main/java/com/example/backend/study/api/service/member/StudyMemberService.java
  backend/src/test/java/com/example/backend/domain/define/study/info/StudyInfoFixture.java
  backend/src/test/java/com/example/backend/study/api/service/github/GithubApiServiceTest.java
  backend/src/test/java/com/example/backend/study/api/service/member/StudyMemberServiceTest.java
Labels: feat, 구영민 진행중🔥

#467 [BE] refactor(#452): FcmToken 저장필드 생성
  backend/src/main/java/com/example/backend/auth/api/controller/auth/request/AuthRegisterRequest.java
  backend/src/main/java/com/example/backend/auth/api/service/auth/AuthService.java
  backend/src/main/java/com/example/backend/auth/api/service/auth/request/AuthServiceRegisterRequest.java
  backend/src/test/java/com/example/backend/auth/api/controller/auth/AuthControllerTest.java
  backend/src/test/java/com/example/backend/auth/api/service/auth/AuthServiceTest.java
Labels: refactor, 이정우 진행중🔥

#455 [BE] feat(#443): 유저 랭킹 시스템
  backend/src/main/java/com/example/backend/auth/api/controller/auth/AuthController.java
  backend/src/main/java/com/example/backend/auth/api/controller/auth/response/UserInfoAndRankingResponse.java
  backend/src/main/java/com/example/backend/auth/api/service/auth/AuthService.java
  backend/src/main/java/com/example/backend/auth/api/service/rank/RankingService.java
  backend/src/main/java/com/example/backend/auth/api/service/rank/response/UserRankingResponse.java
  backend/src/main/java/com/example/backend/domain/config/RedisConfig.java
  backend/src/main/java/com/example/backend/domain/define/rank/UserRanking.java
  backend/src/test/java/com/example/backend/auth/api/controller/auth/AuthControllerTest.java
  backend/src/test/java/com/example/backend/auth/api/service/auth/AuthServiceTest.java
  backend/src/test/java/com/example/backend/auth/api/service/rank/RankingServiceTest.java
  backend/src/test/java/com/example/backend/auth/config/fixture/UserFixture.java
Labels: feat, 이정우 진행중🔥

#462 [BE] feat(#460): GitHub api token 재발급 로직
  backend/src/main/java/com/example/backend/auth/api/service/auth/AuthService.java
  backend/src/main/java/com/example/backend/auth/config/security/SecurityConfig.java
  backend/src/main/java/com/example/backend/common/exception/ExceptionMessage.java
  backend/src/main/java/com/example/backend/external/clients/github/GithubApiTokenClient.java
  backend/src/main/java/com/example/backend/study/api/service/github/GithubApiService.java
  backend/src/main/java/com/example/backend/study/api/service/member/StudyMemberService.java
  backend/src/test/java/com/example/backend/auth/api/controller/auth/AuthControllerTest.java
  backend/src/test/java/com/example/backend/study/api/service/github/GithubApiServiceTest.java
  backend/src/test/java/com/example/backend/study/api/service/member/StudyMemberServiceTest.java
Labels: feat, 이주성 진행중🔥

#470 [BE] fix(#468): merge conflict
  backend/src/main/java/com/example/backend/auth/api/service/auth/AuthService.java
  backend/src/main/java/com/example/backend/study/api/service/github/GithubApiService.java
  backend/src/main/java/com/example/backend/study/api/service/github/GithubApiTokenService.java
  backend/src/main/java/com/example/backend/study/api/service/member/StudyMemberService.java
  backend/src/test/java/com/example/backend/auth/api/service/jwt/JwtServiceTest.java
  backend/src/test/java/com/example/backend/domain/define/study/github/repository/GithubApiTokenRepositoryTest.java
  backend/src/test/java/com/example/backend/domain/define/study/todo/mapping/repository/StudyTodoMappingRepositoryTest.java
  backend/src/test/java/com/example/backend/study/api/controller/todo/StudyTodoControllerTest.java
  backend/src/test/java/com/example/backend/study/api/service/commit/StudyCommitServiceTest.java
  backend/src/test/java/com/example/backend/study/api/service/github/GithubApiTokenServiceTest.java
  backend/src/test/java/com/example/backend/study/api/service/todo/StudyTodoServiceTest.java
  backend/src/test/java/com/example/backend/webhook/api/service/WebhookServiceTest.java
Labels: fix, 이주성 진행중🔥

#471 [BE] feat(#463): 스터디 레포지토리 이름 검증 api 구현
  backend/src/main/java/com/example/backend/common/exception/ExceptionMessage.java
  backend/src/main/java/com/example/backend/common/validation/RepoNameValidator.java
  backend/src/main/java/com/example/backend/common/validation/ValidRepoName.java
  backend/src/main/java/com/example/backend/study/api/controller/info/StudyInfoController.java
  backend/src/main/java/com/example/backend/study/api/controller/info/request/RepoNameCheckRequest.java
  backend/src/main/java/com/example/backend/study/api/controller/info/request/StudyInfoRegisterRequest.java
  backend/src/main/java/com/example/backend/study/api/service/github/GithubApiService.java
  backend/src/main/java/com/example/backend/study/api/service/info/StudyInfoService.java
  backend/src/test/java/com/example/backend/auth/api/service/auth/AuthServiceTest.java
  backend/src/test/java/com/example/backend/domain/define/study/info/StudyInfoFixture.java
  backend/src/test/java/com/example/backend/study/api/controller/info/StudyInfoControllerTest.java
  backend/src/test/java/com/example/backend/study/api/service/github/GithubApiServiceTest.java
  backend/src/test/java/com/example/backend/study/api/service/info/StudyInfoServiceTest.java
Labels: feat, 이주성 진행중🔥

#475 [BE] refactor(#474): 재발급 url 시큐리티 설정 수정
  backend/src/main/java/com/example/backend/auth/config/security/SecurityConfig.java
  backend/src/main/java/com/example/backend/study/api/controller/info/StudyInfoController.java
  backend/src/main/java/com/example/backend/study/api/controller/info/request/StudyInfoRegisterRequest.java
  backend/src/test/java/com/example/backend/study/api/controller/info/StudyInfoControllerTest.java
  backend/src/test/java/com/example/backend/study/api/service/info/StudyInfoServiceTest.java
Labels: refactor
