Repository DKU-Dgaja/gitudy, pull requests merged in 2024-04, with the labels that each got.

#262 refactor(#260): request에서 uesrId를 받지 않고 jwt 토큰으로만 사용자의 정보 확인하도록 변경
  backend/src/main/java/com/example/backend/auth/api/controller/auth/AuthController.java
  backend/src/main/java/com/example/backend/domain/define/study/info/StudyInfo.java
  backend/src/main/java/com/example/backend/study/api/controller/bookmark/StudyBookmarkController.java
  backend/src/main/java/com/example/backend/study/api/controller/category/info/CategoryController.java
  backend/src/main/java/com/example/backend/study/api/controller/category/info/request/CategoryRegisterRequest.java
  backend/src/main/java/com/example/backend/study/api/controller/category/info/request/CategoryUpdateRequest.java
  backend/src/main/java/com/example/backend/study/api/controller/comment/study/StudyCommentController.java
  backend/src/main/java/com/example/backend/study/api/controller/comment/study/request/StudyCommentRegisterRequest.java
  backend/src/main/java/com/example/backend/study/api/controller/comment/study/request/StudyCommentUpdateRequest.java
  backend/src/main/java/com/example/backend/study/api/controller/commit/StudyCommitController.java
  backend/src/main/java/com/example/backend/study/api/controller/info/StudyInfoController.java
  backend/src/main/java/com/example/backend/study/api/controller/info/request/StudyInfoRegisterRequest.java
  backend/src/main/java/com/example/backend/study/api/controller/info/request/StudyInfoUpdateRequest.java
  backend/src/main/java/com/example/backend/study/api/controller/member/StudyMemberController.java
  backend/src/main/java/com/example/backend/study/api/service/comment/study/StudyCommentService.java
  backend/src/main/java/com/example/backend/study/api/service/info/StudyInfoService.java
  backend/src/test/java/com/example/backend/auth/api/controller/auth/AuthControllerTest.java
  backend/src/test/java/com/example/backend/domain/define/study/comment/StudyCommentFixture.java
  backend/src/test/java/com/example/backend/domain/define/study/info/StudyInfoFixture.java
  backend/src/test/java/com/example/backend/study/api/controller/bookmark/StudyBookmarkControllerTest.java
  backend/src/test/java/com/example/backend/study/api/controller/category/info/CategoryControllerTest.java
  backend/src/test/java/com/example/backend/study/api/controller/comment/study/StudyCommentControllerTest.java
  backend/src/test/java/com/example/backend/study/api/controller/commit/StudyCommitControllerTest.java
  backend/src/test/java/com/example/backend/study/api/controller/info/StudyInfoControllerTest.java
  backend/src/test/java/com/example/backend/study/api/controller/member/StudyMemberControllerTest.java
  backend/src/test/java/com/example/backend/study/api/service/category/info/CategoryServiceTest.java
  backend/src/test/java/com/example/backend/study/api/service/comment/study/StudyCommentServiceTest.java
  backend/src/test/java/com/example/backend/study/api/service/info/StudyInfoServiceTest.java
Labels: refactor, 이주성 진행중🔥

#256 [BE] feat(#255): 스터디 가입신청 알림 api
  backend/src/main/java/com/example/backend/BackendApplication.java
  backend/src/main/java/com/example/backend/common/exception/ExceptionMessage.java
  backend/src/main/java/com/example/backend/common/exception/event/EventException.java
  backend/src/main/java/com/example/backend/domain/define/study/info/listener/StudyEventListener.java
  backend/src/main/java/com/example/backend/domain/define/study/info/listener/event/ApplyMemberEvent.java
  backend/src/main/java/com/example/backend/domain/define/study/member/listener/TestEventListener.java
  backend/src/main/java/com/example/backend/study/api/controller/member/StudyMemberController.java
  backend/src/main/java/com/example/backend/study/api/controller/member/request/ApplyMemberMessageRequest.java
  backend/src/main/java/com/example/backend/study/api/event/FcmSingleTokenRequest.java
  backend/src/main/java/com/example/backend/study/api/event/FcmTitleMessageRequest.java
  backend/src/main/java/com/example/backend/study/api/service/member/StudyMemberService.java
  backend/src/test/java/com/example/backend/auth/TestConfig.java
  backend/src/test/java/com/example/backend/auth/config/fixture/UserFixture.java
  backend/src/test/java/com/example/backend/domain/define/event/FcmFixture.java
  backend/src/test/java/com/example/backend/domain/define/study/info/StudyEventFixture.java
  backend/src/test/java/com/example/backend/domain/define/study/info/listener/StudyEventListenerTest.java
  backend/src/test/java/com/example/backend/domain/define/study/member/StudyMemberFixture.java
  backend/src/test/java/com/example/backend/study/api/controller/member/StudyMemberControllerTest.java
  backend/src/test/java/com/example/backend/study/api/service/member/StudyMemberServiceTest.java
Labels: feat, 이정우 진행중🔥

#266 [AN] feat(#263): 회원가입 시 푸시 알람 여부 확인 기능 구현
  android/gitudy/build.gradle.kts
  android/gitudy/common/src/main/java/com/takseha/common/model/SPKey.kt
  android/gitudy/data/src/main/java/com/takseha/data/api/gitudy/GitudyApi.kt
  android/gitudy/data/src/main/java/com/takseha/data/dto/auth/register/NickNameResponse.kt
  android/gitudy/data/src/main/java/com/takseha/data/dto/auth/register/RegisterRequest.kt
  android/gitudy/data/src/main/java/com/takseha/data/dto/feed/MakeStudyRequest.kt
  android/gitudy/data/src/main/java/com/takseha/data/repository/GitudyRepository.kt
  android/gitudy/presentation/build.gradle.kts
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/auth/InputIdFragment.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/auth/InputNicknameFragment.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/auth/PopupAgreementFragment.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/auth/RegisterCompleteFragment.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/home/MainHomeActivity.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/home/MainHomeFragment.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/profile/ProfileHomeFragment.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/viewmodel/auth/PopupAgreementViewModel.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/viewmodel/auth/RegisterViewModel.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/viewmodel/home/MainHomeViewModel.kt
  android/gitudy/presentation/src/main/res/layout/fragment_input_id.xml
  android/gitudy/presentation/src/main/res/layout/fragment_input_nickname.xml
  android/gitudy/presentation/src/main/res/layout/fragment_popup_agreement.xml
  android/gitudy/presentation/src/main/res/navigation/register_nav.xml
  android/gitudy/presentation/src/main/res/values/strings.xml
Labels: feat, 탁세하 진행중🔥

#265 [BE] refactor(#264): StudyMember 스터디장에게 한마디 필드 생성
  backend/src/main/java/com/example/backend/domain/define/study/member/StudyMember.java
  backend/src/main/java/com/example/backend/domain/define/study/member/repository/StudyMemberRepositoryImpl.java
  backend/src/main/java/com/example/backend/study/api/controller/member/response/StudyMemberApplyResponse.java
  backend/src/main/java/com/example/backend/study/api/service/member/StudyMemberService.java
  backend/src/test/java/com/example/backend/domain/define/study/info/listener/StudyEventListenerTest.java
  backend/src/test/java/com/example/backend/domain/define/study/member/StudyMemberFixture.java
  backend/src/test/java/com/example/backend/study/api/service/member/StudyMemberServiceTest.java
Labels: refactor, 이정우 진행중🔥

#257 [BE] feat(#254) 스터디 강퇴 알림 api 구현
  backend/src/main/java/com/example/backend/BackendApplication.java
  backend/src/main/java/com/example/backend/auth/api/service/auth/AuthService.java
  backend/src/main/java/com/example/backend/common/exception/ExceptionMessage.java
  backend/src/main/java/com/example/backend/common/exception/event/EventException.java
  backend/src/main/java/com/example/backend/domain/define/study/member/listener/MemberEventListener.java
  backend/src/main/java/com/example/backend/domain/define/study/member/listener/event/ResignMemberEvent.java
  backend/src/main/java/com/example/backend/study/api/service/member/StudyMemberService.java
  backend/src/test/java/com/example/backend/auth/TestConfig.java
  backend/src/test/java/com/example/backend/auth/config/fixture/UserFixture.java
  backend/src/test/java/com/example/backend/domain/define/study/member/MemberEventFixture.java
  backend/src/test/java/com/example/backend/domain/define/study/member/listener/MemberEventListenerTest.java
  backend/src/test/java/com/example/backend/study/api/service/member/StudyMemberServiceTest.java
Labels: feat, 구영민 진행중🔥

#269 [BE] feat(#268): 가입 승인/거부 알림 전송 api
  backend/src/main/java/com/example/backend/domain/define/fcm/FcmToken.java
  backend/src/main/java/com/example/backend/domain/define/fcm/listener/ApplyApproveRefuseMemberListener.java
  backend/src/main/java/com/example/backend/domain/define/fcm/listener/ApplyMemberListener.java
  backend/src/main/java/com/example/backend/domain/define/fcm/listener/ResignMemberListener.java
  backend/src/main/java/com/example/backend/domain/define/fcm/repository/FcmTokenRepository.java
  backend/src/main/java/com/example/backend/domain/define/study/info/event/ApplyApproveRefuseMemberEvent.java
  backend/src/main/java/com/example/backend/domain/define/study/info/event/ApplyMemberEvent.java
  backend/src/main/java/com/example/backend/domain/define/study/member/event/ResignMemberEvent.java
  backend/src/main/java/com/example/backend/study/api/event/service/FcmService.java
  backend/src/main/java/com/example/backend/study/api/service/category/info/CategoryService.java
  backend/src/main/java/com/example/backend/study/api/service/comment/commit/CommitCommentService.java
  backend/src/main/java/com/example/backend/study/api/service/comment/study/StudyCommentService.java
  backend/src/main/java/com/example/backend/study/api/service/commit/StudyCommitService.java
  backend/src/main/java/com/example/backend/study/api/service/convention/StudyConventionService.java
  backend/src/main/java/com/example/backend/study/api/service/info/StudyInfoService.java
  backend/src/main/java/com/example/backend/study/api/service/member/StudyMemberService.java
  backend/src/main/java/com/example/backend/study/api/service/todo/StudyTodoService.java
  backend/src/main/java/com/example/backend/study/api/service/user/UserService.java
  backend/src/test/java/com/example/backend/domain/define/event/FcmFixture.java
  backend/src/test/java/com/example/backend/domain/define/fcm/listener/ApplyApproveRefuseMemberListenerTest.java
  backend/src/test/java/com/example/backend/domain/define/fcm/listener/ApplyMemberListenerTest.java
  backend/src/test/java/com/example/backend/domain/define/fcm/listener/ResignMemberListenerTest.java
  backend/src/test/java/com/example/backend/domain/define/fcm/repository/FcmTokenRepositoryTest.java
  backend/src/test/java/com/example/backend/domain/define/study/info/StudyEventFixture.java
  backend/src/test/java/com/example/backend/domain/define/study/member/MemberEventFixture.java
  backend/src/test/java/com/example/backend/study/api/event/service/FcmServiceTest.java
  backend/src/test/java/com/example/backend/study/api/service/member/StudyMemberServiceTest.java
Labels: refactor, feat, 이정우 진행중🔥

#271 [BE] feat(#270): 스터디 탈퇴 유저가 생겼을 때 스터디장에게 알림
  backend/src/main/java/com/example/backend/domain/define/fcm/listener/WithdrawalMemberListener.java
  backend/src/main/java/com/example/backend/domain/define/study/member/event/WithdrawalMemberEvent.java
  backend/src/main/java/com/example/backend/study/api/controller/member/StudyMemberController.java
  backend/src/main/java/com/example/backend/study/api/service/member/StudyMemberService.java
  backend/src/test/java/com/example/backend/domain/define/fcm/listener/WithdrawalMemberListenerTest.java
  backend/src/test/java/com/example/backend/study/api/service/member/StudyMemberServiceTest.java
Labels: feat, 구영민 진행중🔥

#273 [BE] feat(#272): 특정 스터디원에게 알림 전송(fcm) api
  backend/src/main/java/com/example/backend/domain/define/fcm/listener/NotifyMemberListener.java
  backend/src/main/java/com/example/backend/domain/define/study/member/event/NotifyMemberEvent.java
  backend/src/main/java/com/example/backend/study/api/controller/member/StudyMemberController.java
  backend/src/main/java/com/example/backend/study/api/controller/member/request/MessageRequest.java
  backend/src/main/java/com/example/backend/study/api/service/member/StudyMemberService.java
  backend/src/test/java/com/example/backend/domain/define/fcm/listener/NotifyMemberListenerTest.java
  backend/src/test/java/com/example/backend/domain/define/study/member/MemberEventFixture.java
  backend/src/test/java/com/example/backend/domain/define/study/member/StudyMemberFixture.java
  backend/src/test/java/com/example/backend/study/api/controller/member/StudyMemberControllerTest.java
  backend/src/test/java/com/example/backend/study/api/service/member/StudyMemberServiceTest.java
Labels: refactor, feat, 이정우 진행중🔥

#279 [ALL] refactor(#278): readme.md 파일 수정
  README.md
Labels: refactor, 탁세하 진행중🔥

#280 [ALL] refactor(#278): readme 수정
  README.md
Labels: refactor, 탁세하 진행중🔥

#276 [BE] feat(#275): Todo 등록 멤버 알림전송(fcm) api
  backend/src/main/java/com/example/backend/domain/define/fcm/listener/TodoRegisterMemberListener.java
  backend/src/main/java/com/example/backend/domain/define/study/todo/event/TodoRegisterMemberEvent.java
  backend/src/main/java/com/example/backend/study/api/event/service/FcmService.java
  backend/src/main/java/com/example/backend/study/api/service/todo/StudyTodoService.java
  backend/src/main/java/com/example/backend/study/api/service/user/UserService.java
  backend/src/test/java/com/example/backend/auth/config/fixture/UserFixture.java
  backend/src/test/java/com/example/backend/domain/define/event/FcmFixture.java
  backend/src/test/java/com/example/backend/domain/define/fcm/listener/TodoRegisterMemberListenerTest.java
  backend/src/test/java/com/example/backend/domain/define/study/todo/TodoEventFixture.java
  backend/src/test/java/com/example/backend/study/api/service/member/StudyMemberServiceTest.java
  backend/src/test/java/com/example/backend/study/api/service/todo/StudyTodoServiceTest.java
Labels: feat, 이정우 진행중🔥

#282 [BE] feat(#274): Todo를 수정 했을 때 알림 구현
  backend/src/main/java/com/example/backend/domain/define/fcm/listener/TodoUpdateMemberListener.java
  backend/src/main/java/com/example/backend/domain/define/study/todo/event/TodoUpdateMemberEvent.java
  backend/src/main/java/com/example/backend/study/api/controller/todo/StudyTodoController.java
  backend/src/main/java/com/example/backend/study/api/service/todo/StudyTodoService.java
  backend/src/test/java/com/example/backend/domain/define/fcm/listener/TodoUpdateMemberListenerTest.java
  backend/src/test/java/com/example/backend/domain/define/study/todo/TodoEventFixture.java
  backend/src/test/java/com/example/backend/study/api/controller/todo/StudyTodoControllerTest.java
  backend/src/test/java/com/example/backend/study/api/service/todo/StudyTodoServiceTest.java
Labels: feat, 구영민 진행중🔥
