Repository DKU-Dgaja/gitudy, pull requests merged in 2024-05, with the labels that each got.

#284 [BE] fix(#283): 테스트 에러해결
  backend/src/main/java/com/example/backend/study/api/controller/comment/commit/CommitCommentController.java
  backend/src/main/java/com/example/backend/study/api/controller/comment/study/StudyCommentController.java
  backend/src/main/java/com/example/backend/study/api/controller/info/StudyInfoController.java
  backend/src/main/java/com/example/backend/study/api/event/FcmMultiTokenRequest.java
  backend/src/main/java/com/example/backend/study/api/event/FcmSingleTokenRequest.java
  backend/src/main/java/com/example/backend/study/api/event/TestEvent.java
  backend/src/main/java/com/example/backend/study/api/event/controller/FcmController.java
  backend/src/main/java/com/example/backend/study/api/event/service/FcmService.java
  backend/src/main/java/com/example/backend/study/api/service/bookmark/StudyBookmarkService.java
  backend/src/main/java/com/example/backend/study/api/service/category/info/CategoryService.java
  backend/src/main/java/com/example/backend/study/api/service/convention/StudyConventionService.java
  backend/src/main/java/com/example/backend/study/api/service/info/StudyInfoService.java
  backend/src/main/java/com/example/backend/study/api/service/member/StudyMemberService.java
  backend/src/main/java/com/example/backend/study/api/service/todo/StudyTodoService.java
  backend/src/test/java/com/example/backend/auth/TestConfig.java
  backend/src/test/java/com/example/backend/domain/define/user/repository/UserRepositoryTest.java
  backend/src/test/java/com/example/backend/study/api/controller/info/StudyInfoControllerTest.java
  backend/src/test/java/com/example/backend/study/api/controller/todo/StudyTodoControllerTest.java
  backend/src/test/java/com/example/backend/study/api/service/comment/commit/CommitCommentServiceTest.java
  backend/src/test/java/com/example/backend/study/api/service/convention/StudyConventionServiceTest.java
  backend/src/test/java/com/example/backend/study/api/service/member/StudyMemberServiceTest.java
  backend/src/test/java/com/example/backend/study/api/service/todo/StudyTodoServiceTest.java
Labels: fix

#291 [BE] fix: LocalDateTime 포맷터 설정
  backend/src/main/java/com/example/backend/auth/config/ProjectConfig.java
Labels: fix, 구영민 진행중🔥

#293 [BE] refactor(#290): LocalDateTime사용
  backend/src/main/java/com/example/backend/auth/config/ProjectConfig.java
Labels: fix, 구영민 진행중🔥

#294 An feat(#267) 전체스터디 목록 생성 기능 구현
  android/gitudy/data/src/main/java/com/takseha/data/api/gitudy/auth/GitudyAuthApi.kt
  android/gitudy/data/src/main/java/com/takseha/data/api/gitudy/study/GitudyStudyApi.kt
  android/gitudy/data/src/main/java/com/takseha/data/dto/mystudy/StudyListResponse.kt
  android/gitudy/data/src/main/java/com/takseha/data/repository/auth/GithubRepository.kt
  android/gitudy/data/src/main/java/com/takseha/data/repository/auth/GitudyAuthRepository.kt
  android/gitudy/data/src/main/java/com/takseha/data/repository/study/GitudyStudyRepository.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/adapter/FeedRVAdapter.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/adapter/RVAdapter.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/feed/FeedHomeFragment.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/viewholder/MyStudyListViewHolder.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/viewmodel/auth/LoginViewModel.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/viewmodel/auth/LoginWebViewViewModel.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/viewmodel/auth/RegisterViewModel.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/viewmodel/feed/FeedHomeViewModel.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/viewmodel/feed/MakeStudyViewModel.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/viewmodel/home/MainHomeViewModel.kt
  android/gitudy/presentation/src/main/res/drawable/ic_check_blue_sq.png
  android/gitudy/presentation/src/main/res/drawable/ic_check_empty_sq.png
  android/gitudy/presentation/src/main/res/drawable/ic_feed_save_white.png
  android/gitudy/presentation/src/main/res/drawable/ic_people.png
  android/gitudy/presentation/src/main/res/drawable/ic_sort.png
  android/gitudy/presentation/src/main/res/drawable/selector_ic_check_sq_checked.xml
  android/gitudy/presentation/src/main/res/layout/fragment_feed_home.xml
  android/gitudy/presentation/src/main/res/layout/fragment_make_study2.xml
  android/gitudy/presentation/src/main/res/layout/item_feed.xml
  android/gitudy/presentation/src/main/res/values/strings.xml
Labels: feat, 탁세하 진행중🔥

#287 [BE] feat(#285): mongo db연동
  backend/build.gradle
  backend/src/main/java/com/example/backend/domain/config/MongoConfig.java
  backend/src/main/java/com/example/backend/domain/define/notice/Notice.java
  backend/src/main/java/com/example/backend/domain/define/notice/repository/NoticeRepository.java
  backend/src/test/java/com/example/backend/domain/define/notice/repository/NoticeRepositoryTest.java
Labels: feat, 구영민 진행중🔥

#302 dev -> main merge
  android/gitudy/data/src/main/java/com/takseha/data/api/gitudy/auth/GitudyAuthApi.kt
  android/gitudy/data/src/main/java/com/takseha/data/api/gitudy/study/GitudyStudyApi.kt
  android/gitudy/data/src/main/java/com/takseha/data/dto/mystudy/StudyListResponse.kt
  android/gitudy/data/src/main/java/com/takseha/data/repository/auth/GithubRepository.kt
  android/gitudy/data/src/main/java/com/takseha/data/repository/auth/GitudyAuthRepository.kt
  android/gitudy/data/src/main/java/com/takseha/data/repository/study/GitudyStudyRepository.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/adapter/FeedRVAdapter.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/adapter/RVAdapter.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/feed/FeedHomeFragment.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/viewholder/MyStudyListViewHolder.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/viewmodel/auth/LoginViewModel.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/viewmodel/auth/LoginWebViewViewModel.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/viewmodel/auth/RegisterViewModel.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/viewmodel/feed/FeedHomeViewModel.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/viewmodel/feed/MakeStudyViewModel.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/viewmodel/home/MainHomeViewModel.kt
  android/gitudy/presentation/src/main/res/drawable/ic_check_blue_sq.png
  android/gitudy/presentation/src/main/res/drawable/ic_check_empty_sq.png
  android/gitudy/presentation/src/main/res/drawable/ic_feed_save_white.png
  android/gitudy/presentation/src/main/res/drawable/ic_people.png
  android/gitudy/presentation/src/main/res/drawable/ic_sort.png
  android/gitudy/presentation/src/main/res/drawable/selector_ic_check_sq_checked.xml
  android/gitudy/presentation/src/main/res/layout/fragment_feed_home.xml
  android/gitudy/presentation/src/main/res/layout/fragment_make_study2.xml
  android/gitudy/presentation/src/main/res/layout/item_feed.xml
  android/gitudy/presentation/src/main/res/values/strings.xml
  backend/build.gradle
  backend/src/main/java/com/example/backend/auth/config/ProjectConfig.java
  backend/src/main/java/com/example/backend/domain/config/MongoConfig.java
  backend/src/main/java/com/example/backend/domain/define/notice/Notice.java
  backend/src/main/java/com/example/backend/domain/define/notice/repository/NoticeRepository.java
  backend/src/main/java/com/example/backend/domain/define/study/commit/StudyCommit.java
  backend/src/main/java/com/example/backend/domain/define/study/commit/constant/CommitStatus.java
  backend/src/main/java/com/example/backend/study/api/controller/commit/StudyCommitController.java
  backend/src/main/java/com/example/backend/study/api/controller/commit/request/CommitRejectionRequest.java
  backend/src/main/java/com/example/backend/study/api/service/commit/StudyCommitService.java
  backend/src/test/java/com/example/backend/domain/define/notice/repository/NoticeRepositoryTest.java
  backend/src/test/java/com/example/backend/domain/define/study/commit/StudyCommitFixture.java
  backend/src/test/java/com/example/backend/study/api/controller/commit/StudyCommitControllerTest.java
  backend/src/test/java/com/example/backend/study/api/service/commit/StudyCommitServiceTest.java
Labels: chore

#298 [BE] feat(#297): 리스너 수정 + 알림 로직 생성
  backend/src/main/java/com/example/backend/domain/define/fcm/listener/ApplyApproveRefuseMemberListener.java
  backend/src/main/java/com/example/backend/domain/define/fcm/listener/ApplyMemberListener.java
  backend/src/main/java/com/example/backend/domain/define/fcm/listener/NotifyMemberListener.java
  backend/src/main/java/com/example/backend/domain/define/fcm/listener/ResignMemberListener.java
  backend/src/main/java/com/example/backend/domain/define/fcm/listener/TodoRegisterMemberListener.java
  backend/src/main/java/com/example/backend/domain/define/fcm/listener/TodoUpdateMemberListener.java
  backend/src/main/java/com/example/backend/domain/define/fcm/listener/WithdrawalMemberListener.java
  backend/src/main/java/com/example/backend/domain/define/notice/Notice.java
  backend/src/main/java/com/example/backend/domain/define/study/info/event/ApplyApproveRefuseMemberEvent.java
  backend/src/main/java/com/example/backend/domain/define/study/info/event/ApplyMemberEvent.java
  backend/src/main/java/com/example/backend/domain/define/study/member/event/NotifyMemberEvent.java
  backend/src/main/java/com/example/backend/domain/define/study/member/event/ResignMemberEvent.java
  backend/src/main/java/com/example/backend/domain/define/study/member/event/WithdrawalMemberEvent.java
  backend/src/main/java/com/example/backend/domain/define/study/todo/event/TodoRegisterMemberEvent.java
  backend/src/main/java/com/example/backend/domain/define/study/todo/event/TodoUpdateMemberEvent.java
  backend/src/main/java/com/example/backend/study/api/controller/member/StudyMemberController.java
  backend/src/main/java/com/example/backend/study/api/event/service/NoticeService.java
  backend/src/main/java/com/example/backend/study/api/service/member/StudyMemberService.java
  backend/src/main/java/com/example/backend/study/api/service/todo/StudyTodoService.java
  backend/src/test/java/com/example/backend/domain/define/fcm/listener/ApplyApproveRefuseMemberListenerTest.java
  backend/src/test/java/com/example/backend/domain/define/fcm/listener/ApplyMemberListenerTest.java
  backend/src/test/java/com/example/backend/domain/define/fcm/listener/NotifyMemberListenerTest.java
  backend/src/test/java/com/example/backend/domain/define/fcm/listener/ResignMemberListenerTest.java
  backend/src/test/java/com/example/backend/domain/define/fcm/listener/TodoRegisterMemberListenerTest.java
  backend/src/test/java/com/example/backend/domain/define/fcm/listener/TodoUpdateMemberListenerTest.java
  backend/src/test/java/com/example/backend/domain/define/fcm/listener/WithdrawalMemberListenerTest.java
  backend/src/test/java/com/example/backend/domain/define/study/info/StudyEventFixture.java
  backend/src/test/java/com/example/backend/domain/define/study/member/MemberEventFixture.java
  backend/src/test/java/com/example/backend/domain/define/study/todo/TodoEventFixture.java
  backend/src/test/java/com/example/backend/study/api/service/member/StudyMemberServiceTest.java
  backend/src/test/java/com/example/backend/study/api/service/todo/StudyTodoServiceTest.java
Labels: refactor, feat

#301 [BE] feat(#300) 스터디 개수 조회 api 구현
  backend/src/main/java/com/example/backend/domain/define/study/info/repository/StudyInfoRepositoryCustom.java
  backend/src/main/java/com/example/backend/domain/define/study/info/repository/StudyInfoRepositoryImpl.java
  backend/src/main/java/com/example/backend/study/api/controller/info/StudyInfoController.java
  backend/src/main/java/com/example/backend/study/api/controller/info/response/StudyInfoCountResponse.java
  backend/src/main/java/com/example/backend/study/api/service/info/StudyInfoService.java
  backend/src/test/java/com/example/backend/study/api/controller/info/StudyInfoControllerTest.java
  backend/src/test/java/com/example/backend/study/api/service/info/StudyInfoServiceTest.java
Labels: feat, 구영민 진행중🔥

#296 [BE] feat(#295): 스터디 현재인원 증/감 로직 추가
  backend/src/main/java/com/example/backend/domain/define/study/info/StudyInfo.java
  backend/src/main/java/com/example/backend/study/api/service/member/StudyMemberService.java
  backend/src/test/java/com/example/backend/domain/define/study/info/StudyInfoFixture.java
  backend/src/test/java/com/example/backend/study/api/service/member/StudyMemberServiceTest.java
Labels: feat

#306 [BE] feat(#304): 알림 목록 조회 api
  backend/src/main/java/com/example/backend/domain/define/notice/repository/NoticeRepository.java
  backend/src/main/java/com/example/backend/domain/define/notice/repository/NoticeRepositoryCustom.java
  backend/src/main/java/com/example/backend/domain/define/notice/repository/NoticeRepositoryImpl.java
  backend/src/main/java/com/example/backend/study/api/event/controller/NoticeController.java
  backend/src/main/java/com/example/backend/study/api/event/controller/response/UserNoticeList.java
  backend/src/main/java/com/example/backend/study/api/event/service/NoticeService.java
  backend/src/test/java/com/example/backend/domain/define/notice/NoticeFixture.java
  backend/src/test/java/com/example/backend/study/api/event/controller/NoticeControllerTest.java
  backend/src/test/java/com/example/backend/study/api/event/service/NoticeServiceTest.java
Labels: feat

#308 [BE] feat(#307): 팀원이 팀장에게 알림 api
  backend/src/main/java/com/example/backend/domain/define/fcm/listener/NotifyLeaderListener.java
  backend/src/main/java/com/example/backend/domain/define/study/member/event/NotifyLeaderEvent.java
  backend/src/main/java/com/example/backend/study/api/controller/member/StudyMemberController.java
  backend/src/main/java/com/example/backend/study/api/event/service/NoticeService.java
  backend/src/main/java/com/example/backend/study/api/service/member/StudyMemberService.java
  backend/src/test/java/com/example/backend/domain/define/fcm/listener/NotifyLeaderListenerTest.java
  backend/src/test/java/com/example/backend/domain/define/study/member/MemberEventFixture.java
  backend/src/test/java/com/example/backend/study/api/controller/member/StudyMemberControllerTest.java
  backend/src/test/java/com/example/backend/study/api/service/member/StudyMemberServiceTest.java
Labels: feat

#305 feat(#303): 스터디장의 승인/거절을 기다리는 커밋 리스트 조회 api 구현
  backend/src/main/java/com/example/backend/domain/define/study/commit/repository/StudyCommitRepository.java
  backend/src/main/java/com/example/backend/study/api/controller/commit/StudyCommitController.java
  backend/src/main/java/com/example/backend/study/api/service/commit/StudyCommitService.java
  backend/src/test/java/com/example/backend/domain/define/study/commit/StudyCommitFixture.java
  backend/src/test/java/com/example/backend/study/api/controller/commit/StudyCommitControllerTest.java
  backend/src/test/java/com/example/backend/study/api/service/commit/StudyCommitServiceTest.java
Labels: feat, 이주성 진행중🔥

#310 [BE] feat(#309): 알림 삭제 api
  backend/src/main/java/com/example/backend/common/exception/ExceptionMessage.java
  backend/src/main/java/com/example/backend/common/exception/notice/NoticeException.java
  backend/src/main/java/com/example/backend/domain/define/notice/repository/NoticeRepository.java
  backend/src/main/java/com/example/backend/study/api/event/controller/NoticeController.java
  backend/src/main/java/com/example/backend/study/api/event/service/NoticeService.java
  backend/src/test/java/com/example/backend/domain/define/notice/repository/NoticeRepositoryTest.java
  backend/src/test/java/com/example/backend/study/api/event/controller/NoticeControllerTest.java
  backend/src/test/java/com/example/backend/study/api/event/service/NoticeServiceTest.java
Labels: feat

#313 feat(#312): 커밋 패치 로직 스케줄링 적용
  backend/src/main/java/com/example/backend/domain/define/study/commit/repository/StudyCommitRepository.java
  backend/src/main/java/com/example/backend/domain/define/study/todo/repository/StudyTodoRepository.java
  backend/src/main/java/com/example/backend/study/api/scheduler/config/AsyncConfig.java
  backend/src/main/java/com/example/backend/study/api/scheduler/config/SchedulingConfig.java
  backend/src/main/java/com/example/backend/study/api/scheduler/service/ScheduledCommitFetchService.java
  backend/src/main/java/com/example/backend/study/api/service/commit/StudyCommitService.java
  backend/src/main/java/com/example/backend/study/api/service/todo/StudyTodoService.java
  backend/src/test/java/com/example/backend/MockTestConfig.java
  backend/src/test/java/com/example/backend/TestConfig.java
  backend/src/test/java/com/example/backend/study/api/scheduler/service/ScheduledCommitFetchServiceTest.java
  backend/src/test/java/com/example/backend/study/api/service/commit/CommitFetchPerformanceTest.java
  backend/src/test/java/com/example/backend/study/api/service/commit/CommitFetchServiceTest.java
  backend/src/test/java/com/example/backend/study/api/service/commit/StudyCommitServiceTest.java
  backend/src/test/java/com/example/backend/study/api/service/todo/StudyTodoServiceTest.java
Labels: feat, 이주성 진행중🔥

#315 fix: 설정 파일 수정
  backend/build.gradle
Labels: fix, 이주성 진행중🔥

#317 [AN] feat(#299): 마이스터디 목록 생성 기능
  android/gitudy/data/src/main/java/com/takseha/data/api/gitudy/auth/GitudyAuthApi.kt
  android/gitudy/data/src/main/java/com/takseha/data/api/gitudy/study/GitudyStudyApi.kt
  android/gitudy/data/src/main/java/com/takseha/data/dto/feed/StudyListResponse.kt
  android/gitudy/data/src/main/java/com/takseha/data/dto/mystudy/MyStudyWithTodo.kt
  android/gitudy/data/src/main/java/com/takseha/data/dto/mystudy/TodoListResponse.kt
  android/gitudy/data/src/main/java/com/takseha/data/dto/mystudy/TodoProgressResponse.kt
  android/gitudy/data/src/main/java/com/takseha/data/dto/mystudy/TodoStatus.kt
  android/gitudy/data/src/main/java/com/takseha/data/repository/study/GitudyStudyRepository.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/adapter/FeedRVAdapter.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/adapter/MyStudyRVAdapter.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/feed/FeedHomeFragment.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/home/MainHomeActivity.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/home/MainHomeFragment.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/mystudy/MyStudyHomeFragment.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/viewmodel/feed/FeedHomeViewModel.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/viewmodel/home/MainHomeViewModel.kt
  android/gitudy/presentation/src/main/res/drawable/ic_git_white.png
  android/gitudy/presentation/src/main/res/layout/fragment_feed_home.xml
  android/gitudy/presentation/src/main/res/layout/fragment_main_home.xml
  android/gitudy/presentation/src/main/res/layout/fragment_my_study_home.xml
  android/gitudy/presentation/src/main/res/layout/item_feed.xml
  android/gitudy/presentation/src/main/res/layout/item_mystudy.xml
  android/gitudy/presentation/src/main/res/values/strings.xml
Labels: feat, 탁세하 진행중🔥
