Repository DKU-Dgaja/gitudy, pull requests merged in 2024-10, with the labels that each got.

#637 [BE] feat(#636) : 관리자 로그인 구현
  backend/src/main/java/com/example/backend/auth/api/controller/auth/AuthController.java
  backend/src/main/java/com/example/backend/auth/api/controller/auth/request/AdminLoginRequest.java
  backend/src/main/java/com/example/backend/auth/api/service/auth/AuthService.java
  backend/src/main/java/com/example/backend/auth/config/security/SecurityConfig.java
  backend/src/main/java/com/example/backend/common/exception/ExceptionMessage.java
  backend/src/test/java/com/example/backend/auth/api/controller/auth/AuthControllerTest.java
  backend/src/test/java/com/example/backend/auth/api/service/auth/AuthServiceTest.java
Labels: feat, 구영민 진행중🔥

#628 [BE] feat(#610): 테스트 코드 시간 최적화
  backend/src/test/java/com/example/backend/ApplicationContextInitListener.java
  backend/src/test/java/com/example/backend/CommonMockConfig.java
  backend/src/test/java/com/example/backend/MockTestConfig.java
  backend/src/test/java/com/example/backend/auth/api/controller/auth/AuthControllerTest.java
  backend/src/test/java/com/example/backend/auth/api/service/auth/AuthServiceTest.java
  backend/src/test/java/com/example/backend/auth/api/service/rank/RankingServiceTest.java
  backend/src/test/java/com/example/backend/study/api/controller/bookmark/StudyBookmarkControllerTest.java
  backend/src/test/java/com/example/backend/study/api/controller/category/info/CategoryControllerTest.java
  backend/src/test/java/com/example/backend/study/api/controller/comment/commit/CommitCommentControllerTest.java
  backend/src/test/java/com/example/backend/study/api/controller/comment/study/StudyCommentControllerTest.java
  backend/src/test/java/com/example/backend/study/api/controller/commit/StudyCommitControllerTest.java
  backend/src/test/java/com/example/backend/study/api/controller/convention/StudyConventionControllerTest.java
  backend/src/test/java/com/example/backend/study/api/controller/info/StudyInfoControllerTest.java
  backend/src/test/java/com/example/backend/study/api/controller/member/StudyMemberControllerTest.java
  backend/src/test/java/com/example/backend/study/api/controller/todo/StudyTodoControllerTest.java
  backend/src/test/java/com/example/backend/study/api/event/controller/FcmControllerTest.java
  backend/src/test/java/com/example/backend/study/api/event/controller/NoticeControllerTest.java
  backend/src/test/java/com/example/backend/study/api/event/service/FcmServiceTest.java
  backend/src/test/java/com/example/backend/study/api/event/service/NoticeServiceTest.java
  backend/src/test/java/com/example/backend/study/api/service/info/StudyInfoServiceTest.java
  backend/src/test/java/com/example/backend/study/api/service/member/StudyMemberServiceTest.java
  backend/src/test/java/com/example/backend/study/api/service/todo/StudyTodoServiceTest.java
Labels: feat, 구영민 진행중🔥

#639 [AN] refactor(#638): 배포 전 최종 수정 - 프로덕션 액세스 통과 :)
  android/gitudy/app/build.gradle.kts
  android/gitudy/presentation/src/main/java/com/takseha/presentation/adapter/CommitCommentListRVAdapter.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/adapter/DetailCommentListRVAdapter.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/adapter/ToDoListRVAdapter.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/feed/FeedHomeFragment.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/mystudy/MyStudyHomeFragment.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/mystudy/StudyCommentBoardFragment.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/mystudy/ToDoFragment.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/profile/CommitDetailFragment.kt
  android/gitudy/presentation/src/main/res/layout/fragment_main_home.xml
  android/gitudy/presentation/src/main/res/layout/item_comment_detail.xml
  android/gitudy/presentation/src/main/res/layout/item_commit_comment.xml
  android/gitudy/presentation/src/main/res/menu/report_menu.xml
  android/gitudy/presentation/src/main/res/values/strings.xml
Labels: refactor, 탁세하 진행중🔥

#643 [AN] fix(#640): 앱 토큰 암호화 관련 문제 해결
  android/gitudy/app/build.gradle.kts
  android/gitudy/data/src/main/java/com/takseha/data/api/gitudy/GitudyAuthService.kt
  android/gitudy/data/src/main/java/com/takseha/data/dto/auth/login/AdminLoginRequest.kt
  android/gitudy/data/src/main/java/com/takseha/data/sharedPreferences/SP.kt
  android/gitudy/data/src/main/java/com/takseha/data/token/TokenManager.kt
  android/gitudy/presentation/src/main/AndroidManifest.xml
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/auth/AdminLoginActivity.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/auth/LoginActivity.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/viewmodel/auth/AdminLoginViewModel.kt
  android/gitudy/presentation/src/main/res/drawable/ic_alarm_alert.png
  android/gitudy/presentation/src/main/res/drawable/ic_alarm_alert_white.png
  android/gitudy/presentation/src/main/res/drawable/ic_alert_gradient_c.png
  android/gitudy/presentation/src/main/res/drawable/ic_btn_make_study.png
  android/gitudy/presentation/src/main/res/drawable/ic_copy_check.png
  android/gitudy/presentation/src/main/res/drawable/ic_smile.png
  android/gitudy/presentation/src/main/res/drawable/img_study_background_1.png
  android/gitudy/presentation/src/main/res/drawable/img_study_background_2.png
  android/gitudy/presentation/src/main/res/layout/activity_admin_login.xml
  android/gitudy/presentation/src/main/res/layout/activity_login.xml
  android/gitudy/presentation/src/main/res/layout/fragment_study_apply_info.xml
  android/gitudy/presentation/src/main/res/values/strings.xml
Labels: fix
