Repository DKU-Dgaja/gitudy, pull requests merged in 2024-01, with the labels that each got.

#18 [FE] chore(#17): android project setting
  frontend/.gitignore
  frontend/app/.gitignore
  frontend/app/build.gradle.kts
  frontend/app/proguard-rules.pro
  frontend/app/src/androidTest/java/com/example/frontend/ExampleInstrumentedTest.kt
  frontend/app/src/main/AndroidManifest.xml
  frontend/app/src/main/java/com/example/frontend/MainActivity.kt
  frontend/app/src/main/java/com/example/frontend/ui/theme/Color.kt
  frontend/app/src/main/java/com/example/frontend/ui/theme/Theme.kt
  frontend/app/src/main/java/com/example/frontend/ui/theme/Type.kt
  frontend/app/src/main/res/drawable/ic_launcher_background.xml
  frontend/app/src/main/res/drawable/ic_launcher_foreground.xml
  frontend/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  frontend/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  frontend/app/src/main/res/mipmap-hdpi/ic_launcher.webp
  frontend/app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  frontend/app/src/main/res/mipmap-mdpi/ic_launcher.webp
  frontend/app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  frontend/app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  frontend/app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  frontend/app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  frontend/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  frontend/app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  frontend/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  frontend/app/src/main/res/values/colors.xml
  frontend/app/src/main/res/values/strings.xml
  frontend/app/src/main/res/values/themes.xml
  frontend/app/src/main/res/xml/backup_rules.xml
  frontend/app/src/main/res/xml/data_extraction_rules.xml
  frontend/app/src/test/java/com/example/frontend/ExampleUnitTest.kt
  frontend/build.gradle.kts
  frontend/gradle.properties
  frontend/gradle/wrapper/gradle-wrapper.jar
  frontend/gradle/wrapper/gradle-wrapper.properties
  frontend/gradlew
  frontend/gradlew.bat
  frontend/settings.gradle.kts
Labels: chore, 탁세하 진행중🔥

#26 [ALL] refactor(#25): README 프로필 수정
  README.md
Labels: refactor

#32 [BE] feat(#31): JWT 토큰 발급 로직 구현
  backend/src/main/java/com/example/backend/auth/api/controller/auth/AuthController.java
  backend/src/main/java/com/example/backend/auth/api/service/auth/AuthService.java
  backend/src/main/java/com/example/backend/auth/api/service/jwt/JwtToken.java
  backend/src/main/java/com/example/backend/auth/api/service/oauth/OAuthService.java
  backend/src/main/java/com/example/backend/auth/api/service/oauth/adapter/github/GithubAdapter.java
  backend/src/main/java/com/example/backend/auth/api/service/oauth/builder/github/GithubURLBuilder.java
  backend/src/main/java/com/example/backend/domain/define/user/User.java
  backend/src/main/java/com/example/backend/external/config/ExternalClientsPostProcessor.java
  backend/src/test/java/com/example/backend/auth/TestConfig.java
  backend/src/test/java/com/example/backend/auth/api/service/auth/AuthServiceTest.java
  backend/src/test/java/com/example/backend/auth/api/service/oauth/OAuthServiceTest.java
Labels: feat

#33 [BE] feat(#30): Google OAuth2 Login 구현
  backend/src/main/java/com/example/backend/auth/api/service/oauth/OAuthService.java
  backend/src/main/java/com/example/backend/auth/api/service/oauth/adapter/google/GoogleAdapter.java
  backend/src/main/java/com/example/backend/auth/api/service/oauth/builder/google/GoogleURLBuilder.java
  backend/src/main/java/com/example/backend/external/clients/oauth/google/GoogleProfileClients.java
  backend/src/main/java/com/example/backend/external/clients/oauth/google/GoogleTokenClients.java
  backend/src/main/java/com/example/backend/external/clients/oauth/google/response/GoogleProfileResponse.java
  backend/src/main/java/com/example/backend/external/clients/oauth/google/response/GoogleTokenResponse.java
  backend/src/test/java/com/example/backend/auth/api/service/oauth/OAuthServiceTest.java
  backend/src/test/java/com/example/backend/auth/api/service/oauth/adapter/google/GoogleAdapterTest.java
  backend/src/test/java/com/example/backend/auth/api/service/oauth/builder/google/GoogleURLBuilderTest.java
Labels: feat

#36 Chore: GitHub action
  .github/workflows/CI_dev_be_pull_request.yml
Labels: chore, 홍찬희 진행중🔥

#34 [BE] Feat(#29): Kakao OAuth2 Login 구현
  backend/src/main/java/com/example/backend/auth/api/service/oauth/OAuthService.java
  backend/src/main/java/com/example/backend/auth/api/service/oauth/adapter/kakao/KakaoAdapter.java
  backend/src/main/java/com/example/backend/auth/api/service/oauth/builder/kakao/KakaoURLBuilder.java
  backend/src/main/java/com/example/backend/external/clients/oauth/kakao/KakaoProfileClients.java
  backend/src/main/java/com/example/backend/external/clients/oauth/kakao/KakaoTokenClients.java
  backend/src/main/java/com/example/backend/external/clients/oauth/kakao/response/KakaoProfileResponse.java
  backend/src/main/java/com/example/backend/external/clients/oauth/kakao/response/KakaoTokenResponse.java
  backend/src/test/java/com/example/backend/auth/api/service/oauth/OAuthServiceTest.java
  backend/src/test/java/com/example/backend/auth/api/service/oauth/adapter/kakao/KakaoAdapterTest.java
  backend/src/test/java/com/example/backend/auth/api/service/oauth/builder/kakao/KakaoURLBuilderTest.java
  backend/src/test/java/com/example/backend/external/clients/oauth/kakao/KakaoClientTest.java
Labels: feat

#37 [BE] chore(#35): Redis setting
  backend/build.gradle
  backend/src/main/java/com/example/backend/auth/api/service/auth/AuthService.java
  backend/src/main/java/com/example/backend/auth/api/service/oauth/OAuthService.java
  backend/src/main/java/com/example/backend/domain/config/RedisConfig.java
  backend/src/main/java/com/example/backend/domain/define/test/RedisTest.java
  backend/src/main/java/com/example/backend/domain/define/test/repository/RedisTestRepository.java
  backend/src/test/java/com/example/backend/auth/api/service/jwt/JwtServiceTest.java
  backend/src/test/java/com/example/backend/auth/api/service/oauth/adapter/github/GithubAdapterTest.java
  backend/src/test/java/com/example/backend/domain/redis/define/test/repository/RedisTestRepositoryTest.java
Labels: chore, 이주성 진행중🔥

#45 [BE] chore pipeline
  .github/workflows/CI_dev_be_pull_request.yml
Labels: chore, 홍찬희 진행중🔥

#52 [BE] refactor(#51): OAuthServiceTest 오류수정
  .github/workflows/CI_dev_be_pull_request.yml
  backend/src/test/java/com/example/backend/auth/api/service/oauth/OAuthServiceTest.java
Labels: refactor, 이정우 진행중🔥

#55 Feat(#53) swagger setting
  backend/src/main/java/com/example/backend/auth/config/ProjectConfig.java
  backend/src/main/java/com/example/backend/auth/config/security/SecurityConfig.java
  backend/src/main/java/com/example/backend/auth/config/swagger/SwaggerConfig.java
Labels: chore

#60 [FE] feat(#58, #42): UI 구현 관련 res 정의 및 Splash 화면 구현
  frontend/app/src/main/AndroidManifest.xml
  frontend/app/src/main/java/com/takseha/frontend/MainActivity.kt
  frontend/presentation/src/main/AndroidManifest.xml
  frontend/presentation/src/main/java/com/takseha/presentation/ui/SplashActivity.kt
  frontend/presentation/src/main/res/drawable/gitudy_logo.png
  frontend/presentation/src/main/res/drawable/gradient.xml
  frontend/presentation/src/main/res/font/pretendard_black.otf
  frontend/presentation/src/main/res/font/pretendard_bold.otf
  frontend/presentation/src/main/res/font/pretendard_extrabold.otf
  frontend/presentation/src/main/res/font/pretendard_extralight.otf
  frontend/presentation/src/main/res/font/pretendard_light.otf
  frontend/presentation/src/main/res/font/pretendard_medium.otf
  frontend/presentation/src/main/res/font/pretendard_regular.otf
  frontend/presentation/src/main/res/font/pretendard_semibold.otf
  frontend/presentation/src/main/res/font/pretendard_thin.otf
  frontend/presentation/src/main/res/layout/activity_splash.xml
  frontend/presentation/src/main/res/values/colors.xml
  frontend/presentation/src/main/res/values/strings.xml
  frontend/presentation/src/main/res/values/styles.xml
  frontend/presentation/src/main/res/values/themes.xml
Labels: refactor, feat, 탁세하 진행중🔥

#48 [BE] feat(#47): refresh token 생성 및 저장 구현
  backend/src/main/java/com/example/backend/auth/api/service/auth/AuthService.java
  backend/src/main/java/com/example/backend/auth/api/service/jwt/JwtService.java
  backend/src/main/java/com/example/backend/auth/api/service/token/RefreshTokenService.java
  backend/src/main/java/com/example/backend/domain/define/refreshToken/RefreshToken.java
  backend/src/main/java/com/example/backend/domain/define/refreshToken/repository/RefreshTokenRepository.java
  backend/src/test/java/com/example/backend/auth/api/service/jwt/JwtServiceTest.java
  backend/src/test/java/com/example/backend/auth/api/service/token/RefreshTokenServiceTest.java
  backend/src/test/java/com/example/backend/domain/define/refreshToken/repository/RefreshTokenRepositoryTest.java
Labels: feat

#56 [BE] feat(#46): state verification
  backend/src/main/java/com/example/backend/auth/api/controller/auth/AuthController.java
  backend/src/main/java/com/example/backend/auth/api/service/state/LoginStateService.java
  backend/src/main/java/com/example/backend/common/exception/ExceptionMessage.java
  backend/src/main/java/com/example/backend/common/exception/state/LoginStateException.java
  backend/src/main/java/com/example/backend/domain/define/state/LoginState.java
  backend/src/main/java/com/example/backend/domain/define/state/LoginStateRepository.java
  backend/src/test/java/com/example/backend/domain/redis/define/state/LoginStateTest.java
  backend/src/test/java/com/example/backend/external/clients/oauth/google/GoogleClientTest.java
Labels: feat, 이정우 진행중🔥

#69 Refactor(#68) generate refresh token test error 수정
  backend/src/test/java/com/example/backend/auth/api/service/jwt/JwtServiceTest.java
Labels: refactor

#70 [BE] refactor (#68): platformId -> subject 수정
  backend/src/main/java/com/example/backend/auth/api/service/auth/AuthService.java
  backend/src/main/java/com/example/backend/auth/api/service/state/LoginStateService.java
  backend/src/main/java/com/example/backend/domain/define/refreshToken/RefreshToken.java
  backend/src/main/java/com/example/backend/domain/define/state/LoginState.java
  backend/src/main/java/com/example/backend/domain/define/state/LoginStateRepository.java
  backend/src/test/java/com/example/backend/auth/api/service/jwt/JwtServiceTest.java
  backend/src/test/java/com/example/backend/auth/api/service/token/RefreshTokenServiceTest.java
  backend/src/test/java/com/example/backend/domain/define/refreshToken/repository/RefreshTokenRepositoryTest.java
  backend/src/test/java/com/example/backend/domain/redis/define/state/LoginStateTest.java
Labels: refactor

#71 [FE] feat(#66): 로그인 및 회원가입 페이지 UI 구현
  frontend/presentation/build.gradle.kts
  frontend/presentation/src/main/AndroidManifest.xml
  frontend/presentation/src/main/java/com/takseha/presentation/ui/SplashActivity.kt
  frontend/presentation/src/main/java/com/takseha/presentation/ui/login/AgreementActivity.kt
  frontend/presentation/src/main/java/com/takseha/presentation/ui/login/Detail1Fragment.kt
  frontend/presentation/src/main/java/com/takseha/presentation/ui/login/Detail2Fragment.kt
  frontend/presentation/src/main/java/com/takseha/presentation/ui/login/Detail3Fragment.kt
  frontend/presentation/src/main/java/com/takseha/presentation/ui/login/InputIdActivity.kt
  frontend/presentation/src/main/java/com/takseha/presentation/ui/login/InputNameActivity.kt
  frontend/presentation/src/main/java/com/takseha/presentation/ui/login/LoginActivity.kt
  frontend/presentation/src/main/java/com/takseha/presentation/ui/login/LoginCompleteFragment.kt
  frontend/presentation/src/main/java/com/takseha/presentation/ui/login/PopupFragment.kt
  frontend/presentation/src/main/java/com/takseha/presentation/ui/login/SubLoginActivity.kt
  frontend/presentation/src/main/res/drawable/box_non_stroke_green.xml
  frontend/presentation/src/main/res/drawable/box_stroke.xml
  frontend/presentation/src/main/res/drawable/character_bebe_lv1.png
  frontend/presentation/src/main/res/drawable/character_shadow.png
  frontend/presentation/src/main/res/drawable/gradient.xml
  frontend/presentation/src/main/res/drawable/ic_arrow.png
  frontend/presentation/src/main/res/drawable/ic_arrow_back.png
  frontend/presentation/src/main/res/drawable/ic_check_grey.png
  frontend/presentation/src/main/res/drawable/ic_check_grey_r.png
  frontend/presentation/src/main/res/drawable/ic_exit.png
  frontend/presentation/src/main/res/drawable/logo_github.png
  frontend/presentation/src/main/res/drawable/logo_gitudy.png
  frontend/presentation/src/main/res/drawable/logo_google.png
  frontend/presentation/src/main/res/drawable/logo_kakao.png
  frontend/presentation/src/main/res/layout/activity_agreement.xml
  frontend/presentation/src/main/res/layout/activity_input_id.xml
  frontend/presentation/src/main/res/layout/activity_input_name.xml
  frontend/presentation/src/main/res/layout/activity_login.xml
  frontend/presentation/src/main/res/layout/activity_splash.xml
  frontend/presentation/src/main/res/layout/activity_sub_login.xml
  frontend/presentation/src/main/res/layout/fragment_detail1.xml
  frontend/presentation/src/main/res/layout/fragment_detail2.xml
  frontend/presentation/src/main/res/layout/fragment_detail3.xml
  frontend/presentation/src/main/res/layout/fragment_login_complete.xml
  frontend/presentation/src/main/res/layout/fragment_popup.xml
  frontend/presentation/src/main/res/values/dimens.xml
  frontend/presentation/src/main/res/values/strings.xml
  frontend/presentation/src/main/res/values/styles.xml
Labels: refactor, feat, 탁세하 진행중🔥

#74 [FE] refactor(#73): 로그인 관련 UI 수정
  frontend/presentation/src/main/res/drawable/character_bebe_lv1.png
  frontend/presentation/src/main/res/drawable/character_shadow.png
  frontend/presentation/src/main/res/drawable/ic_alert_red.png
  frontend/presentation/src/main/res/drawable/ic_arrow.png
  frontend/presentation/src/main/res/drawable/ic_arrow_back.png
  frontend/presentation/src/main/res/drawable/ic_check_green.png
  frontend/presentation/src/main/res/drawable/ic_check_grey.png
  frontend/presentation/src/main/res/drawable/ic_check_grey_r.png
  frontend/presentation/src/main/res/drawable/ic_exit.png
  frontend/presentation/src/main/res/drawable/logo_github.png
  frontend/presentation/src/main/res/drawable/logo_google.png
  frontend/presentation/src/main/res/drawable/logo_kakao.png
  frontend/presentation/src/main/res/layout/activity_input_id.xml
  frontend/presentation/src/main/res/layout/activity_login.xml
  frontend/presentation/src/main/res/layout/activity_sub_login.xml
  frontend/presentation/src/main/res/layout/fragment_detail1.xml
  frontend/presentation/src/main/res/layout/fragment_detail2.xml
  frontend/presentation/src/main/res/layout/fragment_detail3.xml
  frontend/presentation/src/main/res/layout/fragment_popup.xml
Labels: refactor, 탁세하 진행중🔥

#78 [BE] chore(#77): querydsl setting
  backend/.gitignore
  backend/build.gradle
  backend/src/main/java/com/example/backend/domain/config/QueryDslConfig.java
  backend/src/main/java/com/example/backend/domain/define/test/DslTest.java
  backend/src/main/java/com/example/backend/domain/define/test/repository/DslTestRepository.java
  backend/src/main/java/com/example/backend/domain/define/test/repository/DslTestRepositoryCustom.java
  backend/src/main/java/com/example/backend/domain/define/test/repository/DslTestRepositoryImpl.java
  backend/src/test/java/com/example/backend/domain/define/test/repository/DslTestRepositoryTest.java
Labels: chore, 이주성 진행중🔥

#76 [BE] feat(#61): logout 구현
  backend/src/main/java/com/example/backend/auth/api/controller/auth/AuthController.java
  backend/src/main/java/com/example/backend/auth/api/service/auth/AuthService.java
  backend/src/main/java/com/example/backend/auth/api/service/token/RefreshTokenService.java
  backend/src/main/java/com/example/backend/auth/config/security/filter/JwtAuthenticationFilter.java
  backend/src/main/java/com/example/backend/common/exception/ExceptionMessage.java
  backend/src/test/java/com/example/backend/auth/TestConfig.java
  backend/src/test/java/com/example/backend/auth/api/controller/auth/AuthControllerTest.java
Labels: feat, 이정우 진행중🔥

#75 [BE] Feat: (#64) jwt 재발급 구현
  backend/src/main/java/com/example/backend/auth/api/controller/auth/AuthController.java
  backend/src/main/java/com/example/backend/auth/api/controller/auth/response/ReissueAccessTokenResponse.java
  backend/src/main/java/com/example/backend/auth/api/service/auth/AuthService.java
  backend/src/main/java/com/example/backend/auth/api/service/jwt/JwtService.java
  backend/src/main/java/com/example/backend/auth/api/service/token/RefreshTokenService.java
  backend/src/main/java/com/example/backend/auth/config/security/filter/JwtAuthenticationFilter.java
  backend/src/main/java/com/example/backend/common/exception/ExceptionMessage.java
  backend/src/test/java/com/example/backend/auth/api/service/auth/AuthServiceTest.java
  backend/src/test/java/com/example/backend/auth/api/service/jwt/JwtServiceTest.java
  backend/src/test/java/com/example/backend/auth/api/service/token/RefreshTokenServiceTest.java
Labels: refactor, feat

#80 [BE] fix(#79): 패키지 경로 수정
  backend/src/main/java/com/example/backend/auth/api/controller/auth/AuthController.java
  backend/src/main/java/com/example/backend/auth/api/service/auth/AuthService.java
  backend/src/main/java/com/example/backend/auth/api/service/token/RefreshTokenService.java
  backend/src/main/java/com/example/backend/auth/config/security/filter/JwtAuthenticationFilter.java
  backend/src/test/java/com/example/backend/auth/api/service/token/RefreshTokenServiceTest.java
Labels: fix, 이정우 진행중🔥

#85 [AN] feat(#83): 메인 홈 관련 페이지 UI 구현
  frontend/presentation/src/main/AndroidManifest.xml
  frontend/presentation/src/main/java/com/takseha/presentation/ui/feed/FeedHomeFragment.kt
  frontend/presentation/src/main/java/com/takseha/presentation/ui/home/EditNicknameFragment.kt
  frontend/presentation/src/main/java/com/takseha/presentation/ui/home/MainHomeActivity.kt
  frontend/presentation/src/main/java/com/takseha/presentation/ui/home/MainHomeFragment.kt
  frontend/presentation/src/main/java/com/takseha/presentation/ui/mystudy/MyStudyHomeFragment.kt
  frontend/presentation/src/main/res/drawable/box_stroke_200_r21.xml
  frontend/presentation/src/main/res/drawable/character_bebe_first.png
  frontend/presentation/src/main/res/drawable/character_bebe_lv1.png
  frontend/presentation/src/main/res/drawable/character_bebe_over_130.png
  frontend/presentation/src/main/res/drawable/character_bebe_to_100.png
  frontend/presentation/src/main/res/drawable/character_bebe_to_130.png
  frontend/presentation/src/main/res/drawable/character_bebe_to_15.png
  frontend/presentation/src/main/res/drawable/character_bebe_to_30.png
  frontend/presentation/src/main/res/drawable/character_bebe_to_50.png
  frontend/presentation/src/main/res/drawable/character_bebe_to_70.png
  frontend/presentation/src/main/res/drawable/ic_alarm_alert_white.png
  frontend/presentation/src/main/res/drawable/ic_alarm_white.png
  frontend/presentation/src/main/res/drawable/ic_attendance.png
  frontend/presentation/src/main/res/drawable/ic_todo.png
  frontend/presentation/src/main/res/drawable/progress_bar.xml
  frontend/presentation/src/main/res/layout/activity_main_home.xml
  frontend/presentation/src/main/res/layout/fragment_edit_nickname.xml
  frontend/presentation/src/main/res/layout/fragment_feed_home.xml
  frontend/presentation/src/main/res/layout/fragment_login_complete.xml
  frontend/presentation/src/main/res/layout/fragment_main_home.xml
  frontend/presentation/src/main/res/layout/fragment_my_study_home.xml
  frontend/presentation/src/main/res/values/strings.xml
Labels: feat, 탁세하 진행중🔥
