Repository DKU-Dgaja/gitudy, pull requests merged in 2024-03, with the labels that each got.

#148 [BE] feat(#146) : 스터디 댓글 삭제 api 구현
  backend/src/main/java/com/example/backend/study/api/controller/comment/study/StudyCommentController.java
  backend/src/main/java/com/example/backend/study/api/service/comment/study/StudyCommentService.java
  backend/src/main/java/com/example/backend/study/api/service/member/StudyMemberService.java
  backend/src/test/java/com/example/backend/study/api/controller/comment/study/StudyCommentControllerTest.java
  backend/src/test/java/com/example/backend/study/api/service/comment/study/StudyCommentServiceTest.java
Labels: feat, 구영민 진행중🔥

#162 [BE] feat(#161): 컨벤션 등록 api
  backend/src/main/java/com/example/backend/domain/define/study/convention/repository/StudyConventionRepository.java
  backend/src/main/java/com/example/backend/study/api/controller/convention/StudyConventionController.java
  backend/src/main/java/com/example/backend/study/api/controller/convention/request/StudyConventionRequest.java
  backend/src/main/java/com/example/backend/study/api/service/convention/StudyConventionService.java
  backend/src/test/java/com/example/backend/domain/define/study/convention/StudyConventionFixture.java
  backend/src/test/java/com/example/backend/study/api/controller/convention/StudyConventionControllerTest.java
  backend/src/test/java/com/example/backend/study/api/service/convention/StudyConventionServiceTest.java
Labels: feat, 이정우 진행중🔥

#166 [BE] fix(#165): 테스트 오류해결
  backend/src/test/java/com/example/backend/study/api/controller/convention/StudyConventionControllerTest.java
Labels: fix, 이정우 진행중🔥

#156 [BE] feat(#152): 스터디원 강퇴, 스터디 탈퇴 api
  backend/src/main/java/com/example/backend/domain/define/study/member/StudyMember.java
  backend/src/main/java/com/example/backend/domain/define/study/member/repository/StudyMemberRepository.java
  backend/src/main/java/com/example/backend/domain/define/study/todo/mapping/repository/StudyTodoMappingRepository.java
  backend/src/main/java/com/example/backend/domain/define/study/todo/repository/StudyTodoRepositoryCustom.java
  backend/src/main/java/com/example/backend/domain/define/study/todo/repository/StudyTodoRepositoryImpl.java
  backend/src/main/java/com/example/backend/study/api/controller/member/StudyMemberController.java
  backend/src/main/java/com/example/backend/study/api/service/member/StudyMemberService.java
  backend/src/test/java/com/example/backend/domain/define/study/todo/StudyTodoFixture.java
  backend/src/test/java/com/example/backend/study/api/controller/member/StudyMemberControllerTest.java
  backend/src/test/java/com/example/backend/study/api/service/member/StudyMemberServiceTest.java
Labels: feat, 이정우 진행중🔥

#136 [BE] feat(#135): 마이스터디 조회 api 구현
  backend/src/main/java/com/example/backend/domain/define/account/user/repository/UserRepository.java
  backend/src/main/java/com/example/backend/domain/define/account/user/repository/UserRepositoryCustom.java
  backend/src/main/java/com/example/backend/domain/define/account/user/repository/UserRepositoryImpl.java
  backend/src/main/java/com/example/backend/domain/define/study/category/info/repository/StudyCategoryRepository.java
  backend/src/main/java/com/example/backend/domain/define/study/category/info/repository/StudyCategoryRepositoryCustom.java
  backend/src/main/java/com/example/backend/domain/define/study/category/info/repository/StudyCategoryRepositoryImpl.java
  backend/src/main/java/com/example/backend/domain/define/study/category/mapping/repository/StudyCategoryMappingRepository.java
  backend/src/main/java/com/example/backend/domain/define/study/category/mapping/repository/StudyCategoryMappingRepositoryCustom.java
  backend/src/main/java/com/example/backend/domain/define/study/category/mapping/repository/StudyCategoryMappingRepositoryImpl.java
  backend/src/main/java/com/example/backend/domain/define/study/info/repository/StudyInfoRepository.java
  backend/src/main/java/com/example/backend/domain/define/study/info/repository/StudyInfoRepositoryCustom.java
  backend/src/main/java/com/example/backend/domain/define/study/info/repository/StudyInfoRepositoryImpl.java
  backend/src/main/java/com/example/backend/domain/define/study/member/repository/StudyMemberRepositoryCustom.java
  backend/src/main/java/com/example/backend/domain/define/study/member/repository/StudyMemberRepositoryImpl.java
  backend/src/main/java/com/example/backend/study/api/controller/info/StudyInfoController.java
  backend/src/main/java/com/example/backend/study/api/controller/info/response/CategoryResponseWithStudyId.java
  backend/src/main/java/com/example/backend/study/api/controller/info/response/MyStudyInfoListAndCursorIdxResponse.java
  backend/src/main/java/com/example/backend/study/api/controller/info/response/MyStudyInfoListResponse.java
  backend/src/main/java/com/example/backend/study/api/controller/info/response/StudyMemberWithUserInfoResponse.java
  backend/src/main/java/com/example/backend/study/api/service/info/StudyInfoService.java
  backend/src/main/java/com/example/backend/study/api/service/info/response/StudyCategoryMappingListResponse.java
  backend/src/main/java/com/example/backend/study/api/service/info/response/StudyMembersIdListResponse.java
  backend/src/main/java/com/example/backend/study/api/service/info/response/UserNameAndProfileImageResponse.java
  backend/src/test/java/com/example/backend/domain/define/study/category/mapping/repository/StudyCategoryMappingRepositoryTest.java
  backend/src/test/java/com/example/backend/domain/define/study/info/StudyInfoFixture.java
  backend/src/test/java/com/example/backend/domain/define/study/info/repository/StudyInfoRepositoryTest.java
  backend/src/test/java/com/example/backend/domain/define/study/member/StudyMemberFixture.java
  backend/src/test/java/com/example/backend/domain/define/study/member/repository/StudyMemberRepositoryTest.java
  backend/src/test/java/com/example/backend/study/api/controller/info/StudyInfoControllerTest.java
  backend/src/test/java/com/example/backend/study/api/service/info/StudyInfoServiceTest.java
Labels: feat, 구영민 진행중🔥

#159 [BE] feat(#158): 스터디 댓글 리스트 조회 api 구현
  backend/src/main/java/com/example/backend/domain/define/study/comment/study/repository/StudyCommentRepository.java
  backend/src/main/java/com/example/backend/domain/define/study/comment/study/repository/StudyCommentRepositoryCustom.java
  backend/src/main/java/com/example/backend/domain/define/study/comment/study/repository/StudyCommentRepositoryImpl.java
  backend/src/main/java/com/example/backend/study/api/controller/comment/study/StudyCommentController.java
  backend/src/main/java/com/example/backend/study/api/controller/comment/study/response/StudyCommentListAndCursorIdxResponse.java
  backend/src/main/java/com/example/backend/study/api/controller/comment/study/response/StudyCommentResponse.java
  backend/src/main/java/com/example/backend/study/api/service/comment/study/StudyCommentService.java
  backend/src/main/java/com/example/backend/study/api/service/comment/study/response/UserInfoForStudyCommentResponse.java
  backend/src/test/java/com/example/backend/domain/define/study/comment/StudyCommentFixture.java
  backend/src/test/java/com/example/backend/domain/define/study/comment/study/repository/StudyCommentRepositoryTest.java
  backend/src/test/java/com/example/backend/study/api/controller/comment/study/StudyCommentControllerTest.java
  backend/src/test/java/com/example/backend/study/api/service/comment/study/StudyCommentServiceTest.java
Labels: feat, 구영민 진행중🔥

#175 [BE] feat(#174): 컨벤션 조회 api
  backend/src/main/java/com/example/backend/domain/define/study/convention/repository/StudyConventionRepository.java
  backend/src/main/java/com/example/backend/domain/define/study/convention/repository/StudyConventionRepositoryCustom.java
  backend/src/main/java/com/example/backend/domain/define/study/convention/repository/StudyConventionRepositoryImpl.java
  backend/src/main/java/com/example/backend/study/api/controller/convention/StudyConventionController.java
  backend/src/main/java/com/example/backend/study/api/controller/convention/response/StudyConventionListAndCursorIdxResponse.java
  backend/src/main/java/com/example/backend/study/api/controller/convention/response/StudyConventionResponse.java
  backend/src/main/java/com/example/backend/study/api/service/convention/StudyConventionService.java
  backend/src/test/java/com/example/backend/domain/define/study/convention/StudyConventionFixture.java
  backend/src/test/java/com/example/backend/domain/define/study/convention/repository/StudyConventionRepositoryTest.java
  backend/src/test/java/com/example/backend/study/api/controller/convention/StudyConventionControllerTest.java
  backend/src/test/java/com/example/backend/study/api/service/convention/StudyConventionServiceTest.java
Labels: feat, 이정우 진행중🔥

#177 [BE] refactor(#176): 회원가입 로직 수정
  backend/src/main/java/com/example/backend/auth/api/controller/auth/AuthController.java
  backend/src/main/java/com/example/backend/auth/api/controller/auth/request/AuthRegisterRequest.java
  backend/src/main/java/com/example/backend/auth/api/controller/auth/response/AuthLoginResponse.java
  backend/src/main/java/com/example/backend/auth/api/service/auth/AuthService.java
  backend/src/main/java/com/example/backend/auth/api/service/auth/request/AuthServiceRegisterRequest.java
  backend/src/main/java/com/example/backend/auth/api/service/auth/response/AuthServiceLoginResponse.java
  backend/src/main/java/com/example/backend/auth/config/security/SecurityConfig.java
  backend/src/main/java/com/example/backend/domain/define/account/user/User.java
  backend/src/test/java/com/example/backend/auth/api/controller/auth/AuthControllerTest.java
  backend/src/test/java/com/example/backend/auth/api/service/auth/AuthServiceTest.java
  backend/src/test/java/com/example/backend/common/utils/TokenUtil.java
Labels: refactor, 이주성 진행중🔥

#182 [BE] refactor(#181): 스터디 멤버 상태 수정
  backend/src/main/java/com/example/backend/domain/define/study/member/constant/StudyMemberStatus.java
Labels: refactor, 이정우 진행중🔥

#186 [BE] refactor(#176): 회원가입 DTO 수정
  backend/src/main/java/com/example/backend/auth/api/controller/auth/request/AuthRegisterRequest.java
  backend/src/main/java/com/example/backend/auth/api/controller/auth/response/AuthLoginResponse.java
  backend/src/test/java/com/example/backend/auth/api/controller/auth/AuthControllerTest.java
Labels: refactor, 이주성 진행중🔥

#173 [BE] feat(#172): 전체 스터디 목록 조회 api 구현
  backend/src/main/java/com/example/backend/domain/define/study/info/repository/StudyInfoRepositoryCustom.java
  backend/src/main/java/com/example/backend/domain/define/study/info/repository/StudyInfoRepositoryImpl.java
  backend/src/main/java/com/example/backend/study/api/controller/info/StudyInfoController.java
  backend/src/main/java/com/example/backend/study/api/controller/info/response/StudyInfoListAndCursorIdxResponse.java
  backend/src/main/java/com/example/backend/study/api/controller/info/response/StudyInfoListResponse.java
  backend/src/main/java/com/example/backend/study/api/service/info/StudyInfoService.java
  backend/src/test/java/com/example/backend/domain/define/study/info/StudyInfoFixture.java
  backend/src/test/java/com/example/backend/domain/define/study/info/repository/StudyInfoRepositoryTest.java
  backend/src/test/java/com/example/backend/study/api/controller/info/StudyInfoControllerTest.java
  backend/src/test/java/com/example/backend/study/api/service/info/StudyInfoServiceTest.java
Labels: feat, 구영민 진행중🔥

#192 [BE] refactor(#191): Swagger-ui snake case 변환
  backend/build.gradle
  backend/src/main/java/com/example/backend/auth/config/ProjectConfig.java
Labels: refactor, 구영민 진행중🔥

#183 [BE] feat(#178): 스터디 가입 신청 api
  backend/src/main/java/com/example/backend/common/exception/ExceptionMessage.java
  backend/src/main/java/com/example/backend/domain/define/study/member/StudyMember.java
  backend/src/main/java/com/example/backend/domain/define/study/member/repository/StudyMemberRepositoryCustom.java
  backend/src/main/java/com/example/backend/domain/define/study/member/repository/StudyMemberRepositoryImpl.java
  backend/src/main/java/com/example/backend/study/api/controller/member/StudyMemberController.java
  backend/src/main/java/com/example/backend/study/api/service/member/StudyMemberService.java
  backend/src/test/java/com/example/backend/domain/define/study/info/StudyInfoFixture.java
  backend/src/test/java/com/example/backend/domain/define/study/member/StudyMemberFixture.java
  backend/src/test/java/com/example/backend/study/api/controller/member/StudyMemberControllerTest.java
  backend/src/test/java/com/example/backend/study/api/service/member/StudyMemberServiceTest.java
Labels: feat, 이정우 진행중🔥

#189 [BE] feat(#185): 스터디 상세정보 api 구현
  backend/src/main/java/com/example/backend/study/api/controller/info/StudyInfoController.java
  backend/src/main/java/com/example/backend/study/api/controller/info/response/StudyInfoDetailResponse.java
  backend/src/main/java/com/example/backend/study/api/service/info/StudyInfoService.java
  backend/src/test/java/com/example/backend/domain/define/study/info/StudyInfoFixture.java
  backend/src/test/java/com/example/backend/study/api/controller/info/StudyInfoControllerTest.java
  backend/src/test/java/com/example/backend/study/api/service/info/StudyInfoServiceTest.java
Labels: feat, 구영민 진행중🔥

#197 [BE] refactor(#196): category id list 반환 -> category name list 반환
  backend/src/main/java/com/example/backend/domain/define/study/category/info/repository/StudyCategoryRepositoryCustom.java
  backend/src/main/java/com/example/backend/domain/define/study/category/info/repository/StudyCategoryRepositoryImpl.java
  backend/src/main/java/com/example/backend/study/api/controller/info/StudyInfoController.java
  backend/src/main/java/com/example/backend/study/api/controller/info/response/StudyInfoDetailResponse.java
  backend/src/main/java/com/example/backend/study/api/controller/info/response/UpdateStudyInfoPageResponse.java
  backend/src/main/java/com/example/backend/study/api/service/info/StudyInfoService.java
  backend/src/test/java/com/example/backend/domain/define/study/category/mapping/repository/StudyCategoryMappingRepositoryTest.java
  backend/src/test/java/com/example/backend/domain/define/study/info/StudyInfoFixture.java
  backend/src/test/java/com/example/backend/study/api/service/info/StudyInfoServiceTest.java
Labels: refactor, 구영민 진행중🔥

#198 [AN] refactor(#195): 유저 연동 깃허브 아이디 유효성 검증 기능 수정
  android/gitudy/data/src/main/java/com/takseha/data/api/github/GithubApi.kt
  android/gitudy/data/src/main/java/com/takseha/data/api/github/RetrofitInstance.kt
  android/gitudy/data/src/main/java/com/takseha/data/dto/auth/register/GithubIdResponse.kt
  android/gitudy/data/src/main/java/com/takseha/data/repository/GithubRepository.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/login/InputIdFragment.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/login/RegisterCompleteFragment.kt
  android/gitudy/presentation/src/main/res/anim/alpha.xml
  android/gitudy/presentation/src/main/res/anim/fade_in.xml
  android/gitudy/presentation/src/main/res/layout/fragment_input_id.xml
  android/gitudy/presentation/src/main/res/layout/fragment_register_complete.xml
  android/gitudy/presentation/src/main/res/values/strings.xml
Labels: refactor, 탁세하 진행중🔥

#199 [BE] feat(#184): 스터디장의 가입신청 승인/거부
  backend/src/main/java/com/example/backend/study/api/controller/member/StudyMemberController.java
  backend/src/main/java/com/example/backend/study/api/service/member/StudyMemberService.java
  backend/src/test/java/com/example/backend/study/api/controller/member/StudyMemberControllerTest.java
  backend/src/test/java/com/example/backend/study/api/service/member/StudyMemberServiceTest.java
Labels: feat, 이정우 진행중🔥

#204 [BE] feat(#203): 스터디 가입 신청 취소 api
  backend/src/main/java/com/example/backend/common/exception/ExceptionMessage.java
  backend/src/main/java/com/example/backend/study/api/controller/member/StudyMemberController.java
  backend/src/main/java/com/example/backend/study/api/service/member/StudyMemberService.java
  backend/src/test/java/com/example/backend/study/api/controller/member/StudyMemberControllerTest.java
  backend/src/test/java/com/example/backend/study/api/service/member/StudyMemberServiceTest.java
Labels: feat, 이정우 진행중🔥

#202 [BE] feat(#201): category 등록 api
  backend/src/main/java/com/example/backend/study/api/controller/category/info/CategoryController.java
  backend/src/main/java/com/example/backend/study/api/controller/category/info/request/CategoryRegisterRequest.java
  backend/src/main/java/com/example/backend/study/api/service/category/info/CategoryService.java
  backend/src/test/java/com/example/backend/study/api/controller/category/info/CategoryControllerTest.java
  backend/src/test/java/com/example/backend/study/api/service/category/info/CategoryServiceTest.java
Labels: feat, 구영민 진행중🔥

#208 [BE] feat(#207): 카테고리 수정, 삭제 api 구현
  backend/src/main/java/com/example/backend/common/exception/ExceptionMessage.java
  backend/src/main/java/com/example/backend/common/exception/category/CategoryException.java
  backend/src/main/java/com/example/backend/domain/define/study/category/info/StudyCategory.java
  backend/src/main/java/com/example/backend/study/api/controller/category/info/CategoryController.java
  backend/src/main/java/com/example/backend/study/api/controller/category/info/request/CategoryUpdateRequest.java
  backend/src/main/java/com/example/backend/study/api/service/category/info/CategoryService.java
  backend/src/test/java/com/example/backend/study/api/controller/category/info/CategoryControllerTest.java
  backend/src/test/java/com/example/backend/study/api/service/category/info/CategoryServiceTest.java
Labels: feat, 구영민 진행중🔥

#210 [BE] feat(#209): 스터디 가입신청 목록 조회 api
  backend/src/main/java/com/example/backend/common/exception/ExceptionMessage.java
  backend/src/main/java/com/example/backend/domain/define/study/member/repository/StudyMemberRepositoryCustom.java
  backend/src/main/java/com/example/backend/domain/define/study/member/repository/StudyMemberRepositoryImpl.java
  backend/src/main/java/com/example/backend/study/api/controller/member/StudyMemberController.java
  backend/src/main/java/com/example/backend/study/api/controller/member/response/StudyMemberApplyListAndCursorIdxResponse.java
  backend/src/main/java/com/example/backend/study/api/controller/member/response/StudyMemberApplyResponse.java
  backend/src/main/java/com/example/backend/study/api/service/member/StudyMemberService.java
  backend/src/test/java/com/example/backend/auth/config/fixture/UserFixture.java
  backend/src/test/java/com/example/backend/study/api/controller/member/StudyMemberControllerTest.java
  backend/src/test/java/com/example/backend/study/api/service/member/StudyMemberServiceTest.java
Labels: feat, 이정우 진행중🔥

#212 [BE] feat(#211): Todo 단일 조회 api
  backend/src/main/java/com/example/backend/study/api/controller/todo/StudyTodoController.java
  backend/src/main/java/com/example/backend/study/api/controller/todo/response/StudyTodoResponse.java
  backend/src/main/java/com/example/backend/study/api/service/todo/StudyTodoService.java
  backend/src/test/java/com/example/backend/study/api/controller/todo/StudyTodoControllerTest.java
  backend/src/test/java/com/example/backend/study/api/service/todo/StudyTodoServiceTest.java
Labels: feat, 이정우 진행중🔥

#220 [BE] refactor(#219) 스웨거 오류 수정
  backend/src/main/java/com/example/backend/study/api/controller/info/StudyInfoController.java
Labels: refactor

#214 [BE] feat(#213): 닉네임 중복체크 api
  backend/src/main/java/com/example/backend/auth/api/controller/auth/AuthController.java
  backend/src/main/java/com/example/backend/auth/api/controller/auth/request/UserNameRequest.java
  backend/src/main/java/com/example/backend/auth/api/service/auth/AuthService.java
  backend/src/main/java/com/example/backend/common/exception/ExceptionMessage.java
  backend/src/main/java/com/example/backend/domain/define/account/user/repository/UserRepository.java
  backend/src/test/java/com/example/backend/auth/api/controller/auth/AuthControllerTest.java
  backend/src/test/java/com/example/backend/auth/api/service/auth/AuthServiceTest.java
  backend/src/test/java/com/example/backend/auth/config/fixture/UserFixture.java
Labels: feat, 이정우 진행중🔥

#216 [BE] feat(#215) 카테고리 리스트 조회 api 구현
  backend/src/main/java/com/example/backend/domain/define/study/category/info/repository/StudyCategoryRepositoryCustom.java
  backend/src/main/java/com/example/backend/domain/define/study/category/info/repository/StudyCategoryRepositoryImpl.java
  backend/src/main/java/com/example/backend/study/api/controller/category/info/CategoryController.java
  backend/src/main/java/com/example/backend/study/api/controller/category/info/response/CategoryListAndCursorIdxResponse.java
  backend/src/main/java/com/example/backend/study/api/service/category/info/CategoryService.java
  backend/src/main/java/com/example/backend/study/api/service/category/info/response/CategoryResponse.java
  backend/src/test/java/com/example/backend/domain/define/study/StudyCategory/info/StudyCategoryFixture.java
  backend/src/test/java/com/example/backend/domain/define/study/category/info/repository/StudyCategoryRepositoryTest.java
  backend/src/test/java/com/example/backend/study/api/controller/category/info/CategoryControllerTest.java
  backend/src/test/java/com/example/backend/study/api/service/category/info/CategoryServiceTest.java
Labels: feat, 구영민 진행중🔥

#223 [BE] refactor(#222): required = false 추가
  backend/src/main/java/com/example/backend/study/api/controller/bookmark/StudyBookmarkController.java
  backend/src/main/java/com/example/backend/study/api/controller/comment/study/StudyCommentController.java
  backend/src/main/java/com/example/backend/study/api/controller/commit/StudyCommitController.java
  backend/src/main/java/com/example/backend/study/api/controller/convention/StudyConventionController.java
  backend/src/main/java/com/example/backend/study/api/controller/member/StudyMemberController.java
  backend/src/main/java/com/example/backend/study/api/controller/todo/StudyTodoController.java
  backend/src/test/java/com/example/backend/study/api/controller/bookmark/StudyBookmarkControllerTest.java
  backend/src/test/java/com/example/backend/study/api/controller/comment/study/StudyCommentControllerTest.java
  backend/src/test/java/com/example/backend/study/api/controller/commit/StudyCommitControllerTest.java
  backend/src/test/java/com/example/backend/study/api/controller/convention/StudyConventionControllerTest.java
  backend/src/test/java/com/example/backend/study/api/controller/member/StudyMemberControllerTest.java
  backend/src/test/java/com/example/backend/study/api/controller/todo/StudyTodoControllerTest.java
Labels: refactor, 구영민 진행중🔥

#231 [AN] feat(#200): 하단바 네비게이션 구현 및 메인 카테고리 홈 화면 초기 화면 기능 구현
  android/gitudy/app/build.gradle.kts
  android/gitudy/app/google-services.json
  android/gitudy/build.gradle.kts
  android/gitudy/data/build.gradle.kts
  android/gitudy/data/src/main/java/com/takseha/data/api/gitudy/GitudyApi.kt
  android/gitudy/data/src/main/java/com/takseha/data/dto/auth/auth/UserInfoResponse.kt
  android/gitudy/data/src/main/java/com/takseha/data/dto/auth/login/LoginPageResponse.kt
  android/gitudy/data/src/main/java/com/takseha/data/dto/auth/register/RegisterRequest.kt
  android/gitudy/data/src/main/java/com/takseha/data/dto/study/StudyListResponse.kt
  android/gitudy/data/src/main/java/com/takseha/data/repository/GitudyRepository.kt
  android/gitudy/presentation/build.gradle.kts
  android/gitudy/presentation/src/main/java/com/takseha/presentation/adapter/RVAdapter.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/feed/FeedHomeFragment.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/home/MainHomeActivity.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/home/MainHomeFragment.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/login/RegisterCompleteFragment.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/mystudy/MyStudyHomeFragment.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/profile/ProfileHomeFragment.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/viewholder/MyStudyListViewHolder.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/viewmodel/LoginViewModel.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/viewmodel/MainHomeViewModel.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/viewmodel/ProfileHomeViewModel.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/viewmodel/RegisterViewModel.kt
  android/gitudy/presentation/src/main/res/anim/alpha_character.xml
  android/gitudy/presentation/src/main/res/drawable/gradient_main.xml
  android/gitudy/presentation/src/main/res/drawable/ic_alert_300.png
  android/gitudy/presentation/src/main/res/drawable/ic_navi_feed.png
  android/gitudy/presentation/src/main/res/drawable/ic_navi_feed_active.png
  android/gitudy/presentation/src/main/res/drawable/ic_navi_home.png
  android/gitudy/presentation/src/main/res/drawable/ic_navi_mystudy.png
  android/gitudy/presentation/src/main/res/drawable/ic_navi_profile.png
  android/gitudy/presentation/src/main/res/drawable/ic_plus_c_300.png
  android/gitudy/presentation/src/main/res/drawable/progress_bar.xml
  android/gitudy/presentation/src/main/res/drawable/progress_bar_c.xml
  android/gitudy/presentation/src/main/res/drawable/selector_nav_feed.xml
  android/gitudy/presentation/src/main/res/drawable/selector_nav_home.xml
  android/gitudy/presentation/src/main/res/drawable/selector_nav_mystudy.xml
  android/gitudy/presentation/src/main/res/drawable/selector_nav_profile.xml
  android/gitudy/presentation/src/main/res/drawable/square_r8_non_stroke.xml
  android/gitudy/presentation/src/main/res/layout/activity_main_home.xml
  android/gitudy/presentation/src/main/res/layout/activity_my_study_main.xml
  android/gitudy/presentation/src/main/res/layout/activity_splash.xml
  android/gitudy/presentation/src/main/res/layout/fragment_feed_home.xml
  android/gitudy/presentation/src/main/res/layout/fragment_main_home.xml
  android/gitudy/presentation/src/main/res/layout/fragment_my_study_home.xml
  android/gitudy/presentation/src/main/res/layout/fragment_profile_home.xml
  android/gitudy/presentation/src/main/res/layout/item_mystudy.xml
  android/gitudy/presentation/src/main/res/values/colors.xml
  android/gitudy/presentation/src/main/res/values/strings.xml
Labels: feat, 탁세하 진행중🔥

#236 [AN] chore(#232): firebase 세팅
  android/gitudy/.gitignore
  android/gitudy/app/.gitignore
  android/gitudy/app/build.gradle.kts
  android/gitudy/data/build.gradle.kts
  android/gitudy/data/src/main/AndroidManifest.xml
  android/gitudy/presentation/build.gradle.kts
  android/gitudy/presentation/src/main/java/com/takseha/presentation/firebase/MyFirebaseMessagingService.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/SplashActivity.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/login/SocialLoginCompleteActivity.kt
Labels: feat, 탁세하 진행중🔥

#234 [BE] feat(#233): 회원가입, 스터디생성, 스터디 가입 시 user 점수 로직 추가
  backend/src/main/java/com/example/backend/domain/define/account/user/User.java
  backend/src/main/java/com/example/backend/study/api/service/info/StudyInfoService.java
  backend/src/main/java/com/example/backend/study/api/service/member/StudyMemberService.java
  backend/src/test/java/com/example/backend/study/api/service/info/StudyInfoServiceTest.java
  backend/src/test/java/com/example/backend/study/api/service/member/StudyMemberServiceTest.java
Labels: feat, 구영민 진행중🔥

#230 [BE] setting(#229): FirebaseConfig 추가
  .github/workflows/CICD_dev_be_merge.yml
  .github/workflows/CI_dev_be_pull_request.yml
  backend/.gitignore
  backend/build.gradle
  backend/src/main/java/com/example/backend/domain/config/FirebaseConfig.java
Labels: chore, feat, 이정우 진행중🔥

#226 [BE] setting(#225): 이벤트 구조 세팅
  backend/src/main/java/com/example/backend/domain/define/study/member/listener/TestEventListener.java
  backend/src/main/java/com/example/backend/study/api/event/TestEvent.java
Labels: chore, feat

#239 [BE] refactor(#238) findbyid orthrow() 중복제거
  backend/src/main/java/com/example/backend/study/api/service/category/info/CategoryService.java
  backend/src/main/java/com/example/backend/study/api/service/comment/commit/CommitCommentService.java
  backend/src/main/java/com/example/backend/study/api/service/comment/study/StudyCommentService.java
  backend/src/main/java/com/example/backend/study/api/service/commit/StudyCommitService.java
  backend/src/main/java/com/example/backend/study/api/service/convention/StudyConventionService.java
  backend/src/main/java/com/example/backend/study/api/service/info/StudyInfoService.java
  backend/src/main/java/com/example/backend/study/api/service/member/StudyMemberService.java
  backend/src/main/java/com/example/backend/study/api/service/todo/StudyTodoService.java
Labels: refactor, 구영민 진행중🔥

#246 [BE] feat(#243): redis FCM token 저장 api 구현
  backend/src/main/java/com/example/backend/domain/define/fcmToken/FcmToken.java
  backend/src/main/java/com/example/backend/domain/define/fcmToken/repository/FcmTokenRepository.java
  backend/src/main/java/com/example/backend/study/api/event/controller/FcmController.java
  backend/src/main/java/com/example/backend/study/api/event/controller/request/FcmTokenSaveRequest.java
  backend/src/main/java/com/example/backend/study/api/event/service/FcmService.java
  backend/src/test/java/com/example/backend/domain/define/fcmToken/repository/FcmTokenRepositoryTest.java
  backend/src/test/java/com/example/backend/study/api/event/controller/FcmControllerTest.java
  backend/src/test/java/com/example/backend/study/api/event/service/FcmServiceTest.java
Labels: feat, 구영민 진행중🔥

#245 [BE] feat(#244): FCM 구현
  backend/src/main/java/com/example/backend/domain/config/FirebaseConfig.java
  backend/src/main/java/com/example/backend/study/api/event/FcmMultiTokenRequest.java
  backend/src/main/java/com/example/backend/study/api/event/FcmSingleTokenRequest.java
  backend/src/main/java/com/example/backend/study/api/event/controller/FcmController.java
  backend/src/main/java/com/example/backend/study/api/event/service/FcmService.java
  backend/src/test/java/com/example/backend/domain/define/event/FcmFixture.java
  backend/src/test/java/com/example/backend/study/api/event/controller/FcmControllerTest.java
  backend/src/test/java/com/example/backend/study/api/event/service/FcmServiceTest.java
Labels: feat, 이정우 진행중🔥

#259 refactor(#258): 회원가입 dto 수정
  backend/src/main/java/com/example/backend/auth/api/controller/auth/request/AuthRegisterRequest.java
  backend/src/main/java/com/example/backend/auth/api/service/auth/AuthService.java
  backend/src/main/java/com/example/backend/auth/api/service/auth/request/AuthServiceRegisterRequest.java
  backend/src/main/java/com/example/backend/domain/define/account/user/User.java
  backend/src/test/java/com/example/backend/auth/api/controller/auth/AuthControllerTest.java
  backend/src/test/java/com/example/backend/auth/api/service/auth/AuthServiceTest.java
Labels: refactor, 이주성 진행중🔥
