Repository DKU-Dgaja/gitudy, pull requests merged in 2024-08, with the labels that each got.

#473 [BE] feat(#472): 스터디 랭킹 시스템
  backend/src/main/java/com/example/backend/auth/api/service/rank/RankingService.java
  backend/src/main/java/com/example/backend/auth/api/service/rank/response/StudyRankingResponse.java
  backend/src/main/java/com/example/backend/domain/define/rank/StudyRanking.java
  backend/src/main/java/com/example/backend/study/api/controller/info/StudyInfoController.java
  backend/src/test/java/com/example/backend/auth/api/service/rank/RankingServiceTest.java
  backend/src/test/java/com/example/backend/domain/define/study/info/StudyInfoFixture.java
  backend/src/test/java/com/example/backend/study/api/controller/info/StudyInfoControllerTest.java
Labels: feat, 이정우 진행중🔥

#477 [AN] feat(#464): 마이스터디 방명록 구현
  android/gitudy/data/src/main/java/com/takseha/data/api/gitudy/study/GitudyStudyService.kt
  android/gitudy/data/src/main/java/com/takseha/data/dto/auth/auth/UserInfoResponse.kt
  android/gitudy/data/src/main/java/com/takseha/data/dto/auth/register/RegisterRequest.kt
  android/gitudy/data/src/main/java/com/takseha/data/dto/feed/MakeStudyRequest.kt
  android/gitudy/data/src/main/java/com/takseha/data/dto/mystudy/StudyCommentListResponse.kt
  android/gitudy/data/src/main/java/com/takseha/data/dto/mystudy/StudyInfoResponse.kt
  android/gitudy/data/src/main/java/com/takseha/data/repository/study/GitudyStudyRepository.kt
  android/gitudy/data/src/main/java/com/takseha/data/token/TokenInterceptor.kt
  android/gitudy/presentation/build.gradle.kts
  android/gitudy/presentation/src/main/AndroidManifest.xml
  android/gitudy/presentation/src/main/java/com/takseha/presentation/adapter/CommentListRVAdapter.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/firebase/MyFirebaseMessagingService.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/SplashActivity.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/auth/InputIdFragment.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/auth/SocialLoginCompleteActivity.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/feed/FeedHomeFragment.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/feed/MakeStudy3Fragment.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/feed/StudyApplyActivity.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/home/MainHomeFragment.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/mystudy/AddTodoActivity.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/mystudy/MyStudyHomeFragment.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/mystudy/MyStudyMainActivity.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/mystudy/StudyCommentBoardActivity.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/mystudy/ToDoFragment.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/viewmodel/auth/RegisterViewModel.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/viewmodel/feed/MakeStudyViewModel.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/viewmodel/feed/StudyApplyViewModel.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/viewmodel/home/MainHomeViewModel.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/viewmodel/mystudy/MyStudyMainViewModel.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/viewmodel/mystudy/TodoViewModel.kt
  android/gitudy/presentation/src/main/res/drawable/logo_profile_default.png
  android/gitudy/presentation/src/main/res/layout/activity_my_study_main.xml
  android/gitudy/presentation/src/main/res/layout/activity_study_comment_board.xml
  android/gitudy/presentation/src/main/res/layout/fragment_to_do.xml
  android/gitudy/presentation/src/main/res/layout/item_comment.xml
  android/gitudy/presentation/src/main/res/values/strings.xml
Labels: feat, 탁세하 진행중🔥

#480 Be 476 refactor 투두 도메인 리팩토링
  backend/src/main/java/com/example/backend/common/exception/ExceptionMessage.java
  backend/src/main/java/com/example/backend/domain/define/study/todo/info/StudyTodo.java
  backend/src/main/java/com/example/backend/domain/define/study/todo/repository/StudyTodoRepository.java
  backend/src/main/java/com/example/backend/study/api/controller/todo/response/StudyTodoResponse.java
  backend/src/main/java/com/example/backend/study/api/controller/todo/response/StudyTodoWithCommitsResponse.java
  backend/src/main/java/com/example/backend/study/api/service/github/GithubApiService.java
  backend/src/main/java/com/example/backend/study/api/service/todo/StudyTodoService.java
  backend/src/main/java/com/example/backend/webhook/api/controller/request/WebhookPayload.java
  backend/src/main/java/com/example/backend/webhook/api/service/WebhookService.java
  backend/src/test/java/com/example/backend/domain/define/study/info/StudyInfoFixture.java
  backend/src/test/java/com/example/backend/study/api/service/github/GithubApiServiceTest.java
  backend/src/test/java/com/example/backend/study/api/service/todo/StudyTodoServiceTest.java
  backend/src/test/java/com/example/backend/webhook/api/service/WebhookServiceTest.java
Labels: refactor, feat, 이주성 진행중🔥

#483 [BE] refactor(#482): 투두 진행률 조회 api 수정
  backend/src/main/java/com/example/backend/study/api/controller/todo/StudyTodoController.java
  backend/src/main/java/com/example/backend/study/api/controller/todo/response/StudyTodoProgressResponse.java
  backend/src/main/java/com/example/backend/study/api/service/member/StudyMemberService.java
  backend/src/main/java/com/example/backend/study/api/service/todo/StudyTodoService.java
  backend/src/main/java/com/example/backend/webhook/api/service/WebhookService.java
  backend/src/test/java/com/example/backend/domain/define/study/todo/StudyTodoFixture.java
  backend/src/test/java/com/example/backend/domain/define/study/todo/mapping/repository/StudyTodoMappingRepositoryTest.java
  backend/src/test/java/com/example/backend/domain/define/study/todo/repository/StudyTodoRepositoryTest.java
  backend/src/test/java/com/example/backend/study/api/controller/todo/StudyTodoControllerTest.java
  backend/src/test/java/com/example/backend/study/api/service/member/StudyMemberServiceTest.java
  backend/src/test/java/com/example/backend/study/api/service/todo/StudyTodoServiceTest.java
Labels: refactor, 이주성 진행중🔥

#484 [BE] refactor(#478) : DTO 수정
  backend/src/main/java/com/example/backend/domain/define/study/comment/commit/repository/CommitCommentRepositoryCustom.java
  backend/src/main/java/com/example/backend/domain/define/study/comment/commit/repository/CommitCommentRepositoryImpl.java
  backend/src/main/java/com/example/backend/domain/define/study/comment/study/repository/StudyCommentRepositoryCustom.java
  backend/src/main/java/com/example/backend/domain/define/study/comment/study/repository/StudyCommentRepositoryImpl.java
  backend/src/main/java/com/example/backend/study/api/controller/comment/commit/CommitCommentController.java
  backend/src/main/java/com/example/backend/study/api/controller/comment/commit/response/CommitCommentInfoResponse.java
  backend/src/main/java/com/example/backend/study/api/controller/comment/study/StudyCommentController.java
  backend/src/main/java/com/example/backend/study/api/controller/comment/study/response/StudyCommentResponse.java
  backend/src/main/java/com/example/backend/study/api/service/comment/commit/CommitCommentService.java
  backend/src/main/java/com/example/backend/study/api/service/comment/study/StudyCommentService.java
  backend/src/test/java/com/example/backend/auth/config/fixture/UserFixture.java
  backend/src/test/java/com/example/backend/domain/define/study/comment/StudyCommentFixture.java
  backend/src/test/java/com/example/backend/domain/define/study/comment/commit/repository/CommitCommentRepositoryTest.java
  backend/src/test/java/com/example/backend/domain/define/study/comment/study/repository/StudyCommentRepositoryTest.java
  backend/src/test/java/com/example/backend/study/api/controller/comment/commit/CommitCommentControllerTest.java
  backend/src/test/java/com/example/backend/study/api/controller/comment/study/StudyCommentControllerTest.java
  backend/src/test/java/com/example/backend/study/api/service/comment/commit/CommitCommentServiceTest.java
  backend/src/test/java/com/example/backend/study/api/service/comment/study/StudyCommentServiceTest.java
Labels: refactor, 구영민 진행중🔥

#487 [AN] feat(#481): 스터디 리스트 UI 및 기능 완성
  android/gitudy/data/src/main/java/com/takseha/data/api/gitudy/study/GitudyStudyService.kt
  android/gitudy/data/src/main/java/com/takseha/data/dto/feed/StudyCountResponse.kt
  android/gitudy/data/src/main/java/com/takseha/data/dto/feed/StudyListResponse.kt
  android/gitudy/data/src/main/java/com/takseha/data/dto/mystudy/MyStudyWithTodo.kt
  android/gitudy/data/src/main/java/com/takseha/data/repository/study/GitudyStudyRepository.kt
  android/gitudy/data/src/main/java/com/takseha/data/token/TokenInterceptor.kt
  android/gitudy/data/src/main/java/com/takseha/data/token/TokenManager.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/adapter/CommitListRVAdapter.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/adapter/FeedCategoryRVAdapter.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/adapter/FeedRVAdapter.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/adapter/MemberListRVAdapter.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/adapter/MyStudyRVAdapter.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/adapter/ToDoListRVAdapter.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/feed/FeedHomeFragment.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/home/MainHomeFragment.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/mystudy/MyStudyHomeFragment.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/mystudy/ToDoFragment.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/viewmodel/feed/FeedHomeViewModel.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/viewmodel/home/MainHomeViewModel.kt
  android/gitudy/presentation/src/main/res/drawable/ic_member_list_empty.png
  android/gitudy/presentation/src/main/res/layout/fragment_feed_home.xml
  android/gitudy/presentation/src/main/res/layout/fragment_my_study_home.xml
  android/gitudy/presentation/src/main/res/layout/item_category.xml
  android/gitudy/presentation/src/main/res/layout/item_feed.xml
  android/gitudy/presentation/src/main/res/layout/item_member_in_study_list.xml
  android/gitudy/presentation/src/main/res/layout/item_mystudy.xml
Labels: feat, 탁세하 진행중🔥

#486 [BE] feat(#485): 카테고리 전체 조회 api 구현
  backend/src/main/java/com/example/backend/study/api/controller/category/info/CategoryController.java
  backend/src/main/java/com/example/backend/study/api/service/category/info/CategoryService.java
  backend/src/main/java/com/example/backend/study/api/service/category/info/response/CategoryResponse.java
  backend/src/main/java/com/example/backend/study/api/service/todo/StudyTodoService.java
  backend/src/main/java/com/example/backend/webhook/api/service/WebhookService.java
  backend/src/test/java/com/example/backend/study/api/controller/category/info/CategoryControllerTest.java
  backend/src/test/java/com/example/backend/study/api/service/category/info/CategoryServiceTest.java
  backend/src/test/java/com/example/backend/study/api/service/todo/StudyTodoServiceTest.java
  backend/src/test/java/com/example/backend/webhook/api/service/WebhookServiceTest.java
Labels: feat, 이주성 진행중🔥

#490 [BE] refactor(#489) 스터디 멤버 조회 반환 수정
  backend/src/main/java/com/example/backend/domain/define/study/member/repository/StudyMemberRepositoryImpl.java
  backend/src/main/java/com/example/backend/study/api/controller/member/response/StudyMembersResponse.java
  backend/src/test/java/com/example/backend/study/api/service/member/StudyMemberServiceTest.java
Labels: refactor, 구영민 진행중🔥

#491 [AN] refactor(#488): 마이스터디 별 Todo 관련 및 스터디 방명록 관련 기능 수정
  android/gitudy/app/build.gradle.kts
  android/gitudy/app/src/main/java/com/takseha/gitudy/GitudyApplication.kt
  android/gitudy/data/build.gradle.kts
  android/gitudy/data/src/main/java/com/takseha/data/dto/mystudy/DetailUserInfo.kt
  android/gitudy/data/src/main/java/com/takseha/data/dto/mystudy/MyStudyWithTodo.kt
  android/gitudy/data/src/main/java/com/takseha/data/dto/mystudy/StudyCommentListResponse.kt
  android/gitudy/data/src/main/java/com/takseha/data/dto/mystudy/StudyMemberListResponse.kt
  android/gitudy/data/src/main/java/com/takseha/data/dto/mystudy/Todo.kt
  android/gitudy/data/src/main/java/com/takseha/data/dto/mystudy/TodoListResponse.kt
  android/gitudy/data/src/main/java/com/takseha/data/dto/mystudy/TodoProgressResponse.kt
  android/gitudy/presentation/build.gradle.kts
  android/gitudy/presentation/src/main/java/com/takseha/presentation/adapter/CommentListRVAdapter.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/adapter/MemberRankRVAdapter.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/adapter/MyStudyRVAdapter.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/adapter/ToDoListRVAdapter.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/home/MainHomeFragment.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/mystudy/MyStudyHomeFragment.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/mystudy/MyStudyMainActivity.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/viewmodel/home/MainHomeViewModel.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/viewmodel/mystudy/MyStudyMainViewModel.kt
  android/gitudy/presentation/src/main/res/layout/activity_my_study_main.xml
  android/gitudy/presentation/src/main/res/layout/item_comment.xml
  android/gitudy/presentation/src/main/res/layout/item_todo.xml
Labels: refactor, 탁세하 진행중🔥

#494 [AN] refactor(#492): 스터디 개설 과정 전체 수정
  android/gitudy/data/src/main/java/com/takseha/data/api/gitudy/auth/GitudyAuthService.kt
  android/gitudy/data/src/main/java/com/takseha/data/api/gitudy/category/GitudyCategoryService.kt
  android/gitudy/data/src/main/java/com/takseha/data/api/gitudy/study/GitudyStudyService.kt
  android/gitudy/data/src/main/java/com/takseha/data/dto/feed/CategoryListResponse.kt
  android/gitudy/data/src/main/java/com/takseha/data/dto/feed/CheckRepoNameRequest.kt
  android/gitudy/data/src/main/java/com/takseha/data/repository/auth/GitudyAuthRepository.kt
  android/gitudy/data/src/main/java/com/takseha/data/repository/category/GitudyCategoryRepository.kt
  android/gitudy/data/src/main/java/com/takseha/data/repository/study/GitudyStudyRepository.kt
  android/gitudy/data/src/main/java/com/takseha/data/token/TokenManager.kt
  android/gitudy/presentation/src/main/AndroidManifest.xml
  android/gitudy/presentation/src/main/java/com/takseha/presentation/adapter/AllCategoryRVAdapter.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/adapter/CommentListRVAdapter.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/adapter/DetailCommentListRVAdapter.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/adapter/FeedCategoryRVAdapter.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/adapter/ToDoListRVAdapter.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/feed/MakeStudy1Fragment.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/mystudy/MyStudyMainActivity.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/mystudy/StudyCommentBoardActivity.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/viewmodel/feed/MakeStudyViewModel.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/viewmodel/mystudy/MyStudyMainViewModel.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/viewmodel/mystudy/StudyCommentBoardViewModel.kt
  android/gitudy/presentation/src/main/res/drawable/ic_heart.png
  android/gitudy/presentation/src/main/res/drawable/ic_thumbs_up.png
  android/gitudy/presentation/src/main/res/layout/activity_study_comment_board.xml
  android/gitudy/presentation/src/main/res/layout/fragment_make_study1.xml
  android/gitudy/presentation/src/main/res/layout/item_category_all.xml
  android/gitudy/presentation/src/main/res/layout/item_comment.xml
  android/gitudy/presentation/src/main/res/layout/item_comment_detail.xml
  android/gitudy/presentation/src/main/res/menu/delete_menu.xml
  android/gitudy/presentation/src/main/res/menu/update_delete_menu.xml
  android/gitudy/presentation/src/main/res/values/strings.xml
Labels: refactor, 탁세하 진행중🔥

#497 [BE] fix(#496): 깃허브 토큰 저장 에러 수정
  backend/src/main/java/com/example/backend/auth/api/service/auth/AuthService.java
  backend/src/main/java/com/example/backend/auth/api/service/oauth/OAuthService.java
  backend/src/main/java/com/example/backend/domain/define/study/comment/study/repository/StudyCommentRepositoryImpl.java
  backend/src/main/java/com/example/backend/study/api/controller/comment/study/response/StudyCommentResponse.java
  backend/src/test/java/com/example/backend/domain/define/study/comment/StudyCommentFixture.java
  backend/src/test/java/com/example/backend/study/api/controller/comment/commit/CommitCommentControllerTest.java
  backend/src/test/java/com/example/backend/study/api/service/github/GithubApiServiceTest.java
Labels: fix, 이주성 진행중🔥

#498 [BE] refactor(#493): 점수 로직 추가
  backend/src/main/java/com/example/backend/auth/api/service/auth/AuthService.java
  backend/src/main/java/com/example/backend/auth/api/service/rank/RankingService.java
  backend/src/main/java/com/example/backend/auth/api/service/rank/event/StudyScoreSaveEvent.java
  backend/src/main/java/com/example/backend/auth/api/service/rank/event/StudyScoreUpdateEvent.java
  backend/src/main/java/com/example/backend/auth/api/service/rank/event/UserScoreSaveEvent.java
  backend/src/main/java/com/example/backend/auth/api/service/rank/event/UserScoreUpdateEvent.java
  backend/src/main/java/com/example/backend/domain/define/rank/listener/StudyScoreSaveListener.java
  backend/src/main/java/com/example/backend/domain/define/rank/listener/StudyScoreUpdateListener.java
  backend/src/main/java/com/example/backend/domain/define/rank/listener/UserScoreSaveListener.java
  backend/src/main/java/com/example/backend/domain/define/rank/listener/UserScoreUpdateListener.java
  backend/src/main/java/com/example/backend/domain/define/study/info/StudyInfo.java
  backend/src/main/java/com/example/backend/domain/define/study/member/StudyMember.java
  backend/src/main/java/com/example/backend/study/api/controller/comment/commit/request/AddCommitCommentRequest.java
  backend/src/main/java/com/example/backend/study/api/service/comment/commit/CommitCommentService.java
  backend/src/main/java/com/example/backend/study/api/service/commit/StudyCommitService.java
  backend/src/main/java/com/example/backend/study/api/service/info/StudyInfoService.java
  backend/src/main/java/com/example/backend/study/api/service/member/StudyMemberService.java
  backend/src/test/java/com/example/backend/study/api/service/comment/commit/CommitCommentServiceTest.java
  backend/src/test/java/com/example/backend/study/api/service/commit/StudyCommitServiceTest.java
Labels: refactor, feat, 이정우 진행중🔥

#500 [BE] feat(#499): actuator & prometheus 의존성 추가 및 시큐리티 설정
  backend/build.gradle
  backend/src/main/java/com/example/backend/auth/config/security/SecurityConfig.java
Labels: feat, 이주성 진행중🔥

#503 [BE] refactor(#502): 이제는 필요 없는 투두 코드 잔여물 삭제
  backend/src/main/java/com/example/backend/domain/define/study/commit/repository/StudyCommitRepositoryCustom.java
  backend/src/main/java/com/example/backend/domain/define/study/commit/repository/StudyCommitRepositoryImpl.java
  backend/src/main/java/com/example/backend/domain/define/study/todo/info/StudyTodo.java
  backend/src/test/java/com/example/backend/study/api/service/todo/StudyTodoServiceTest.java
Labels: refactor, 이주성 진행중🔥

#507 [BE] refactor(#506): 알림 메시지 형식 수정 + 커밋 승인/거부 로직 수정
  backend/src/main/java/com/example/backend/domain/define/fcm/listener/CommitApproveListener.java
  backend/src/main/java/com/example/backend/domain/define/fcm/listener/CommitRefuseListener.java
  backend/src/main/java/com/example/backend/domain/define/fcm/listener/StudyApplyApproveRefuseListener.java
  backend/src/main/java/com/example/backend/domain/define/fcm/listener/StudyApplyListener.java
  backend/src/main/java/com/example/backend/domain/define/fcm/listener/TodoRegisterListener.java
  backend/src/main/java/com/example/backend/domain/define/fcm/listener/TodoUpdateListener.java
  backend/src/main/java/com/example/backend/domain/define/study/commit/event/CommitApproveEvent.java
  backend/src/main/java/com/example/backend/domain/define/study/commit/event/CommitRefuseEvent.java
  backend/src/main/java/com/example/backend/study/api/event/service/NoticeService.java
  backend/src/main/java/com/example/backend/study/api/service/commit/StudyCommitService.java
  backend/src/test/java/com/example/backend/domain/define/fcm/listener/ApplyApproveRefuseMemberListenerTest.java
  backend/src/test/java/com/example/backend/domain/define/fcm/listener/ApplyMemberListenerTest.java
  backend/src/test/java/com/example/backend/domain/define/fcm/listener/TodoRegisterMemberListenerTest.java
  backend/src/test/java/com/example/backend/domain/define/fcm/listener/TodoUpdateMemberListenerTest.java
  backend/src/test/java/com/example/backend/study/api/service/commit/StudyCommitServiceTest.java
  backend/src/test/java/com/example/backend/study/api/service/member/StudyMemberServiceTest.java
  backend/src/test/java/com/example/backend/study/api/service/todo/StudyTodoServiceTest.java
Labels: refactor, feat

#509 [BE] refactor(#508): 알림 전체 목록 api 필드 추가
  backend/src/main/java/com/example/backend/domain/define/study/info/event/ApplyApproveRefuseMemberEvent.java
  backend/src/main/java/com/example/backend/domain/define/study/member/event/NotifyLeaderEvent.java
  backend/src/main/java/com/example/backend/domain/define/study/member/event/NotifyMemberEvent.java
  backend/src/main/java/com/example/backend/domain/define/study/member/event/ResignMemberEvent.java
  backend/src/main/java/com/example/backend/domain/define/study/member/event/WithdrawalMemberEvent.java
  backend/src/main/java/com/example/backend/domain/define/study/todo/event/TodoRegisterMemberEvent.java
  backend/src/main/java/com/example/backend/domain/define/study/todo/event/TodoUpdateMemberEvent.java
  backend/src/main/java/com/example/backend/study/api/event/service/NoticeService.java
  backend/src/main/java/com/example/backend/study/api/service/member/StudyMemberService.java
  backend/src/main/java/com/example/backend/study/api/service/todo/StudyTodoService.java
Labels: refactor, 이정우 진행중🔥

#513 [BE] refactor(#511): 프로필 공개여부 추가
  backend/src/main/java/com/example/backend/domain/define/study/member/repository/StudyMemberRepositoryImpl.java
  backend/src/main/java/com/example/backend/study/api/controller/member/response/StudyMemberApplyResponse.java
Labels: refactor, 이정우 진행중🔥

#512 [BE] refactor(#510) 스터디 가입 신청 로직 관련 이슈 수정
  backend/src/main/java/com/example/backend/domain/define/study/info/repository/StudyInfoRepositoryImpl.java
  backend/src/main/java/com/example/backend/study/api/controller/info/response/StudyInfoDetailResponse.java
  backend/src/main/java/com/example/backend/study/api/service/info/StudyInfoService.java
Labels: refactor, 구영민 진행중🔥

#514 [BE] fix(#510): 재사용 함수 수정
  backend/src/main/java/com/example/backend/study/api/service/info/StudyInfoService.java
Labels: fix, 구영민 진행중🔥

#515 [BE] refactor(#510): 스터디 개수 조회 쿼리 수정
  backend/src/main/java/com/example/backend/domain/define/study/info/repository/StudyInfoRepositoryImpl.java
Labels: refactor, 구영민 진행중🔥

#517 [BE] refactor(#516): 스터디 가입 목록 조회 필드 수정
  backend/src/main/java/com/example/backend/domain/define/study/member/repository/StudyMemberRepositoryImpl.java
  backend/src/main/java/com/example/backend/study/api/controller/member/response/StudyMemberApplyListAndCursorIdxResponse.java
  backend/src/main/java/com/example/backend/study/api/controller/member/response/StudyMemberApplyResponse.java
  backend/src/main/java/com/example/backend/study/api/service/member/StudyMemberService.java
Labels: refactor, 이정우 진행중🔥

#522 [AN] feat(#505): 스터디 가입 승인/거절 로직 구현
  android/gitudy/data/src/main/java/com/takseha/data/api/gitudy/GitudyMemberService.kt
  android/gitudy/data/src/main/java/com/takseha/data/dto/mystudy/SocialInfo.kt
  android/gitudy/data/src/main/java/com/takseha/data/dto/mystudy/StudyApplyMemberListResponse.kt
  android/gitudy/data/src/main/java/com/takseha/data/dto/mystudy/StudyInfoResponse.kt
  android/gitudy/data/src/main/java/com/takseha/data/repository/gitudy/GitudyMemberRepository.kt
  android/gitudy/data/src/main/java/com/takseha/data/token/TokenInterceptor.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/adapter/StudyApplyMemberListRVAdapter.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/SplashActivity.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/feed/FeedHomeFragment.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/feed/StudyApplyInfoFragment.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/feed/StudyApplyMessageFragment.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/home/MainHomeAlertActivity.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/home/MainHomeAlertFragment.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/mystudy/MyStudyMainActivity.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/mystudy/StudyApplyMemberListFragment.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/mystudy/StudyApplyMemberProfileFragment.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/mystudy/StudyCommentBoardActivity.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/mystudy/ToDoFragment.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/viewmodel/feed/FeedHomeViewModel.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/viewmodel/feed/StudyApplyViewModel.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/viewmodel/home/MainHomeAlertViewModel.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/viewmodel/mystudy/AddTodoViewModel.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/viewmodel/mystudy/StudyApplyMemberListViewModel.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/viewmodel/mystudy/StudyApplyMemberProfileViewModel.kt
  android/gitudy/presentation/src/main/res/drawable/ic_arrow_down_black.png
  android/gitudy/presentation/src/main/res/layout/activity_main_home_alert.xml
  android/gitudy/presentation/src/main/res/layout/activity_my_study_main.xml
  android/gitudy/presentation/src/main/res/layout/activity_study_comment_board.xml
  android/gitudy/presentation/src/main/res/layout/fragment_main_home_alert.xml
  android/gitudy/presentation/src/main/res/layout/fragment_my_study_home.xml
  android/gitudy/presentation/src/main/res/layout/fragment_study_apply_member_list.xml
  android/gitudy/presentation/src/main/res/layout/fragment_study_apply_member_profile.xml
  android/gitudy/presentation/src/main/res/layout/fragment_study_apply_message.xml
  android/gitudy/presentation/src/main/res/layout/item_apply_member.xml
  android/gitudy/presentation/src/main/res/navigation/main_home_alert_nav.xml
  android/gitudy/presentation/src/main/res/values/colors.xml
  android/gitudy/presentation/src/main/res/values/strings.xml
Labels: feat, 탁세하 진행중🔥

#521 [BE] fix(#520): content-type-오류-수정
  backend/src/main/java/com/example/backend/study/api/service/github/GithubApiService.java
Labels: fix, 구영민 진행중🔥

#530 [BE] feat(#529) is my bookmark api 구현
  backend/src/main/java/com/example/backend/study/api/controller/bookmark/StudyBookmarkController.java
  backend/src/main/java/com/example/backend/study/api/controller/bookmark/response/IsMyBookmarkResponse.java
  backend/src/main/java/com/example/backend/study/api/service/bookmark/StudyBookmarkService.java
  backend/src/test/java/com/example/backend/domain/define/account/bookmark/StudyBookmarkFixture.java
  backend/src/test/java/com/example/backend/study/api/controller/bookmark/StudyBookmarkControllerTest.java
  backend/src/test/java/com/example/backend/study/api/service/bookmark/StudyBookmarkServiceTest.java
Labels: feat, 구영민 진행중🔥

#531 [AN] feat(#528): 회원정보 수정 및 조회 기능 구현
  android/gitudy/data/src/main/java/com/takseha/data/api/gitudy/GitudyAuthService.kt
  android/gitudy/data/src/main/java/com/takseha/data/dto/auth/auth/UserInfoUpdatePageResponse.kt
  android/gitudy/data/src/main/java/com/takseha/data/dto/auth/auth/UserInfoUpdateRequest.kt
  android/gitudy/data/src/main/java/com/takseha/data/dto/auth/register/CheckNicknameRequest.kt
  android/gitudy/data/src/main/java/com/takseha/data/dto/mystudy/SocialInfo.kt
  android/gitudy/data/src/main/java/com/takseha/data/repository/gitudy/GitudyAuthRepository.kt
  android/gitudy/presentation/src/main/AndroidManifest.xml
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/auth/InputNicknameFragment.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/mystudy/MyStudyMainActivity.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/profile/ProfileEditActivity.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/profile/ProfileHomeFragment.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/viewmodel/auth/RegisterViewModel.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/viewmodel/mystudy/AddTodoViewModel.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/viewmodel/profile/ProfileEditViewModel.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/viewmodel/profile/ProfileHomeViewModel.kt
  android/gitudy/presentation/src/main/res/drawable/box_non_stroke_r85.xml
  android/gitudy/presentation/src/main/res/drawable/box_non_stroke_r85_black.xml
  android/gitudy/presentation/src/main/res/drawable/box_stroke_200_r85.xml
  android/gitudy/presentation/src/main/res/drawable/selector_btn_r85_enable.xml
  android/gitudy/presentation/src/main/res/drawable/selector_btn_stroke_r12_focused.xml
  android/gitudy/presentation/src/main/res/drawable/selector_switch.xml
  android/gitudy/presentation/src/main/res/drawable/selector_text_color_enable_white.xml
  android/gitudy/presentation/src/main/res/drawable/switch_track_off.xml
  android/gitudy/presentation/src/main/res/layout/activity_commit_convention.xml
  android/gitudy/presentation/src/main/res/layout/activity_profile_edit.xml
  android/gitudy/presentation/src/main/res/layout/fragment_make_study1.xml
  android/gitudy/presentation/src/main/res/layout/fragment_study_apply_message.xml
  android/gitudy/presentation/src/main/res/layout/fragment_update_todo.xml
  android/gitudy/presentation/src/main/res/values/strings.xml
Labels: feat, 탁세하 진행중🔥

#527 [BE] refactor(#524): 스터디 가입신청 목록 반환 수정
  backend/src/main/java/com/example/backend/common/exception/ExceptionMessage.java
  backend/src/main/java/com/example/backend/study/api/service/member/StudyMemberService.java
  backend/src/test/java/com/example/backend/study/api/service/member/StudyMemberServiceTest.java
Labels: refactor, 이정우 진행중🔥

#534 [BE] refactor(#533): 알림 이모지 테스트
  backend/src/main/java/com/example/backend/domain/define/fcm/listener/StudyApplyApproveRefuseListener.java
  backend/src/main/java/com/example/backend/study/api/event/service/NoticeService.java
Labels: refactor, 이정우 진행중🔥

#536 [BE] fix(#535): 깃허브 토큰을 찾을 수 없는 에러 발생
  backend/src/main/java/com/example/backend/auth/config/security/filter/JwtAuthenticationFilter.java
  backend/src/main/java/com/example/backend/study/api/service/github/GithubApiService.java
  backend/src/main/java/com/example/backend/study/api/service/info/StudyInfoService.java
Labels: fix, 이주성 진행중🔥

#540 [AN] feat(#532): 로그아웃 및 회원 탈퇴 기능 구현
  android/gitudy/data/src/main/java/com/takseha/data/api/gitudy/GitudyAuthService.kt
  android/gitudy/data/src/main/java/com/takseha/data/repository/gitudy/GitudyAuthRepository.kt
  android/gitudy/data/src/main/java/com/takseha/data/token/TokenManager.kt
  android/gitudy/presentation/src/main/AndroidManifest.xml
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/common/CustomCheckDialog.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/common/CustomSetDialog.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/feed/StudyApplyInfoFragment.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/feed/StudyApplyMessageFragment.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/mystudy/AddTodoActivity.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/mystudy/StudyApplyMemberProfileFragment.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/mystudy/StudyCommentBoardActivity.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/mystudy/ToDoFragment.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/mystudy/UpdateTodoFragment.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/profile/CustomerServiceFragment.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/profile/DeleteAccountCompleteFragment.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/profile/DeleteAccountFragment.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/profile/LogoutCompleteFragment.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/profile/ProfileEditActivity.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/profile/ProfileHomeFragment.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/profile/SettingActivity.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/profile/SettingHomeFragment.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/viewmodel/profile/ProfileEditViewModel.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/viewmodel/profile/ProfileHomeViewModel.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/viewmodel/profile/SettingHomeViewModel.kt
  android/gitudy/presentation/src/main/res/drawable/custom_radio_button_checked.xml
  android/gitudy/presentation/src/main/res/drawable/custom_radio_button_unchecked.xml
  android/gitudy/presentation/src/main/res/drawable/ic_radio_off.png
  android/gitudy/presentation/src/main/res/drawable/ic_radio_on.png
  android/gitudy/presentation/src/main/res/drawable/selector_radio_checked.xml
  android/gitudy/presentation/src/main/res/layout/activity_profile_edit.xml
  android/gitudy/presentation/src/main/res/layout/activity_setting.xml
  android/gitudy/presentation/src/main/res/layout/fragment_customer_service.xml
  android/gitudy/presentation/src/main/res/layout/fragment_delete_account.xml
  android/gitudy/presentation/src/main/res/layout/fragment_delete_account_complete.xml
  android/gitudy/presentation/src/main/res/layout/fragment_logout_complete.xml
  android/gitudy/presentation/src/main/res/layout/fragment_profile_home.xml
  android/gitudy/presentation/src/main/res/layout/fragment_setting_home.xml
  android/gitudy/presentation/src/main/res/layout/layout_dialog_check.xml
  android/gitudy/presentation/src/main/res/layout/layout_dialog_set.xml
  android/gitudy/presentation/src/main/res/navigation/setting_nav.xml
  android/gitudy/presentation/src/main/res/values/strings.xml
Labels: feat, 탁세하 진행중🔥

#538 [BE] fix(#537) 회원 정보 수정 update 검증 수정
  backend/src/main/java/com/example/backend/auth/api/controller/auth/request/UserUpdateRequest.java
  backend/src/main/java/com/example/backend/common/validation/SocialInfoValidator.java
  backend/src/main/java/com/example/backend/common/validation/ValidSocialInfo.java
  backend/src/test/java/com/example/backend/auth/api/controller/auth/AuthControllerTest.java
Labels: fix, 구영민 진행중🔥

#546 [AN] feat(#525): 스터디 북마크 등록/삭제/조회 기능 구현
  android/gitudy/data/src/main/java/com/takseha/data/api/gitudy/GitudyBookmarksService.kt
  android/gitudy/data/src/main/java/com/takseha/data/dto/profile/BookmarkCheckResponse.kt
  android/gitudy/data/src/main/java/com/takseha/data/dto/profile/BookmarksResponse.kt
  android/gitudy/data/src/main/java/com/takseha/data/repository/gitudy/GitudyBookmarksRepository.kt
  android/gitudy/presentation/src/main/AndroidManifest.xml
  android/gitudy/presentation/src/main/java/com/takseha/presentation/adapter/BookmarkListRVAdapter.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/adapter/FeedRVAdapter.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/feed/FeedHomeFragment.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/profile/BookmarksActivity.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/viewmodel/feed/FeedHomeViewModel.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/viewmodel/mystudy/BooktmarksViewModel.kt
  android/gitudy/presentation/src/main/res/drawable/ic_feed_save_green.png
  android/gitudy/presentation/src/main/res/layout/activity_bookmarks.xml
  android/gitudy/presentation/src/main/res/layout/item_bookmark.xml
  android/gitudy/presentation/src/main/res/layout/item_feed.xml
Labels: feat, 탁세하 진행중🔥

#548 [BE] refactor(#542) webhook 처리 로직 수정
  backend/src/main/java/com/example/backend/domain/define/study/commit/StudyCommit.java
  backend/src/main/java/com/example/backend/domain/define/study/commit/repository/StudyCommitRepository.java
  backend/src/main/java/com/example/backend/webhook/api/controller/request/CommitPayload.java
  backend/src/main/java/com/example/backend/webhook/api/controller/request/WebhookPayload.java
  backend/src/main/java/com/example/backend/webhook/api/service/WebhookService.java
  backend/src/test/java/com/example/backend/domain/define/study/commit/StudyCommitFixture.java
  backend/src/test/java/com/example/backend/domain/define/study/todo/StudyTodoFixture.java
  backend/src/test/java/com/example/backend/webhook/api/service/WebhookServiceTest.java
Labels: refactor, 이주성 진행중🔥

#550 [BE] fix(#549): 깃허브 토큰을 못 찾는 에러의 원인을 찾기 위한 로그 심기
  backend/src/main/java/com/example/backend/auth/api/service/auth/AuthService.java
  backend/src/main/java/com/example/backend/domain/define/study/commit/repository/StudyCommitRepository.java
  backend/src/main/java/com/example/backend/domain/define/study/info/repository/StudyInfoRepositoryImpl.java
  backend/src/main/java/com/example/backend/study/api/controller/bookmark/StudyBookmarkController.java
  backend/src/main/java/com/example/backend/study/api/service/github/GithubApiService.java
  backend/src/main/java/com/example/backend/study/api/service/github/GithubApiTokenService.java
  backend/src/main/java/com/example/backend/study/api/service/info/StudyInfoService.java
  backend/src/main/java/com/example/backend/study/api/service/member/StudyMemberService.java
  backend/src/main/java/com/example/backend/study/api/service/todo/StudyTodoService.java
  backend/src/main/java/com/example/backend/webhook/api/controller/request/WebhookPayload.java
  backend/src/main/java/com/example/backend/webhook/api/service/WebhookService.java
  backend/src/test/java/com/example/backend/auth/api/controller/auth/AuthControllerTest.java
  backend/src/test/java/com/example/backend/study/api/controller/bookmark/StudyBookmarkControllerTest.java
  backend/src/test/java/com/example/backend/study/api/controller/category/info/CategoryControllerTest.java
  backend/src/test/java/com/example/backend/study/api/controller/comment/commit/CommitCommentControllerTest.java
  backend/src/test/java/com/example/backend/study/api/controller/comment/study/StudyCommentControllerTest.java
  backend/src/test/java/com/example/backend/study/api/controller/commit/StudyCommitControllerTest.java
  backend/src/test/java/com/example/backend/study/api/controller/convention/StudyConventionControllerTest.java
  backend/src/test/java/com/example/backend/study/api/controller/info/StudyInfoControllerTest.java
  backend/src/test/java/com/example/backend/study/api/controller/member/StudyMemberControllerTest.java
  backend/src/test/java/com/example/backend/study/api/controller/todo/StudyTodoControllerTest.java
  backend/src/test/java/com/example/backend/study/api/event/controller/FcmControllerTest.java
  backend/src/test/java/com/example/backend/study/api/event/controller/NoticeControllerTest.java
  backend/src/test/java/com/example/backend/webhook/api/controller/WebhookControllerTest.java
Labels: fix, 이주성 진행중🔥

#551 [AN] feat(#547): 스터디 랭킹 구현
  android/gitudy/data/src/main/java/com/takseha/data/api/gitudy/GitudyStudyService.kt
  android/gitudy/data/src/main/java/com/takseha/data/dto/feed/StudyRankResponse.kt
  android/gitudy/data/src/main/java/com/takseha/data/repository/gitudy/GitudyStudyRepository.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/adapter/BookmarkListRVAdapter.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/adapter/FeedRVAdapter.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/adapter/MemberRankRVAdapter.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/feed/FeedHomeFragment.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/feed/StudyApplyInfoFragment.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/feed/StudyApplyMessageFragment.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/home/MainHomeFragment.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/mystudy/MyStudyMainActivity.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/profile/BookmarksActivity.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/profile/ProfileHomeFragment.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/viewmodel/feed/FeedHomeViewModel.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/viewmodel/feed/StudyApplyViewModel.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/viewmodel/mystudy/BooktmarksViewModel.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/viewmodel/mystudy/MyStudyMainViewModel.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/viewmodel/profile/ProfileHomeViewModel.kt
  android/gitudy/presentation/src/main/res/layout/fragment_make_study2.xml
  android/gitudy/presentation/src/main/res/layout/fragment_profile_home.xml
  android/gitudy/presentation/src/main/res/layout/fragment_quit_study.xml
  android/gitudy/presentation/src/main/res/layout/fragment_study_apply_info.xml
  android/gitudy/presentation/src/main/res/values/strings.xml
Labels: feat, 탁세하 진행중🔥

#545 [BE] refactor(#544): 유저 탈퇴 이유 필드 추가
  backend/src/main/java/com/example/backend/auth/api/controller/auth/AuthController.java
  backend/src/main/java/com/example/backend/auth/api/service/auth/AuthService.java
  backend/src/main/java/com/example/backend/domain/define/account/user/User.java
  backend/src/main/java/com/example/backend/study/api/controller/member/request/MessageRequest.java
  backend/src/test/java/com/example/backend/auth/api/controller/auth/AuthControllerTest.java
  backend/src/test/java/com/example/backend/auth/api/service/auth/AuthServiceTest.java
  backend/src/test/java/com/example/backend/auth/api/service/rank/RankingServiceTest.java
  backend/src/test/java/com/example/backend/domain/define/fcm/repository/FcmTokenRepositoryTest.java
Labels: refactor, 이정우 진행중🔥

#555 refact: webhook payload
  webhooks/src/main/kotlin/site/gitudy/webhooks/domain/webhook/WebhookService.kt
  webhooks/src/main/kotlin/site/gitudy/webhooks/infrastructure/gitudy/dto/WebhookCommitRequest.kt
Labels: refactor

#556 [BE] refactor(#539): fcmToken 저장오류
  backend/src/main/java/com/example/backend/auth/api/service/auth/AuthService.java
Labels: refactor, 이정우 진행중🔥

#558 [BE] refactor(#557): 백엔드 호출 url 수정
  webhooks/src/main/kotlin/site/gitudy/webhooks/infrastructure/gitudy/WebhookClient.kt
Labels: refactor, 이주성 진행중🔥

#560 [BE] refactor(#559): 투두 폴더 생성 커밋까지 등록되는 문제 해결
  backend/src/main/java/com/example/backend/auth/config/security/filter/JwtAuthenticationFilter.java
  backend/src/main/java/com/example/backend/webhook/api/service/WebhookService.java
  backend/src/test/java/com/example/backend/webhook/api/service/WebhookServiceTest.java
Labels: refactor, 이주성 진행중🔥

#565 [BE] refactor(#562): 커밋 리스트 필드 추가
  backend/src/main/java/com/example/backend/domain/define/study/commit/repository/StudyCommitRepositoryImpl.java
  backend/src/main/java/com/example/backend/domain/define/study/todo/repository/StudyTodoRepositoryImpl.java
  backend/src/main/java/com/example/backend/study/api/service/commit/StudyCommitService.java
  backend/src/main/java/com/example/backend/study/api/service/commit/response/CommitInfoResponse.java
  backend/src/main/java/com/example/backend/study/api/service/todo/StudyTodoService.java
  backend/src/main/java/com/example/backend/study/api/service/user/UserService.java
  backend/src/test/java/com/example/backend/domain/define/study/todo/repository/StudyTodoRepositoryTest.java
  backend/src/test/java/com/example/backend/study/api/service/commit/StudyCommitServiceTest.java
Labels: refactor, 이정우 진행중🔥

#567 [BE] refactor(#566): 커밋 리스트 필드 추가
  backend/src/main/java/com/example/backend/domain/define/study/commit/repository/StudyCommitRepositoryImpl.java
  backend/src/main/java/com/example/backend/domain/define/study/todo/repository/StudyTodoRepositoryImpl.java
  backend/src/main/java/com/example/backend/study/api/service/commit/StudyCommitService.java
  backend/src/main/java/com/example/backend/study/api/service/commit/response/CommitInfoResponse.java
  backend/src/main/java/com/example/backend/study/api/service/todo/StudyTodoService.java
  backend/src/main/java/com/example/backend/study/api/service/user/UserService.java
Labels: refactor, 이정우 진행중🔥

#569 [BE] refactor(#568): LocalDateTime mapper 수정
  backend/src/main/java/com/example/backend/auth/config/ProjectConfig.java
Labels: refactor, 이정우 진행중🔥

#573 [BE] refactor(#572): 스코어 호출 오류
  backend/src/main/java/com/example/backend/auth/api/service/rank/RankingService.java
  backend/src/main/java/com/example/backend/auth/api/service/rank/response/StudyRankingResponse.java
  backend/src/main/java/com/example/backend/auth/api/service/rank/response/UserRankingResponse.java
  backend/src/test/java/com/example/backend/auth/api/service/rank/RankingServiceTest.java
Labels: refactor, 이정우 진행중🔥

#574 [BE] refactor(#572): 스터디 초기점수 수정
  backend/src/main/java/com/example/backend/study/api/service/info/StudyInfoService.java
Labels: refactor, 이정우 진행중🔥

#576 [BE]: feat(#575): 커밋 시 last commit date 업데이트 로직 구현
  backend/src/main/java/com/example/backend/domain/define/study/info/StudyInfo.java
  backend/src/main/java/com/example/backend/webhook/api/service/WebhookService.java
  backend/src/test/java/com/example/backend/domain/define/study/info/StudyInfoFixture.java
  backend/src/test/java/com/example/backend/webhook/api/service/WebhookServiceTest.java
Labels: feat, 이주성 진행중🔥
