Repository DKU-Dgaja/gitudy, pull requests merged in 2024-06, with the labels that each got.

#324 [AN] feat(#318): 마이스터디 목록 클릭 시 각 스터디 상세정보 api 호출 기능 구현
  android/gitudy/data/src/main/java/com/takseha/data/api/gitudy/study/GitudyStudyApi.kt
  android/gitudy/data/src/main/java/com/takseha/data/dto/mystudy/MyStudyResponse.kt
  android/gitudy/data/src/main/java/com/takseha/data/dto/mystudy/MyStudyWithTodo.kt
  android/gitudy/data/src/main/java/com/takseha/data/repository/study/GitudyStudyRepository.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/adapter/MyStudyRVAdapter.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/mystudy/MyStudyHomeFragment.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/mystudy/MyStudyMainActivity.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/viewmodel/feed/MakeStudyViewModel.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/viewmodel/home/MainHomeViewModel.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/viewmodel/mystudy/MyStudyMainViewModel.kt
  android/gitudy/presentation/src/main/res/drawable/ic_git_200.png
  android/gitudy/presentation/src/main/res/drawable/ic_study_green.png
  android/gitudy/presentation/src/main/res/layout/activity_my_study_main.xml
  android/gitudy/presentation/src/main/res/layout/item_mystudy.xml
  android/gitudy/presentation/src/main/res/values/strings.xml
Labels: feat, 탁세하 진행중🔥

#323 [BE] fix(#322): 스터디 상세정보 수정
  backend/src/main/java/com/example/backend/study/api/controller/info/response/StudyInfoDetailResponse.java
  backend/src/test/java/com/example/backend/study/api/service/info/StudyInfoServiceTest.java
Labels: fix, 구영민 진행중🔥

#326 [BE] fix(#322): isLeader 필드 추가
  backend/src/main/java/com/example/backend/domain/define/study/info/repository/StudyInfoRepositoryImpl.java
  backend/src/main/java/com/example/backend/study/api/controller/info/StudyInfoController.java
  backend/src/main/java/com/example/backend/study/api/controller/info/response/StudyInfoDetailResponse.java
  backend/src/main/java/com/example/backend/study/api/controller/info/response/StudyInfoListResponse.java
  backend/src/main/java/com/example/backend/study/api/service/info/StudyInfoService.java
  backend/src/test/java/com/example/backend/study/api/controller/info/StudyInfoControllerTest.java
  backend/src/test/java/com/example/backend/study/api/service/info/StudyInfoServiceTest.java
Labels: feat, 구영민 진행중🔥

#330 [AN] feat(#329): 마이스터디 메인 페이지 내 to do 정보 api 호출 기능 구현
  android/gitudy/presentation/src/main/java/com/takseha/presentation/adapter/MyStudyRVAdapter.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/mystudy/MyStudyMainActivity.kt
  android/gitudy/presentation/src/main/res/layout/activity_my_study_main.xml
Labels: feat, 탁세하 진행중🔥

#333 [AN] feat(#331): 커밋 컨벤션 등록 api 호출 기능 구현
  android/gitudy/data/src/main/java/com/takseha/data/api/gitudy/study/GitudyStudyApi.kt
  android/gitudy/data/src/main/java/com/takseha/data/dto/mystudy/SetConventionRequest.kt
  android/gitudy/data/src/main/java/com/takseha/data/dto/mystudy/SetConventionResponse.kt
  android/gitudy/data/src/main/java/com/takseha/data/repository/study/GitudyStudyRepository.kt
  android/gitudy/presentation/src/main/AndroidManifest.xml
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/mystudy/AddTodoActivity.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/mystudy/CommitConventionActivity.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/mystudy/CommitConventionFragment.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/mystudy/MyStudyMainActivity.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/viewmodel/mystudy/AddTodoViewModel.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/viewmodel/mystudy/CommitConventionViewModel.kt
  android/gitudy/presentation/src/main/res/layout/activity_commit_convention.xml
  android/gitudy/presentation/src/main/res/layout/activity_my_study_main.xml
  android/gitudy/presentation/src/main/res/layout/fragment_commit_convention.xml
  android/gitudy/presentation/src/main/res/values/strings.xml
Labels: feat, 탁세하 진행중🔥

#335 [AN] feat(#334): 마이스터디 메인 페이지 내 커밋 컨벤션 정보 api 호출 기능 구현
  android/gitudy/data/src/main/java/com/takseha/data/api/gitudy/study/GitudyStudyApi.kt
  android/gitudy/data/src/main/java/com/takseha/data/dto/mystudy/ConventionResponse.kt
  android/gitudy/data/src/main/java/com/takseha/data/repository/study/GitudyStudyRepository.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/home/MainHomeFragment.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/mystudy/CommitConventionActivity.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/mystudy/MyStudyHomeFragment.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/mystudy/MyStudyMainActivity.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/viewmodel/home/MainHomeViewModel.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/viewmodel/mystudy/CommitConventionViewModel.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/viewmodel/mystudy/MyStudyMainViewModel.kt
  android/gitudy/presentation/src/main/res/layout/activity_commit_convention.xml
  android/gitudy/presentation/src/main/res/layout/activity_my_study_main.xml
  android/gitudy/presentation/src/main/res/values/strings.xml
Labels: feat, 탁세하 진행중🔥

#338 [BE] feat(#332): todo 전체 조회 시 커밋 리스트를 포함해 반환
  backend/src/main/java/com/example/backend/domain/define/study/commit/repository/StudyCommitRepository.java
  backend/src/main/java/com/example/backend/domain/define/study/todo/repository/StudyTodoRepositoryCustom.java
  backend/src/main/java/com/example/backend/domain/define/study/todo/repository/StudyTodoRepositoryImpl.java
  backend/src/main/java/com/example/backend/study/api/controller/commit/StudyCommitController.java
  backend/src/main/java/com/example/backend/study/api/controller/todo/StudyTodoController.java
  backend/src/main/java/com/example/backend/study/api/controller/todo/response/StudyTodoListAndCursorIdxResponse.java
  backend/src/main/java/com/example/backend/study/api/controller/todo/response/StudyTodoWithCommitsResponse.java
  backend/src/main/java/com/example/backend/study/api/service/todo/StudyTodoService.java
  backend/src/test/java/com/example/backend/domain/define/study/todo/repository/StudyTodoRepositoryTest.java
  backend/src/test/java/com/example/backend/study/api/controller/todo/StudyTodoControllerTest.java
  backend/src/test/java/com/example/backend/study/api/service/todo/StudyTodoServiceTest.java
Labels: feat, 이주성 진행중🔥

#339 [AN] feat(#337): 스터디 신청 페이지전체 스터디 상세 페이지 로직 구현
  android/gitudy/data/src/main/java/com/takseha/data/dto/feed/StudyListResponse.kt
  android/gitudy/data/src/main/java/com/takseha/data/dto/mystudy/Commit.kt
  android/gitudy/data/src/main/java/com/takseha/data/dto/mystudy/TodoListResponse.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/adapter/FeedRVAdapter.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/adapter/MyStudyRVAdapter.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/feed/FeedHomeFragment.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/feed/StudyApplyActivity.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/home/MainHomeFragment.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/mystudy/CommitConventionActivity.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/mystudy/MyStudyHomeFragment.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/mystudy/MyStudyMainActivity.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/viewmodel/feed/MakeStudyViewModel.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/viewmodel/feed/StudyApplyViewModel.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/viewmodel/home/MainHomeViewModel.kt
  android/gitudy/presentation/src/main/res/layout/activity_study_apply.xml
  android/gitudy/presentation/src/main/res/layout/fragment_feed_home.xml
  android/gitudy/presentation/src/main/res/layout/fragment_main_home.xml
  android/gitudy/presentation/src/main/res/layout/fragment_my_study_home.xml
Labels: feat, 탁세하 진행중🔥

#342 [BE] refactor(#341): enum 타입 data truncated 에러
  backend/src/main/java/com/example/backend/domain/define/study/commit/constant/CommitStatus.java
  backend/src/main/java/com/example/backend/domain/define/study/info/constant/StudyStatus.java
  backend/src/main/java/com/example/backend/domain/define/study/member/StudyMember.java
  backend/src/main/java/com/example/backend/domain/define/study/member/constant/StudyMemberStatus.java
  backend/src/main/java/com/example/backend/study/api/service/member/StudyMemberService.java
Labels: refactor, 이주성 진행중🔥

#345 [BE] refactor(#341): 스터디 가입 로직 수정
  backend/src/main/java/com/example/backend/study/api/service/member/StudyMemberService.java
Labels: fix

#346 An feat(#340) 스터디 신청 페이지 스터디 신청 및 알림 api 호출 기능 구현
  android/gitudy/data/src/main/java/com/takseha/data/api/gitudy/member/GitudyMemberApi.kt
  android/gitudy/data/src/main/java/com/takseha/data/dto/feed/MessageRequest.kt
  android/gitudy/data/src/main/java/com/takseha/data/dto/mystudy/RogerResponse.kt
  android/gitudy/data/src/main/java/com/takseha/data/repository/member/GitudyMemberRepository.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/firebase/MyFirebaseMessagingService.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/auth/SocialLoginCompleteActivity.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/common/CustomDialog.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/feed/StudyApplyActivity.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/mystudy/AddTodoActivity.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/mystudy/MyStudyMainActivity.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/viewmodel/feed/StudyApplyViewModel.kt
  android/gitudy/presentation/src/main/res/layout/activity_study_apply.xml
  android/gitudy/presentation/src/main/res/layout/fragment_study_apply.xml
  android/gitudy/presentation/src/main/res/layout/layout_dialog.xml
  android/gitudy/presentation/src/main/res/values/strings.xml
Labels: feat, 탁세하 진행중🔥

#348 [AN] feat(#347): 스터디 멤버 리스트 api 호출 로직 구현
  android/gitudy/data/src/main/java/com/takseha/data/api/gitudy/member/GitudyMemberApi.kt
  android/gitudy/data/src/main/java/com/takseha/data/dto/mystudy/StudyMemberListResponse.kt
  android/gitudy/data/src/main/java/com/takseha/data/repository/member/GitudyMemberRepository.kt
  android/gitudy/presentation/build.gradle.kts
  android/gitudy/presentation/src/main/java/com/takseha/presentation/adapter/MemberRankRVAdapter.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/mystudy/MyStudyMainActivity.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/viewmodel/mystudy/MyStudyMainViewModel.kt
  android/gitudy/presentation/src/main/res/drawable/logo_profile_default.png
  android/gitudy/presentation/src/main/res/layout/item_member_in_rank.xml
  android/gitudy/presentation/src/main/res/values/strings.xml
Labels: feat, 탁세하 진행중🔥

#351 [AN] feat(#349): To-Do 리스트 api 호출 로직 구현
  android/gitudy/data/src/main/java/com/takseha/data/dto/mystudy/Commit.kt
  android/gitudy/data/src/main/java/com/takseha/data/dto/mystudy/CommitStatus.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/adapter/MyStudyRVAdapter.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/adapter/ToDoListRVAdapter.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/mystudy/MyStudyMainActivity.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/mystudy/ToDoActivity.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/viewmodel/mystudy/TodoViewModel.kt
  android/gitudy/presentation/src/main/res/layout/activity_my_study_main.xml
  android/gitudy/presentation/src/main/res/layout/activity_to_do.xml
  android/gitudy/presentation/src/main/res/layout/item_commit.xml
  android/gitudy/presentation/src/main/res/layout/item_todo.xml
  android/gitudy/presentation/src/main/res/values/strings.xml
Labels: feat, 탁세하 진행중🔥

#355 [Be] refactor(#354): cors 설정 수정
  backend/src/main/java/com/example/backend/auth/config/ProjectConfig.java
Labels: refactor, 이주성 진행중🔥

#357 [BE] refactor(#356): DTO 수정
  backend/src/main/java/com/example/backend/domain/define/study/comment/study/repository/StudyCommentRepositoryImpl.java
  backend/src/main/java/com/example/backend/study/api/controller/comment/study/response/StudyCommentResponse.java
Labels: refactor, 구영민 진행중🔥

#358 [AN] feat(#352): To-Do 별 커밋 목록 나타내기
  android/gitudy/data/src/main/java/com/takseha/data/dto/mystudy/Commit.kt
  android/gitudy/data/src/main/java/com/takseha/data/dto/mystudy/TodoListResponse.kt
  android/gitudy/presentation/build.gradle.kts
  android/gitudy/presentation/src/main/ic_launcher-playstore.png
  android/gitudy/presentation/src/main/java/com/takseha/presentation/adapter/CommitListRVAdapter.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/adapter/FeedRVAdapter.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/adapter/MyStudyRVAdapter.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/adapter/ToDoListRVAdapter.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/feed/FeedHomeFragment.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/feed/StudyApplyActivity.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/mystudy/AddTodoActivity.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/mystudy/CommitConventionActivity.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/mystudy/MyStudyMainActivity.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/mystudy/ToDoActivity.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/profile/CommitWebViewFragment.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/profile/MyCommitFragment.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/profile/ProfileHomeFragment.kt
  android/gitudy/presentation/src/main/res/drawable/ic_launch_background_gitudy.png
  android/gitudy/presentation/src/main/res/drawable/logo_gitudy.png
  android/gitudy/presentation/src/main/res/layout/activity_my_study_main.xml
  android/gitudy/presentation/src/main/res/layout/activity_splash.xml
  android/gitudy/presentation/src/main/res/layout/activity_to_do.xml
  android/gitudy/presentation/src/main/res/layout/fragment_commit_web_view.xml
  android/gitudy/presentation/src/main/res/layout/fragment_feed_home.xml
  android/gitudy/presentation/src/main/res/layout/fragment_my_commit_detail.xml
  android/gitudy/presentation/src/main/res/layout/fragment_profile_home.xml
  android/gitudy/presentation/src/main/res/layout/item_todo.xml
  android/gitudy/presentation/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  android/gitudy/presentation/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  android/gitudy/presentation/src/main/res/mipmap-hdpi/ic_launcher.webp
  android/gitudy/presentation/src/main/res/mipmap-hdpi/ic_launcher_background.webp
  android/gitudy/presentation/src/main/res/mipmap-hdpi/ic_launcher_foreground.webp
  android/gitudy/presentation/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  android/gitudy/presentation/src/main/res/mipmap-mdpi/ic_launcher.webp
  android/gitudy/presentation/src/main/res/mipmap-mdpi/ic_launcher_background.webp
  android/gitudy/presentation/src/main/res/mipmap-mdpi/ic_launcher_foreground.webp
  android/gitudy/presentation/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  android/gitudy/presentation/src/main/res/mipmap-xhdpi/ic_launcher.webp
  android/gitudy/presentation/src/main/res/mipmap-xhdpi/ic_launcher_background.webp
  android/gitudy/presentation/src/main/res/mipmap-xhdpi/ic_launcher_foreground.webp
  android/gitudy/presentation/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  android/gitudy/presentation/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  android/gitudy/presentation/src/main/res/mipmap-xxhdpi/ic_launcher_background.webp
  android/gitudy/presentation/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.webp
  android/gitudy/presentation/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  android/gitudy/presentation/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  android/gitudy/presentation/src/main/res/mipmap-xxxhdpi/ic_launcher_background.webp
  android/gitudy/presentation/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.webp
  android/gitudy/presentation/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  android/gitudy/presentation/src/main/res/values/strings.xml
Labels: feat, 탁세하 진행중🔥

#362 [Be] fix(#361): 커밋 패치 로직이 작동하지 않는 문제 발생
  backend/src/main/java/com/example/backend/domain/define/study/commit/repository/StudyCommitRepository.java
  backend/src/main/java/com/example/backend/domain/define/study/commit/repository/StudyCommitRepositoryCustom.java
  backend/src/main/java/com/example/backend/domain/define/study/commit/repository/StudyCommitRepositoryImpl.java
  backend/src/main/java/com/example/backend/study/api/service/commit/StudyCommitService.java
  backend/src/main/java/com/example/backend/study/api/service/github/GithubApiService.java
  backend/src/main/java/com/example/backend/study/api/service/todo/StudyTodoService.java
  backend/src/test/java/com/example/backend/domain/define/study/commit/repository/StudyCommitRepositoryTest.java
  backend/src/test/java/com/example/backend/study/api/service/commit/CommitFetchPerformanceTest.java
  backend/src/test/java/com/example/backend/study/api/service/commit/CommitFetchServiceTest.java
  backend/src/test/java/com/example/backend/study/api/service/commit/StudyCommitServiceTest.java
  backend/src/test/java/com/example/backend/study/api/service/convention/StudyConventionServiceTest.java
  backend/src/test/java/com/example/backend/study/api/service/github/GithubApiServiceTest.java
  backend/src/test/java/com/example/backend/study/api/service/todo/StudyTodoServiceTest.java
Labels: fix, 이주성 진행중🔥

#368 [BE] refactor(#363): 스케줄링 임시 비활성화
  backend/src/main/java/com/example/backend/study/api/scheduler/service/ScheduledCommitFetchService.java
Labels: refactor, 이주성 진행중🔥

#367 [BE] refactor(#364): 스터디 등록요청 dto수정
  backend/src/main/java/com/example/backend/study/api/controller/info/request/StudyInfoRegisterRequest.java
  backend/src/main/java/com/example/backend/study/api/service/info/StudyInfoService.java
  backend/src/test/java/com/example/backend/domain/define/study/info/StudyInfoFixture.java
  backend/src/test/java/com/example/backend/study/api/service/info/StudyInfoServiceTest.java
Labels: refactor, 구영민 진행중🔥

#370 [BE] fix(#369) 충돌해결 #369
  backend/src/main/java/com/example/backend/study/api/controller/info/request/StudyInfoRegisterRequest.java
Labels: fix, 구영민 진행중🔥
