Repository DKU-Dgaja/gitudy, pull requests merged in 2024-09, with the labels that each got.

#585 [BE] refactor(#583): 커밋 메시지 알림 오류 + 문구 수정
  backend/src/main/java/com/example/backend/domain/define/fcm/listener/CommitRegisterListener.java
  backend/src/main/java/com/example/backend/domain/define/fcm/listener/ResignMemberListener.java
  backend/src/main/java/com/example/backend/domain/define/fcm/listener/WithdrawalMemberListener.java
  backend/src/main/java/com/example/backend/study/api/event/service/NoticeService.java
  backend/src/main/java/com/example/backend/study/api/service/commit/StudyCommitService.java
  backend/src/main/java/com/example/backend/webhook/api/service/WebhookService.java
Labels: refactor, 이정우 진행중🔥

#589 [BE] refactor(#588): UI 피드백 반영 및 사소한 버그 수정
  backend/src/main/java/com/example/backend/study/api/controller/commit/StudyCommitController.java
  backend/src/main/java/com/example/backend/study/api/controller/todo/StudyTodoController.java
  backend/src/main/java/com/example/backend/study/api/controller/todo/response/StudyTodoProgressResponse.java
  backend/src/main/java/com/example/backend/study/api/service/todo/StudyTodoService.java
  backend/src/test/java/com/example/backend/domain/define/study/todo/StudyTodoFixture.java
  backend/src/test/java/com/example/backend/study/api/controller/commit/StudyCommitControllerTest.java
  backend/src/test/java/com/example/backend/study/api/controller/todo/StudyTodoControllerTest.java
  backend/src/test/java/com/example/backend/study/api/service/todo/StudyTodoServiceTest.java
Labels: refactor, 이주성 진행중🔥

#593 [BE] refactor(#592): 회원 탈퇴 로직 수정
  backend/src/main/java/com/example/backend/auth/api/controller/auth/AuthController.java
  backend/src/main/java/com/example/backend/auth/api/service/auth/AuthService.java
  backend/src/main/java/com/example/backend/domain/define/account/user/User.java
  backend/src/main/java/com/example/backend/domain/define/study/info/repository/StudyInfoRepository.java
  backend/src/main/java/com/example/backend/domain/define/study/info/repository/StudyInfoRepositoryCustom.java
  backend/src/main/java/com/example/backend/domain/define/study/info/repository/StudyInfoRepositoryImpl.java
  backend/src/main/java/com/example/backend/domain/define/study/member/repository/StudyMemberRepositoryCustom.java
  backend/src/main/java/com/example/backend/domain/define/study/member/repository/StudyMemberRepositoryImpl.java
  backend/src/main/java/com/example/backend/study/api/service/info/StudyInfoService.java
  backend/src/main/java/com/example/backend/study/api/service/info/StudyManagementService.java
  backend/src/main/java/com/example/backend/study/api/service/todo/StudyTodoService.java
  backend/src/test/java/com/example/backend/auth/api/controller/auth/AuthControllerTest.java
  backend/src/test/java/com/example/backend/auth/api/service/auth/AuthServiceTest.java
  backend/src/test/java/com/example/backend/domain/define/study/info/repository/StudyInfoRepositoryTest.java
  backend/src/test/java/com/example/backend/domain/define/study/member/repository/StudyMemberRepositoryTest.java
  backend/src/test/java/com/example/backend/study/api/controller/bookmark/StudyBookmarkControllerTest.java
  backend/src/test/java/com/example/backend/study/api/controller/category/info/CategoryControllerTest.java
  backend/src/test/java/com/example/backend/study/api/controller/comment/commit/CommitCommentControllerTest.java
  backend/src/test/java/com/example/backend/study/api/controller/comment/study/StudyCommentControllerTest.java
  backend/src/test/java/com/example/backend/study/api/controller/commit/StudyCommitControllerTest.java
  backend/src/test/java/com/example/backend/study/api/controller/convention/StudyConventionControllerTest.java
  backend/src/test/java/com/example/backend/study/api/controller/info/StudyInfoControllerTest.java
  backend/src/test/java/com/example/backend/study/api/controller/member/StudyMemberControllerTest.java
  backend/src/test/java/com/example/backend/study/api/controller/todo/StudyTodoControllerTest.java
  backend/src/test/java/com/example/backend/study/api/event/controller/FcmControllerTest.java
  backend/src/test/java/com/example/backend/study/api/event/controller/NoticeControllerTest.java
  backend/src/test/java/com/example/backend/study/api/service/info/StudyManagementServiceTest.java
  backend/src/test/java/com/example/backend/webhook/api/controller/WebhookControllerTest.java
  backend/src/test/java/com/example/backend/webhook/api/service/WebhookServiceTest.java
Labels: refactor, 이주성 진행중🔥

#595 [BE] refactor(#594): 비효율적인 todo 조회 쿼리 수정
  backend/src/main/java/com/example/backend/domain/define/study/todo/repository/StudyTodoRepositoryImpl.java
Labels: refactor, 이주성 진행중🔥

#591 [BE] refactor(#590): 랭킹 시스템 로직 수정
  backend/src/main/java/com/example/backend/auth/api/service/auth/AuthService.java
  backend/src/main/java/com/example/backend/auth/api/service/rank/RankingService.java
  backend/src/main/java/com/example/backend/study/api/service/info/StudyInfoService.java
  backend/src/test/java/com/example/backend/auth/api/service/rank/RankingServiceTest.java
Labels: refactor, 이정우 진행중🔥

#598 [BE] refactor(#596): 회원가입 시 github Id 입력받지 않도록 수정
  backend/src/main/java/com/example/backend/auth/api/controller/auth/request/AuthRegisterRequest.java
  backend/src/main/java/com/example/backend/auth/api/service/auth/AuthService.java
  backend/src/main/java/com/example/backend/auth/api/service/auth/request/AuthServiceRegisterRequest.java
  backend/src/main/java/com/example/backend/domain/define/account/user/User.java
  backend/src/test/java/com/example/backend/auth/api/controller/auth/AuthControllerTest.java
  backend/src/test/java/com/example/backend/auth/api/service/auth/AuthServiceTest.java
Labels: refactor, 이주성 진행중🔥

#606 [BE] refactor(#605): 회원 탈퇴 로직 수정
  backend/src/main/java/com/example/backend/domain/define/account/user/User.java
  backend/src/test/java/com/example/backend/auth/api/service/auth/AuthServiceTest.java
Labels: refactor, 이주성 진행중🔥

#612 [BE] refactor(#611): 서버 시간 불일치 문제 해결
  backend/src/main/java/com/example/backend/domain/define/study/todo/repository/StudyTodoRepositoryImpl.java
  backend/src/main/java/com/example/backend/study/api/service/todo/StudyTodoService.java
Labels: refactor, 이주성 진행중🔥

#608 [BE] refactor(#604): 스터디 재가입 방지 수정
  backend/src/main/java/com/example/backend/domain/define/study/member/repository/StudyMemberRepositoryImpl.java
  backend/src/main/java/com/example/backend/study/api/service/member/StudyMemberService.java
  backend/src/test/java/com/example/backend/domain/define/fcm/repository/FcmTokenRepositoryTest.java
Labels: refactor, 이정우 진행중🔥

#618 [AN] feat(#617): 앱 apk bundle로 추출
  android/gitudy/app/src/main/AndroidManifest.xml
  android/gitudy/data/src/main/java/com/takseha/data/dto/mystudy/StudyInfoResponse.kt
  android/gitudy/presentation/src/main/ic_launcher-playstore.png
  android/gitudy/presentation/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  android/gitudy/presentation/src/main/res/mipmap-hdpi/ic_launcher.png
  android/gitudy/presentation/src/main/res/mipmap-hdpi/ic_launcher.webp
  android/gitudy/presentation/src/main/res/mipmap-hdpi/ic_launcher_background.png
  android/gitudy/presentation/src/main/res/mipmap-hdpi/ic_launcher_background.webp
  android/gitudy/presentation/src/main/res/mipmap-hdpi/ic_launcher_foreground.png
  android/gitudy/presentation/src/main/res/mipmap-hdpi/ic_launcher_foreground.webp
  android/gitudy/presentation/src/main/res/mipmap-hdpi/ic_launcher_monochrome.png
  android/gitudy/presentation/src/main/res/mipmap-mdpi/ic_launcher.png
  android/gitudy/presentation/src/main/res/mipmap-mdpi/ic_launcher.webp
  android/gitudy/presentation/src/main/res/mipmap-mdpi/ic_launcher_background.png
  android/gitudy/presentation/src/main/res/mipmap-mdpi/ic_launcher_background.webp
  android/gitudy/presentation/src/main/res/mipmap-mdpi/ic_launcher_foreground.png
  android/gitudy/presentation/src/main/res/mipmap-mdpi/ic_launcher_foreground.webp
  android/gitudy/presentation/src/main/res/mipmap-mdpi/ic_launcher_monochrome.png
  android/gitudy/presentation/src/main/res/mipmap-xhdpi/ic_launcher.png
  android/gitudy/presentation/src/main/res/mipmap-xhdpi/ic_launcher.webp
  android/gitudy/presentation/src/main/res/mipmap-xhdpi/ic_launcher_background.png
  android/gitudy/presentation/src/main/res/mipmap-xhdpi/ic_launcher_background.webp
  android/gitudy/presentation/src/main/res/mipmap-xhdpi/ic_launcher_foreground.png
  android/gitudy/presentation/src/main/res/mipmap-xhdpi/ic_launcher_foreground.webp
  android/gitudy/presentation/src/main/res/mipmap-xhdpi/ic_launcher_monochrome.png
  android/gitudy/presentation/src/main/res/mipmap-xxhdpi/ic_launcher.png
  android/gitudy/presentation/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  android/gitudy/presentation/src/main/res/mipmap-xxhdpi/ic_launcher_background.png
  android/gitudy/presentation/src/main/res/mipmap-xxhdpi/ic_launcher_background.webp
  android/gitudy/presentation/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.png
  android/gitudy/presentation/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.webp
  android/gitudy/presentation/src/main/res/mipmap-xxhdpi/ic_launcher_monochrome.png
  android/gitudy/presentation/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  android/gitudy/presentation/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  android/gitudy/presentation/src/main/res/mipmap-xxxhdpi/ic_launcher_background.png
  android/gitudy/presentation/src/main/res/mipmap-xxxhdpi/ic_launcher_background.webp
  android/gitudy/presentation/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  android/gitudy/presentation/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.webp
  android/gitudy/presentation/src/main/res/mipmap-xxxhdpi/ic_launcher_monochrome.png
Labels: feat

#620 [AN] fix(#619): 네트워크 에러 생길 시 스낵바 안 뜨는 에러 해결
  android/gitudy/data/src/main/java/com/takseha/data/token/TokenManager.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/SplashActivity.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/home/MainHomeActivity.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/profile/PersonalInfoTermFragment.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/viewmodel/auth/LoginViewModel.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/viewmodel/auth/LoginWebViewViewModel.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/viewmodel/auth/RegisterViewModel.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/viewmodel/auth/SplashViewModel.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/viewmodel/common/BaseApplicationViewModel.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/viewmodel/common/BaseViewModel.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/viewmodel/feed/MakeStudyViewModel.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/viewmodel/feed/StudyApplyViewModel.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/viewmodel/mystudy/AddTodoViewModel.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/viewmodel/mystudy/CommitDetailViewModel.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/viewmodel/mystudy/StudyApplyMemberProfileViewModel.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/viewmodel/profile/ProfileEditViewModel.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/viewmodel/profile/SettingHomeViewModel.kt
  android/gitudy/presentation/src/main/res/layout/fragment_personal_info_term.xml
  android/gitudy/presentation/src/main/res/navigation/setting_nav.xml
Labels: fix, 탁세하 진행중🔥

#627 [BE] refactor: todo 진행률 api 해당하는 todo가 없을 경우 에러가 아닌 null 반환
  backend/src/main/java/com/example/backend/domain/define/study/todo/repository/StudyTodoRepository.java
  backend/src/main/java/com/example/backend/study/api/service/member/StudyMemberService.java
  backend/src/main/java/com/example/backend/study/api/service/todo/StudyTodoService.java
  backend/src/test/java/com/example/backend/domain/define/study/todo/repository/StudyTodoRepositoryTest.java
  backend/src/test/java/com/example/backend/study/api/service/member/StudyMemberServiceTest.java
  backend/src/test/java/com/example/backend/study/api/service/todo/StudyTodoServiceTest.java
Labels: refactor, 이주성 진행중🔥

#631 [AN] VOC(#630): To-Do 관련 업데이트
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/mystudy/MyStudyMainFragment.kt
  android/gitudy/presentation/src/main/res/drawable/ic_info.png
  android/gitudy/presentation/src/main/res/layout/fragment_my_study_main.xml
  android/gitudy/presentation/src/main/res/values/strings.xml
Labels: 탁세하 진행중🔥, voc

#633 [AN] VOC(#632): 기타 UI 수정
  android/gitudy/presentation/src/main/java/com/takseha/presentation/adapter/DetailCommentListRVAdapter.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/feed/FeedHomeFragment.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/feed/StudyApplyInfoFragment.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/home/MainHomeAlertFragment.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/home/MainHomeFragment.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/mystudy/MyStudyHomeFragment.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/mystudy/ToDoFragment.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/profile/ProfileHomeFragment.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/viewmodel/feed/FeedHomeViewModel.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/viewmodel/feed/MakeStudyViewModel.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/viewmodel/home/MainHomeViewModel.kt
  android/gitudy/presentation/src/main/java/com/takseha/presentation/viewmodel/mystudy/MyStudyHomeViewModel.kt
  android/gitudy/presentation/src/main/res/drawable/ic_alert_active.png
  android/gitudy/presentation/src/main/res/layout/fragment_feed_home.xml
  android/gitudy/presentation/src/main/res/layout/fragment_main_home.xml
  android/gitudy/presentation/src/main/res/layout/fragment_make_study3.xml
  android/gitudy/presentation/src/main/res/layout/fragment_my_study_home.xml
  android/gitudy/presentation/src/main/res/layout/fragment_my_study_main.xml
  android/gitudy/presentation/src/main/res/layout/fragment_profile_home.xml
  android/gitudy/presentation/src/main/res/layout/fragment_study_apply_info.xml
  android/gitudy/presentation/src/main/res/layout/fragment_to_do.xml
  android/gitudy/presentation/src/main/res/layout/item_alert.xml
  android/gitudy/presentation/src/main/res/layout/item_category.xml
  android/gitudy/presentation/src/main/res/layout/item_comment_detail.xml
  android/gitudy/presentation/src/main/res/layout/item_feed.xml
Labels: 탁세하 진행중🔥, voc

#635 [BE] refactor: studyinfo info 필드 속성 text로 변경
  backend/src/main/java/com/example/backend/auth/api/controller/auth/request/UserNameRequest.java
  backend/src/main/java/com/example/backend/domain/define/study/info/StudyInfo.java
  backend/src/main/java/com/example/backend/domain/define/study/todo/repository/StudyTodoRepositoryImpl.java
  backend/src/main/java/com/example/backend/study/api/service/member/StudyMemberService.java
  backend/src/test/java/com/example/backend/study/api/service/info/StudyManagementServiceTest.java
Labels: refactor, 이주성 진행중🔥
